### ISSUE TITLE
StripLogs money glitch

### ISSUE THREAD

**Issue by Bedah95** [Zrips/Jobs#1010]
No income and experience if you strip "OAK_LOG".
Infinite money glitch if you hold right-mousekey and strip "STRIPPED_OAK_LOG".

**CONFIG SECTION:**
```
    StripLogs:
      STRIPPED_OAK_LOG:
        income: 0.1
        experience: 9
      STRIPPED_SPRUCE_LOG:
        income: 0.1
        experience: 9
...
```

---

Paper 1.16.4 298
Jobs 4.16.4,4.16.3
