### ISSUE TITLE
Deductions aren't boosted

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#1035]
***Description of issue:**
The permissions for the job boost `(jobs.boost.[jobname].money.[amount]` + `jobs.boost.[jobname].exp.[amount]`) only increase exp and money earnings, but don't boost negative values. Therefore, subtractions under Place are not calculated according to the boost. This causes the anti-cheat mechanism to be overridden by deductions when the boost is removed.
_Example:_
config values:
```
  Break:
      diamond_ore:
        income: 20.32
        experience: 20.32
  Place:
      diamond_ore:
        income: -20.32
        experience: -20.32
```
With an income-boost of 25% and an exp-boost of 200% the player actually gets an income of 25.41 and 40.65 exp. However, the deductions are not calculated based on the permission, but drawn from the config, so only 20.32 income/exp is deducted when placing diamond_ore. Therefore it is possible to cheat by simply placing and breaking diamond_ore when boosts are active. It would be great if this could be fixed.

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
1.16.4
**Relevant plugins (Delete if this isn't needed):**
Jobs 4.16.4
