### ISSUE TITLE
Craft Action Bug

### ISSUE THREAD

**Issue by AlexanderMoebius** [Zrips/Jobs#1041]
***Description of issue:**
The Craft action pays per crafting and not per item that is being crafted.

For example with option
Craft:
    stick:
      income: 0.5
      points: 0.1
      experience: 0.1

if you craft multiple sticks using shift-click you only get 0.5 income instead of (sticksCraftet*0.5)

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Comment by montlikadani** [comment]
in generalConfig
```yml
  Crafting:
    # With this true, player will get money for all crafted items instead of each crafting action (like with old payment mechanic)
    # By default its false, as you can make ALOT of money if prices kept from old payment mechanics
    PayForEachCraft: false
```
