### ISSUE TITLE
PreventHopperFillUps: true doesn't work

### ISSUE THREAD

**Issue by kADOMPHy** [Zrips/Jobs#1058]
**Description of issue:**
Even with config option `PreventHopperFillUps: true` and in paper ```hopper: disable-move-event: false```, after some time the player gets paid even with hopper below the furnace. This can bee seen in this video (the payment starts at around 0:52 seconds) - https://cdn.discordapp.com/attachments/718175010912469012/798688020215234600/JobsSmelting.mp4

**CONFIG SECTION:**
```
  Smelt:
    # Prevent payments when hoppers moving items into furnace
    # Player will not get paid, but items will be smelted
    PreventHopperFillUps: true
  Brew:
    PreventBrewingStandFillUps: true
```
```
    hopper:
      cooldown-when-full: true
      disable-move-event: false
````
---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-407 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Relevant plugins:**
Plugins (5): Essentials, Jobs, Vault, ViaBackwards, ViaVersion

**Jobs version**
Jobs version 4.17.0
