### ISSUE TITLE
Scoreboard bug

### ISSUE THREAD

**Issue by Oruss7** [Zrips/Jobs#106]
When players login, they have a **permanent scoreboard** with top list i guest.
I disabled ShowToplist. But not working.
```
Scoreboard:
  # This will enables to show top list in scoreboard instead of chat
  ShowToplist: false
  # For how long to show scoreboard
  interval: 10

```
Version :
Jobs Reborn 3.9.6
Spigot 1.11.2 (lastest)

Thanks you !
