### ISSUE TITLE
Crafting a map => no reward

### ISSUE THREAD

**Issue by kikelkik** [Zrips/Jobs#1068]
***Description of issue:**
Crafting a map leads to no reward. Other materials work fine.
Excerpt of jobConfig: 
```
Craft:
      map:
        income: 35.33
        experience: 35.33
```
---

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-443

**Relevant plugins (Delete if this isn't needed):** Jobs 4.16.4
