### ISSUE TITLE
Other lines for lore with Item Boost

### ISSUE THREAD

**Issue by ArnoPompio** [Zrips/Jobs#1071]
***Description of issue:**

Hello, I was awaiting a lot for the new boost item logic but actually, I have a problem with it. 
It is perfect but It is not working when there are other lores on the same item. 

For example, this is working with the config that i put in config section :
![2021-01-28_19 46 16](https://user-images.githubusercontent.com/70692501/106184298-a58c5b00-61a1-11eb-80e5-96754189703e.png)

But this is not working :
![2021-01-28_19 46 17](https://user-images.githubusercontent.com/70692501/106184387-c2289300-61a1-11eb-839f-e5daf4cbcf98.png)

Is there a way to make this ? Is this a bug ?

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
excavationBoost:
  id: Diamond_shovel
  lore:
  - '&dExcavation I'
  moneyBoost: 0.1
  expBoost: 0.1
  pointsBoost: 0.1
  jobs:
  - all
```

---

**Server Type (Spigot/Paperspigot/etc):** Paper 439

**Server Version (using `/ver`):** 1.16.5-R0.1-SNAPSHOT

**Jobs Reborn Version**:** 1.17.1

Thanks a lot for the help you will bring to me.
