### ISSUE TITLE
[Bug] Shearing wont work in Quests

### ISSUE THREAD

**Issue by Baktus79** [Zrips/Jobs#1091]
**Description of issue:**
I am experiences that shearing wont work in Quests. This applies to every colors. Settings are default, and has not been changed.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```yaml
Quests:
      '1':
        Name: Regular Joe
        Objectives:
        - Breed;Sheep;10
        - Shear;White;10
        - Milk;Cow;3
        RewardCommands:
        - eco give [playerName] 100
        - msg [playerName] Completed quest!
        RewardDesc:
        - Be a farmer and get money
        - Get 100 for this!
```

---

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper-483 (MC: 1.16.5)
