### ISSUE TITLE
Farmer job no longer giving XP for breaking ageable crops after update

### ISSUE THREAD

**Issue by Momshroom** [Zrips/Jobs#1096]
***Description of issue:**
After updating to the latest dev release from the Jobs Discord, ageable crops (wheat, carrots, potatoes, etc) are no longer giving us Farmer XP on harvesting (but still do on planting, and crops such as cane and pumpkin still give XP on harvest)

When I revert to an earlier dev build, from late January, the crops do give XP properly.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Break:
    wheat-7:
      income: 0.09
      experience: 1
    carrots-7:
      income: 0.09
      experience: 1
    potatoes-7:
      income: 0.09
      experience: 1
    beetroots-3:
      income: 0.09
      experience: 1
    pumpkin:
      income: 0.11
      experience: 1
    melon:
      income: 0.11
      experience: 1
    sugar_cane:
      income: 0.08
      experience: 1
    cocoa-2:
      income: 0.75
      experience: 1.5
    chorus_plant:
      income: 1.5
      experience: 3
    chorus_flower-5:
      income: 3
      experience: 5
    nether_wart:
      income: 0.09
      experience: 1
  Place:
    wheat:
      income: 0.02
      experience: 0.25
    potatoes:
      income: 0.02
      experience: 0.25
    carrots:
      income: 0.02
      experience: 0.25
    beetroots:
      income: 0.02
      experience: 0.25
    cocoa:
      income: 0.02
      experience: 0.25
    pumpkin_stem:
      income: 0.02
      experience: 0.25
    melon_stem:
      income: 0.02
      experience: 0.25

```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[00:41:28 INFO]: This server is running Paper version git-Paper-468 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
Jobs 4.17.1 (Dev build from Discord from 02/20/2021
(Problem does not exist on earlier dev build I installed on 1/28/2021
