### ISSUE TITLE
Deductions aren't boosted

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#1099]
***Description of issue:**
The permissions for the job boost `(jobs.boost.[jobname].money.[amount]` + `jobs.boost.[jobname].exp.[amount]`) only increase exp and money earnings, but don't boost negative values. Therefore, subtractions under Place are not calculated according to the boost. This causes the anti-cheat mechanism to be overridden by deductions when the boost is removed.
_Example:_
config values:
```
  Break:
      diamond_ore:
        income: 20.32
        experience: 20.32
  Place:
      diamond_ore:
        income: -20.32
        experience: -20.32
```
With an income-boost of 25% and an exp-boost of 100% the player actually gets an income of 25.40 and 40.64 exp. However, the deductions are not calculated based on the permission, but drawn from the config, so only 20.32 income/exp is deducted when placing diamond_ore. 
![pay](https://user-images.githubusercontent.com/24480321/109417542-6598dd80-79c4-11eb-8c19-c2a4b8ddec15.png)
![deduction](https://user-images.githubusercontent.com/24480321/109417548-67fb3780-79c4-11eb-9710-ea70a0271fa0.png)
Therefore it is possible to cheat by simply placing and breaking diamond_ore when boosts are active. It would be great if this could be fixed.

**Server Type (Spigot/Paperspigot/etc):** 
Paper build 466
**Server Version (using `/ver`):** 
1.16.5
**Relevant plugins (Delete if this isn't needed):**
Jobs  4.17.0
