### ISSUE TITLE
Farmer Jobs JobsReborn problem

### ISSUE THREAD

**Issue by Chrqmated** [Zrips/Jobs#1100]
***Description of issue:**
Hello, I do not understand my farming profession does not work ... For example the block:
carrots-7 does not work in game, when I break and when I put the block I get no level and it's like that for all the items

**Spigot**

**1.12.2** 

**JobsReborn**

**Comment by montlikadani** [comment]
Show your Farmer job entirely

**Comment by Chrqmated** [comment]
My configuration : https://pastebin.com/fiKaYpSt

**Comment by montlikadani** [comment]
Change `carrots` to carrot in Place action
```yml
Place:
  carrot:
    income: 1
    points: 1
    experience: 1
```
