### ISSUE TITLE
Jobs top Jobname showing wrong data

### ISSUE THREAD

**Issue by EvilOlaf** [Zrips/Jobs#111]
Hey there,

when using `jobs top <jobname>` the data does not match at all with the real current top 10 users in a particular job.
This could be reproduced for all jobs.
We also have signs which show the top 4 players in each jobs. These work correctly.

Jobs 3.9.6
Spigot 1.8.8
Offline mode behind Bungee in online mode.
Other stuff that might be interesting:
```
storage-method: sqlite
MultiServerCompatability: false #As we use Jobs on one server only this is false
Optimizations:
  NewVersion: true
  DBCleaning:
    Jobs:
      Use: false
      Level: 1
    Users:
      Use: false
      Days: 60
  ShowToplist: false
```

As always
thank you for reading.
