### ISSUE TITLE
jobs toggle actionbar command not enable the action bar if the action bar disabled default

### ISSUE THREAD

**Issue by andris155** [Zrips/Jobs#1110]
***Description of issue:**
The /jobs toggle actionbar command not enable the action bar if the action bar disabled default in config.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ActionBars:
  Messages:
    # When this set to true player will see action bar messages by default
    # When false, players will see chat messages instead.
    EnabledByDefault: false
    # If true, should we mute the payment messages from appearing in chat if actionbar is disabled?
    SilentMode: true
```

---

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5
