### ISSUE TITLE
Smokers and Blast Furnaces not keeping ownership after update

### ISSUE THREAD

**Issue by IArlongI** [Zrips/Jobs#1139]
Recently updated server from 1.15.2 to 1.16.5, (Jobs 4.15.1 --> 4.16.3/4.17.0) After server restart users have to continue to reclaim smokers and blast furnaces for their job. Both are enabled to be saved but never do. Brewing stands and furnaces are working fine.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ExploitProtections:
  Furnaces:
    # When enabled, players interacted furnaces will be saved into a file and will be reassigned after restart to keep giving out money
    # Players will no longer need to click on furnace to get paid from it after server restart
    Reassign: true
    # Defines max available furnaces each player can have to get paid from
    # This can be overridden with jobs.maxfurnaces.[amount] permission node
    MaxDefaultAvailable: 64
  BlastFurnaces:
    Reassign: true
    MaxDefaultAvailable: 64
  Smokers:
    Reassign: true
    MaxDefaultAvailable: 64
  BrewingStands:
    # When enabled, players interacted brewing stands will be saved into file and will be reassigned after restart to keep giving out money
    # Players will no longer need to click on brewing stand to get paid from it after server restart
    Reassign: true
    # Defines max available brewing stands each player can have to get paid from
    # Set to 0 if you want to disable this limitation
    # This can be overridden with jobs.maxbrewingstands.[amount] permission node
    MaxDefaultAvailable: 10
```

---

**Jobs version: 4.16.3 (Have tested on 4.17.0 and 4.17.1)** 

**Server Type (Spigot/Paper/etc): git-Paper-570 (MC: 1.16.5)** 

**Server Version (using `/ver`): 1.16.5**
