### ISSUE TITLE
MonsterDamage Protection Issue

### ISSUE THREAD

**Issue by IAmSoccer** [Zrips/Jobs#1145]
***If you have the "MonsterDanage" section set to true you will not be paid for Hunter job no matter the amount of damage you do to the mob. This is one 4.17.2 in #dev-releases**

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    MonsterDamage:
      # This section controls how much damage player should do to monster for player to get paid
      # This prevents from killing monsters in one hit when they suffer in example fall damage
      Use: true
      Percentage: 50
```

---

**Jobs version: 4.17.2** 

**Server Type: git-Purpur-995** 

**Server Version (using `/ver`): 1.16.5**
