### ISSUE TITLE
Actionbar SilentMode not working as intended

### ISSUE THREAD

**Issue by McSwede** [Zrips/Jobs#1157]
**Detailed description of the issue:**
Having SilentMode enabled in config disables all actionbar messages regardless of actionbar being toggled on or off. 

Expected behaviour: SilentMode should only mute chat messages when actionbar has been toggled off like the comment in the config suggests.

---

**CONFIG SECTION:**
```
ActionBars:
  Messages:
    # When this set to true player will see action bar messages by default
    # When false, players will see chat messages instead.
    EnabledByDefault: true
    # If true, should we mute the payment messages from appearing in chat if actionbar is disabled?
    SilentMode: true
```

---

**Jobs version:** 4.17.2

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** Paper-629
