### ISSUE TITLE
Random jobs after the server restart

### ISSUE THREAD

**Issue by Zdoolny** [Zrips/Jobs#1163]
***Detailed description of the issue:** After restart players get a random job, statistic. This is caused after the create a new MSQL database.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Default language.
# Example: en, ru
# File in locale folder with same name should exist. Example: messages_ru.yml
locale-language: pl
storage:
  # storage method, can be MySQL or sqlite
  method: mysql
# Requires Mysql
mysql:
  username: 800950
  password: XYZ
  hostname: sql.pukawka.pl
  database: 800950_serwer
  table-prefix: jobs_
  verify-server-certificate: false
  use-ssl: false
  auto-reconnect: true
  characterEncoding: utf8
  encoding: UTF-8
# How often in minutes you want it to save. This must be a non-zero number
save-period: 10
# Should player data be saved on disconnect?
# Player data is always periodically auto-saved and autosaved during a clean shutdown.
# Only enable this if you have a multi-server setup, or have a really good reason for enabling this.
# Turning this on will decrease database performance.
save-on-disconnect: false
# Tool used when selecting bounds for restricted area.
```

---

**Jobs version: ** 4.17.2

**Server Type (Spigot/Paper/etc):**  Purpur

**Server Version (using `/ver`):** This server is running Purpur version git-Purpur-1064 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 12 version(s) behind
Previous version: git-Paper-556 (MC: 1.16.5)

**Relevant plugins (Delete if this isn't needed):**  Plugins (39): ActionHealth*, AdvancedBan, AuthMe, BeautyQuests, ChatEx*, Chunky, Citizens, CommandPanels, CoreProtect, CrackShot, DeadChest, DiscordSRV, Essentials, EssentialsSpawn, GlobalMarketChest, HolographicDisplays, HolographicPlaceholders, Jobs, LuckPerms, Matrix, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MythicMobs, OpenInv, PlaceholderAPI, ProtectionStones, ProtocolLib, Sentinel, ServerListPlus*, SkinsRestorer, Skript, SuperLog, TitleManager, TokenManager, Vault, VillagerModifications, WorldEdit, WorldGuard
[15:23:23] [Server thread/INFO]: [Matrix] (!) You are currently using free(trial) version of Matrix!
