### ISSUE TITLE
Placeholders for current currency, exp, pts of job

### ISSUE THREAD

**Issue by xRoXaSx** [Zrips/Jobs#1173]
**Description of new idea or improvement on existing one**
I saw the placeholder list of jobs and haven't found placeholders for money, exp, pts (one specific job like digger).  
I'd like to implement it in chat / GUIs.  

An example of what I want to have in job specific placeholders:
![image](https://user-images.githubusercontent.com/38859398/117220822-4ecd9780-ae08-11eb-8810-65ac4ab07b6a.png)

**Comment by montlikadani** [comment]
Current placeholders are: https://github.com/Zrips/Jobs/wiki/Placeholders#complexed-placeholders

Placeholderapi placeholders can only be used in other resources, such as in chat. You can't use directly these placeholders anywhere in jobs. There are own placeholders in most jobs configuration.

**Comment by xRoXaSx** [comment]
I'm aware of those placeholders...  
But there is no placeholder which obtains the current money and pts.  The only one I've found is `%jobsr_user_jexp_(jname/number)%`.  
I just want to display how much the player can gain on the **current rank** with a **specific job** (with a **specific** item) without calculating everything in 3rd party plugins ^^

**Comment by montlikadani** [comment]
So you want to get the amount of income that a player can get, for example, when a player breaks a gravel? Well, this will be a never ending work, as you have to enter all the material names to be able to return the payment amount as a value, the placeholder would look like this with the gravel: `%jobsr_payment_gravel%`, but it's not just the gravel, but also of all other known materials. So you would have to type the placeholders about 500 times in the thirdy party plugin. It doesn't make sense.

Another option that again makes no sense is that we can use a placeholder to return the payment amount for all materials and load it full screen. The question arises, 350 materials are given in a job, how can this be split in two to appear on two GUIs or on a item lore, for example? How should it be at all?

I guess you want to get the income amount from Jobs into 3rd party plugins? The result of displaying these will be in an example configuration:
```
stuff-gui:
  item1:
  lore:
  - "%jobsr_payment_digger_gravel%"
  - "%jobsr_payment_digger_redsand%"
  - "%jobsr_payment_digger_grass%"
  - "%jobsr_payment_digger_stone%"
  - "%jobsr_payment_digger_dirt%"
  - "%jobsr_payment_digger_sand%"
```
This is ugly and almost never ending work.

**Comment by xRoXaSx** [comment]
Not quite what I've imagined, that's true.  
I mean currently I'm calculating each income per block in my GUI plugin (with the provided formula from each job).
But I cannot understand why it should be a "never ending story".
I've got 7 blocks (as you mentioned above) for which I wanted to use placeholders for.  

If each key from the yaml file correspond to one specific block, those blocks could get a dynamic placeholder name and I wouldn't see any problem :o  
For example this :  
```yaml
  Break:
    red_sand:
      income: x
      points: x
      experience: x
    dirt:
      income: x
      points: x
      experience: x
```

could be
- %jobsr_payment_<job_name>_<action>_<block>_<payment_method>%
   -  %jobsr_payment_digger_break_red_sand_income%
   -  %jobsr_payment_digger_break_red_sand_points%
   -  %jobsr_payment_digger_break_red_sand_exp%

   -  %jobsr_payment_digger_break_dirt_income%
   -  %jobsr_payment_digger_break_dirt_points%
   -  %jobsr_payment_digger_break_dirt_exp%

And that could also be applied to other jobs and actions.
