### ISSUE TITLE
StripLogs action does not work for Warped/Crimson Stem, but works for standard logs like Oak

### ISSUE THREAD

**Issue by VoxPopuliZombiemold** [Zrips/Jobs#1176]
***Detailed description of the issue:**

---
StripLogs action does not work for nether wood/stem types such as Crimson Stem and Warped Stem

It does work for standard overworld wood such as Oak Wood and Dark Oak Wood.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  StripLogs:
    stripped_crimson_stem:
      income: 0.15
      points: 0.5
      experience: 3.0
```

---

**Jobs version:** 

4.17.1

**Server Type (Spigot/Paper/etc):** 

Airplane

**Server Version (using `/ver`):** 

Airplane 1.16.5-R0.1-SNAPSHOT
