### ISSUE TITLE
Removed from config SendTitleMessageWhenMaxLevelReached

### ISSUE THREAD

**Issue by Pirito10** [Zrips/Jobs#1181]
**Description:** seems like this config option has been removed at some point. It was introduced in version 4.16.3, but there's no changelog from future versions saying it was removed. I'm not sure if this was intentional, or you forgot to write it in the changelog, or it was removed by mistake.

---

**config.yml:**
```
# Send title and chat message when a player reached the maximum level in a job.
SendTitleMessageWhenMaxLevelReached: true
```

**messages_en.yml:**
```
max-level-reached:
    title: 'Max level reached'
    subtitle: '%jobname%'
    chat: 'You reached maximum level in %jobname%'
```

---

**Jobs version:** 4.17.2

**Server Type:** PaperMC

**Server Version:** git-Paper-669 (MC: 1.16.5)
