### ISSUE TITLE
Crops display incorrectly in /jobs browse and /jobs info

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#1184]
**Detailed description of the issue:**
```
    BEETROOTS-3:
    WHEAT-7:
    CARROTS-7:
    POTATOES-7:
    NETHER_WART-3:
    COCOA-2:
```
These show up as "Wheat block" in /jobs info and /jobs browse despite most of them being in the [default config](https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobs/farmer.yml).

![image](https://user-images.githubusercontent.com/29821149/118376838-0f354700-b590-11eb-8eb7-d87a5e6ddd13.png)

I checked /jobs blockinfo to make sure I was using the correct value and it said I was

![image](https://user-images.githubusercontent.com/29821149/118376851-21af8080-b590-11eb-8c9e-a14fc4bd3908.png)
---

**Jobs version:** 4.17.2

**Server Type (Spigot/Paper/etc):** Tuinity-228

**Server Version (using `/ver`):** 1.16.5
