### ISSUE TITLE
Restricted Areas don't work

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#1193]
***Detailed description of the issue:**
Restricted Area dont work
Jobs region:
When adding a restricted area using the jobs tool, it is listed under `/jobs area list` and its location is correctly recognised with `/jobs area info`. However, the specified job boost doesn't work. `/jobs bonus <job name>` always returns the output `0%`. When downgrading to version 4.17.1, the boost works and `/jobs bonus <job name>` also returns the correct result.

Worldguard region:
Worldguard restricted areas also don't work under version 4.17.2. Under version 4.17.1 worldguard restricted areas work as long as one has only one region per world. If one adds more than one region per world, the areas longer registered correctly and won't work.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
restrictedareas:
  prisma:
    multiplier: -1.0
    WG: true
  oger_hoehle:
    multiplier: -1000.0
    WG: true
  mobfarm_theunrealdoom:
    multiplier: -1.0
    WG: true
  mobfarm_theunrealdoom2:
    multiplier: -1.0
    world: Abbau
    point1:
      x: 2034
      y: 66
      z: 3125
    point2:
      x: 2076
      y: 79
      z: 3167
  farm_aerulion:
    multiplier: -1.0
    world: Nether
    point1:
      x: -1277
      y: 36
      z: -2274
    point2:
      x: -1271
      y: 42
      z: -2270

```
**Jobs version:** 
4.17.2
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.5
