### ISSUE TITLE
"exp dupe" with boosters

### ISSUE THREAD

**Issue by WarnDangerous** [Zrips/Jobs#1195]
***Detailed description of the issue:**

I use a security to lose money/exp when placing ores, it works well, for example :
- He place a diamond_ore, he lose 8 exp
- He breaks it, he earns 8 exp.

BUT

When the player get an exp/money boosters (like x2), he will earn x2 exp/money when breaking the block, but not x2 lose when breaking it, exemple : 
- He place a diamond_ore, he lose 8 exp
- He breaks it, he earns 16 exp.

He won 8 exp easily

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Break:
    STONE:
      income: 2.4
      points: 2.1
      experience: 1.6
    COBBLESTONE:
      income: 1.4
      points: 1.1
      experience: 0.6
    COAL_ORE:
      income: 7
      points: 5.5
      experience: 3
    IRON_ORE:
      income: 7
      points: 5.5
      experience: 3
    GOLD_ORE:
      income: 7
      points: 5.5
      experience: 3
    NETHER_GOLD_ORE:
      income: 7
      points: 5.5
      experience: 3
    LAPIS_ORE:
      income: 7
      points: 5.5
      experience: 3
    REDSTONE_ORE:
      income: 7
      points: 5.5
      experience: 3
    QUARTZ_ORE:
      income: 7
      points: 5.5
      experience: 3
    OBSIDIAN:
      income: 7
      points: 5.5
      experience: 3
    DIAMOND_ORE:
      income: 12
      points: 10.5
      experience: 8
    EMERALD_ORE:
      income: 12
      points: 10.5
      experience: 8
  Place:
    COAL_ORE:
      income: -7
      points: -5.5
      experience: -3
    IRON_ORE:
      income: -7
      points: -5.5
      experience: -3
    GOLD_ORE:
      income: -7
      points: -5.5
      experience: -3
    NETHER_GOLD_ORE:
      income: -7
      points: -5.5
      experience: -3
    LAPIS_ORE:
      income: -7
      points: -5.5
      experience: -3
    REDSTONE_ORE:
      income: -7
      points: -5.5
      experience: -3
    QUARTZ_ORE:
      income: -7
      points: -5.5
      experience: -3
    OBSIDIAN:
      income: -7
      points: -5.5
      experience: -3
    DIAMOND_ORE:
      income: -12
      points: -10.5
      experience: -8
    EMERALD_ORE:
      income: -12
      points: -10.5
      experience: -8
```

---

**Jobs version:** 
4.17.2

**Server Type (Spigot/Paper/etc):** 
Yatopia
**Server Version (using `/ver`):** 
yatopia-1.16.5-115
