### ISSUE TITLE
Boosted items not working on latest version

### ISSUE THREAD

**Issue by pacificminer** [Zrips/Jobs#1210]
With the last Jobs Reborn version, the Boosted Items setting no longer applies on a per-job basis. Instead, the item boosters are applied for all Jobs even when configured not to. Example:

```
blacksmith_booster_1:
  jobs:
  - Blacksmith
  moneyBoost: 1.05
  expBoost: 1.0
  pointsBoost: 1.0
  id: CLOCK
  name: '
```
Normally, this would only apply a +5% Jobs Money booster to the **Blacksmith** Job. But in the latest Jobs Reborn, this is applied to **all** Jobs instead. The system works fine in Jobs version 4.16.3 which is the version I have just updated from. I have downgraded again for testing purposes to confirm that this is the case.  I'd appreciate if this could be looked into and fixed. Thank you.
