### ISSUE TITLE
Acacia Saplings not providing payment

### ISSUE THREAD

**Issue by multirp** [Zrips/Jobs#1221]
***Detailed description of the issue:**
When attempting to use acacia saplings for job money, points, or xp, the system does not count an acacia sapling as a valid material for payout.

This affects only acacia saplings - and if relevant, the payout line for them in the hover on the jobs browse screen is prepended with a space, so instead of "Acacia Sapling" it shows " Acacia Sapling".

According to '/jobs blockinfo' while looking at a freshly placed acacia sapling, it shows:
```
Block Name: ACACIA_SAPLING
Block Data: 4
Usage:  or ACACIA_SAPLING-4
```
---

**CONFIG SECTION:**

I have used both styles of formatting, included below, in various ways (including both acacia sapling lines, removing one of them and keeping the other, capitalizing versus leaving them lower case, and the like), and had not gotten a payout on them.
```
  Place:
    acacia_sapling:
      income: 0.5
      points: 0.5
      experience: 1.0
    acacia_sapling-4:
      income: 0.5
      points: 0.5
      experience: 1.0


Place:
  materials:
  - acacia_sapling;0.5;0.5;1.0
  - acacia_sapling-4;0.5;0.5;1.0
```
---

**Jobs version:** 4.17.2

**Server Type (Spigot/Paper/etc):** Airplane, though issue occurred on Spigot (1.16.5) as well

**Server Version (using `/ver`):** git-Airplane-6 for 1.16.5 (build 6)
