### ISSUE TITLE
Broken Fisherman Job?

### ISSUE THREAD

**Issue by chommki** [Zrips/Jobs#1227]
Everytime I load the server, the fisherman job fails to follow suit and makes it unavailable to my players.  Here are the errors that I receive below:
https://pastebin.com/yfZtThFN

I'm unsure as to what might've happened, as I discovered the error a couple days after it began happening.  I've only edited jobs from the game through /jobs editjobs, and not the .yml, though I did edit the fisherman job.
Here's what the .yml file looks like, just in case:
https://pastebin.com/eGw1qHJD

I'm using the latest 5.0.0.1 update.

I am using a 1.17 (not 1.17.1) Spigot server.

/ver command result:
[13:43:54] [Server thread/INFO]: This server is running CraftBukkit version 3170-Spigot-a483d2c-ec116f6 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[13:43:54] [Server thread/INFO]: Checking version, please wait...
[13:43:54] [Thread-47/INFO]: You are 10 version(s) behind

**Comment by Zrips** [comment]
You have miss formated file. Correct one should look like
```
Fisherman:
  fullname: Fisherman
  shortname: Fi
  FullDescription:
  - Earns money from fishing.
  ChatColour: AQUA
  chat-display: full
  max-level: 200
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 1
  Quests:
    '1':
      Name: Catcher
      Objectives:
      - Fish;cod;2
      - Fish;salmon;2
      - Fish;tropical_fish;2
      RewardCommands:
      - eco give [playerName] 100
      - msg [playerName] Completed quest!
      RewardDesc:
      - Catch fish and get money
      - Get 100 for this!
  Gui:
    Item: fishing_rod
  Fish:
    cod:
      income: 15.0
      points: 15.0
      experience: 15.0
    salmon:
      income: 20.0
      points: 20.0
      experience: 25.0
    tropical_fish:
      income: 25.0
      points: 25.0
      experience: 25.0
    pufferfish:
      income: 25.0
      points: 25.0
      experience: 25.0
  Kill:
    cod:
      income: 15.0
      points: 15.0
      experience: 15.0
    salmon:
      income: 20.0
      points: 20.0
      experience: 25.0
    tropical_fish:
      income: 25.0
      points: 25.0
      experience: 25.0
    pufferfish:
      income: 25.0
      points: 25.0
      experience: 25.0
    dolphin:
      income: 30.0
      points: 30.0
      experience: 30.0
```
One missing and 2 extra spaces for salmon section
