### ISSUE TITLE
Slimes from spawners don't split with jobs loaded.

### ISSUE THREAD

**Issue by Geekmakes** [Zrips/Jobs#1233]
This is a odd one, It seems slimes that spawn from a spawner will not split up like a natural spawn would.

I've tested it on paper, and purpur with only jobs, vault and the new lib plugin.
All having fresh default configs.

After removing job's slimes from spawners split like normal.

Thanks!
---

**Jobs version:**  5.0.0.3

**Server Type:**  Purpur version git-Purpur-1271 (MC: 1.17.1)

**Comment by Zrips** [comment]
Check your config file
```
  Spawner:
    # Prevent slime splitting when they are from spawner
    # Protects against exploiting as new splitted slimes is treated as naturally spawned and not from spawner
    PreventSlimeSplit: true
    # Prevent magmacube splitting when they are from spawner
    PreventMagmaCubeSplit: true
```
