### ISSUE TITLE
Generator bypass for exploit protection doesn't work

### ISSUE THREAD

**Issue by LadyUnicornEJG** [Zrips/Jobs#1249]
When PlaceAndBreak block protection is enabled, the miner job stops working after a few minutes at some/more ore-heavy generators. This happens even with IgnoreOreGenerators set to true.

---
**CONFIG SECTION:**
```
  General:
    PlaceAndBreak:
      # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
      # Modify restrictedBlocks.yml for blocks you want to protect
      Enabled: true
      # Enabling this we will ignore blocks generated in ore generators, liko stone, coublestone and obsidian. You can still use timer on player placed obsidian block
      IgnoreOreGenerators: true
      # For how long in days to keep block protection data in data base
      # This will clean block data which ones have -1 as cooldown value
      # Data base cleanup will be performed on each server startup
      # This cant be more then 14 days
      KeepDataFor: 5
      # All blocks will be protected X sec after player places it on ground.
      GlobalBlockTimer:
        Use: true
        Timer: 60
      # Enable silk touch protection.
      # With this enabled players wont get paid for broken blocks from restrictedblocks list with silk touch tool.
      SilkTouchProtection: false
```

---

**Jobs version:** 5.0.0.6

**Server Type (Spigot/Paper/etc):** Spigot

**Server Version (using `/ver`):** 3211-Spigot-18c71bf-2cdc6b1 (MC:1.17.1) (API version 1.17.1-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** BentoBox, MagicCobbleGenerator
