### ISSUE TITLE
Bossbar issue

### ISSUE THREAD

**Issue by WarnDangerous** [Zrips/Jobs#1251]
***Detailed description of the issue:**
If you got multiple jobs bossbar, only the first one will get the correct aspects, the other will get a different one
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
BossBar:
  # Enables BossBar feature
  # Works only from 1.9 mc version
  Enabled: true
  Messages:
    # When this set to true player will see Bossbar messages by default
    EnabledByDefault: true
  # If enabled boss bar will update after each action
  # If disabled, BossBar will update only on each payment. This can save some server resources
  ShowOnEachAction: true
  # Defines in how many parts bossbar will be split visually
  # Valid options: 1, 6, 10, 12, 20
  SegmentCount: 1
  # How long in sec to show BossBar for player
  # If you have disabled ShowOnEachAction, then keep this number higher than payment interval for better experience
  Timer: 6
```

---

**Jobs version: 5.0.0.6** 

**Server Type (Spigot/Paper/etc): Airplane-Purpur 1.16.5** 

**Server Version (using `/ver`):This server is running Airplane-Purpur version git-Airplane-5 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version
Previous version: git-Airplane-4 (MC: 1.16.5)** 

https://cdn.discordapp.com/attachments/868163945087791195/873921611424755722/2021-08-08_15.31.08.png
