### ISSUE TITLE
Collect glow berries

### ISSUE THREAD

**Issue by Gorderok** [Zrips/Jobs#1252]
collecting glow berries does not work, how should it be put?

I tried :

Collect:
    cave_vines:
      income: 1
      experience: 1
Collect:
    cave_vines-1:
      income: 1
      experience: 1
Collect:
    cave_vines_plant:
      income: 1
      experience: 1
Collect:
    glow_berries:
      income: 1
      experience: 1

**Jobs version: 5.0.0.6

**Server Type (Spigot/Paper/etc): PaperSpigot 1.17.1 #166

**Comment by Zrips** [comment]
You need to provide stage of it, so like
```yaml
  Collect:
    sweet_berry_bush-3:
      income: 0.5
      points: 0.5
      experience: 0.5
```
