### ISSUE TITLE
Dynamic Payment cannot calculate Penalty, only Bonus

### ISSUE THREAD

**Issue by chuckouffin** [Zrips/Jobs#1266]
***Detailed description of the issue:**
I have tried the provided formulas as well as many different other ones as I can think of, including going as for as to simply use a static amount for the formula (i.e 0.5. -50, etc), but nothing gives a penalty amount. Sometimes it will show a "Penalty: 0%" but it is never more than 0%, while the bonus is working perfectly. Is there an issue with the default values below or is this a calculation error on the plugin-side?
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  DynamicPayment:
    # Do you want to use dynamic payment dependent on how many players already working for jobs?
    # This can help automatically lift up payments for not so popular jobs and lower for most popular ones
    use: true
    # totalworkers: The total number of players on the server who have jobs
    # totaljobs: The number of jobs that are enabled
    # jobstotalplayers: The number of people in that particular job
    # Exponential equation: totalworkers / totaljobs / jobstotalplayers - 1
    # Linear equation: ((totalworkers / totaljobs) - jobstotalplayers)/10.0
    equation: totalworkers / totaljobs / jobstotalplayers - 1
    MaxPenalty: 50.0
    MaxBonus: 300.0
```

---

**Jobs version:** 
5.0.0.6
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
1.17.1
