### ISSUE TITLE
RestrictedBlock piston bypass

### ISSUE THREAD

**Issue by Agaloth** [Zrips/Jobs#1273]
***Detailed description of the issue:**

You can basically bypass the restrictedblock with a piston and gain money by auto farming.

https://www.youtube.com/watch?v=hNTfEwp7C_8

```
  General:
    PlaceAndBreak:
      # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
      # Modify restrictedBlocks.yml for blocks you want to protect
      Enabled: true
      # Enabling this we will ignore blocks generated in ore generators, liko stone, coublestone and obsidian. You can still use timer on player placed obsidian block
      IgnoreOreGenerators: true
      # For how long in days to keep block protection data in data base
      # This will clean block data which ones have -1 as cooldown value
      # Data base cleanup will be performed on each server startup
      # This cant be more then 14 days
      KeepDataFor: 14
      # All blocks will be protected X sec after player places it on ground.
      GlobalBlockTimer:
        Use: true
        Timer: 3
      # Enable silk touch protection.
      # With this enabled players wont get paid for broken blocks from restrictedblocks list with silk touch tool.
      SilkTouchProtection: false
```

---

**Jobs version:** 5.0.0.6

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** paper 788
