### ISSUE TITLE
NOT working - restrictedBlocks 

### ISSUE THREAD

**Issue by ehetteNandaYo** [Zrips/Jobs#1277]
***Detailed description of the issue:**

The restrictedBlocks are being reset on server restart even if I set it for days and i have STONE: -1 for example
seems like not all the blocks are being added to the database on restart, I checked and just a few are added, sometimes none at all

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

Using MySQL

```
  General:
    PlaceAndBreak:
      # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
      # Modify restrictedBlocks.yml for blocks you want to protect
      Enabled: true
      # Enabling this we will ignore blocks generated in ore generators, liko stone, coublestone and obsidian. You can still use timer on player placed obsidian block
      IgnoreOreGenerators: true
      # For how long in days to keep block protection data in data base
      # This will clean block data which ones have -1 as cooldown value
      # Data base cleanup will be performed on each server startup
      # This cant be more then 14 days
      KeepDataFor: 14
      # All blocks will be protected X sec after player places it on ground.
      GlobalBlockTimer:
        Use: true
        Timer: 10
      # Enable silk touch protection.
      # With this enabled players wont get paid for broken blocks from restrictedblocks list with silk touch tool.
      SilkTouchProtection: true
```

---

**Jobs version:**  5.0.0.8

**Server Type (Spigot/Paper/etc):**  Paper

**Server Version (using `/ver`):** Paper 266

**Relevant plugins (Delete if this isn't needed):**

CMILib 1.0.3.9
