### ISSUE TITLE
Shearing sheep is not rewarded

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#1297]
***Detailed description of the issue:**
Shearing sheep is not rewarded with money or EXP.
I have tried the following setups:
```
  Shear:
    wool-all:
      income: 4.38
      experience: 4.38
```
```
  Shear:
    white_wool:
      income: 4.38
      experience: 4.38
```

**Jobs version:** 
Jobs version 5.0.0.8
I have also unsuccessfully tried Jobs version 4.17.1 running 1.16.5.
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
git-Paper-327 (MC: 1.17.1)

**Comment by Zrips** [comment]
You need to provide color of sheep and not wool type, so for example
```
  Shear:
    Red:
      income: 4.0
      points: 4.0
      experience: 5.0
    Orange:
      income: 4.0
      points: 4.0
      experience: 5.0
```
