### ISSUE TITLE
blockOwnerShip doesn't respect disabled worlds?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/Jobs#1299]
I noticed in blockOwnerShip.yml I have entries for /spawn/ and other worlds but I remember setting up a whitelist, excluding spawn and those other worlds. 

Is it not respecting disabled worlds?

```yaml
  DisabledWorlds:
    # By setting this to true, Jobs plugin will be disabled in given worlds
    # Only commands can be performed from disabled worlds with jobs.disabledworld.commands permission node
    Use: true
    # If true, will changes the list behavior, so if a world is added to list
    # the payments will only works in the given worlds.
    UseAsWhiteList: true
    List:
    - general
    - mine
    - end
    - nether
```

```
Brewing:
  9aa0fcbe-3263-493d-ad86-1441ed794cdd: spawn:38:72:114
  530a04fd-eb63-436c-9b82-da9414197b12: mine:-1387:33:1860;mine:1122:45:-957
  0af03efd-8134-4826-a23d-ad9b2576b399: spawn:-3:64:112
  413b4348-404a-4bdc-93a6-b382d4d9e064: spawn:22:61:158
  0e3a512d-32fe-4bc6-90e3-01d09ff4bc25: general:15457:69:-14919;general:15464:71:-14926;general:15457:69:-14920;general:15464:69:-14926;general:15457:69:-14921;general:15457:71:-14921;general:15457:71:-14920;general:15457:70:-14921;general:15463:70:-14926;general:15457:70:-14920;general:15462:71:-14926;general:15457:71:-14919;general:15461:70:-14922;general:15464:70:-14926;general:15457:70:-14919;general:15465:70:-14925;general:15465:70:-14926

```
