### ISSUE TITLE
Console is being spammed with SQL errors.  I have not changed anything in the config.

### ISSUE THREAD

**Issue by Silent-Program** [Zrips/Jobs#1330]
***Detailed description of the issue:**
Console is being spammed with SQL errors.  I have not changed anything in the config.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
03.12 00:22:54 [Server] INFO Shadowguyminer has left.
03.12 00:30:28 [Server]  org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
03.12 00:30:28 [Server]  at org.sqlite.core.DB.newSQLException(DB.java:1012)
03.12 00:30:28 [Server]  at org.sqlite.core.DB.newSQLException(DB.java:1024)
03.12 00:30:28 [Server]  at org.sqlite.core.DB.throwex(DB.java:989)
03.12 00:30:28 [Server]  at org.sqlite.core.DB.executeBatch(DB.java:814)
03.12 00:30:28 [Server]  at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
03.12 00:30:28 [Server]  at com.gamingmesh.jobs.dao.JobsDAO.saveBlockProtection(JobsDAO.java:2339)
03.12 00:30:28 [Server]  at com.gamingmesh.jobs.config.BlockProtectionManager.saveCache(BlockProtectionManager.java:109)
03.12 00:30:28 [Server]  at com.gamingmesh.jobs.PlayerManager.saveAll(PlayerManager.java:341)
03.12 00:30:28 [Server]  at com.gamingmesh.jobs.tasks.DatabaseSaveThread.run(DatabaseSaveThread.java:46)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
storage:
  # storage method, can be MySQL or sqlite
  method: sqlite
# Requires Mysql
mysql:
  username: root
  password: ''
  hostname: localhost:3306
  database: minecraft
  table-prefix: jobs_
  verify-server-certificate: false
  use-ssl: false
  auto-reconnect: true
  characterEncoding: utf8
  encoding: UTF-8
# How often in minutes you want it to save. This must be a non-zero number
save-period: 10
```

---

**Jobs version: 5.0.1.0** 

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): This server is running Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**
