### ISSUE TITLE
MySQL tables are not created

### ISSUE THREAD

**Issue by samfces** [Zrips/Jobs#1348]
Hello! I recently started using Jobs inside my server and, after a new installation of the plugin, it does not create the tables in MySQL correctly.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
https://pastebin.com/S8NiHmp8
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
mysql:
  username: root
  password: password
  hostname: host
  database: Survival4_Jobs
  table-prefix: jobs_
  verify-server-certificate: false
  use-ssl: false
  auto-reconnect: true
  characterEncoding: utf8
  encoding: UTF-8
```

---

**Jobs version:** 
5.0.1.0

**Server Type (Spigot/Paper/etc):** 
Purpur (Paper folk)

**Server Version (using `/ver`):** 
 Purpur version git-Purpur-"08dd6c7" (MC: 1.17.1)
