### ISSUE TITLE
Diorite not working as Quest Objective

### ISSUE THREAD

**Issue by JinnFletch** [Zrips/Jobs#1361]
***Detailed description of the issue:**
Attempting to make `diorite` a quest objective.  If I make it `stone`, stone works.  But `diorite` does not.

The quest appears in `/jobs quests`, it says I must "Break Diorite", but breaking Diorite is not counting toward the objective.

The quest objectives in game even say "Break Diorite" with a capital D, leading me to believe the item is understood, since the command is with a lowercase diorite.

---

**CONFIG SECTION:**
```
  Quests:
    '1':
      Name: "Learn about Diorite"
      RewardDesc:
      - Study Diorite
      Objectives:
      - Break;diorite;2
      Chance: 100
      fromLevel: 1
      toLevel: 1
```

---

**Jobs version:** 5.0.1.0 and 5.0.1.1

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 148  (1.18.1)
