### ISSUE TITLE
Built-in JobsReborn ranks & permissions

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [Zrips/Jobs#1373]
**Description of new idea or improvement on existing one**

We should be able to arbitrarily define various ranks within professions (e.g. "Novice" is Levels 1-20) that allow us to assign them permissions.

The premise is similar to TownyAdvanced where you can assign permission nodes to ranks.
The difference is that Jobs would work on a level basis (based on what we configure) and allow players to unlock new crafting recipes or other perks as they level up.

**Detailed information what should do**

Reference: https://github.com/TownyAdvanced/Towny/wiki/Default-Townyperms.yml

As you can see in this reference, TownyAdvanced allows you to add or remove permissions from town ranks. Jobs and Towny are of course different plugins with different goals so the actual config would look a little different.

Here's my example of what a Jobs ranks config could look like using "jobRanks.yml":
```
ranks:
  settings: # QoL settings
    # inheritPermissions is optional to this feature request. If it comes down to a default system, I personally prefer making it so you need to define permissions for each rank. 
    inheritPermissions: false # Do higher level ranks inherit lower rank permissions? True = take into consideration all lower permissions. False = only return player's current rank permissions.
  Brewer:
    Novice:
      Level: 1-10 # Supports level range
      Permission: [] # Requires a plugin that can handle permissions, such as LuckPerms.
    Apprentice:
      Level: 11-20
      Permission:
      - jobs.boost.brewer.exp.0.05
    Initiate:
      Level: 21-40
      Permission:
      - jobs.boost.brewer.exp.0.075
    Journeyman:
      Level: 41-60
      Permission:
      - jobs.boost.brewer.exp.0.1
      - new.recipe.permission
    Adept:
      Level: 61-80
      Permission:
      - jobs.boost.brewer.exp.0.125
    Master:
      Level: 81-99
      Permission:
      - jobs.boost.brewer.exp.0.15
    Grandmaster:
      Level: 100 # Also supports single levels
      Permission:
      - jobs.boost.brewer.money.0.25
      - -new.recipe.permission # Supports denied permissions. Not sure how this works in LuckPerms with true/false settings.
      - anothernew.recipe.permission
```
