### ISSUE TITLE
Specific Tools for Jobs 

### ISSUE THREAD

**Issue by Bigimus1021** [Zrips/Jobs#1378]
So my idea would be to make it so you can specify which tool is needed to break a certain block or even kill certain mobs. So for example, I could require people to break melon blocks with a wooden hoe. 

You could take this even further, by giving different rewards depending on the tool used to kill/break the block. So for example, if a person breaks a block of stone with a wooden pickaxe, they'll get 5 money/points/exp, but if they break a block of stone with a diamond pickaxe, they'll get 15 money/points/exp. 

An example of the job config (this example is from the default digger.yml, with the proposed additions):
```
  Break:
    red_sand:
      tool: "diamond_pickaxe"
      income: 1
      points: 1
      experience: 1
```

Another config example (this would be an addition to the generalConfig.yml):
``` 
  ToolMulti:
    wood:
      MONEY: 0.0
      EXP: 0.0
      POINTS: 0.0
   iron:
      MONEY: 0.0
      EXP: 0.0
      POINTS: 0.0
   gold:
      MONEY: 0.0
      EXP: 0.0
      POINTS: 0.0
   diamond:
      MONEY: 0.0
      EXP: 0.0
      POINTS: 0.0
   netherite:
      MONEY: 0.0
      EXP: 0.0
      POINTS: 0.0
```
I would add this in the Economy section of the config nearby the generalMulti.

I think this change would allow for further customization within jobs and would make the plugin much better than it already is. I was thinking of adding this myself as the plugin is open-source, but I think this feature would be beneficial to all of the users of the plugin and not just myself.
