### ISSUE TITLE
Scheduling and permission support for individual quests and work tasks

### ISSUE THREAD

**Issue by Donkk0** [Zrips/Jobs#1392]
**Scheduling and permission support for individual quests and work tasks**

Add support to schedule when a specific quest can be done, or payout from a job can be gotten, based on real-world date and time. This would allow seasonal quests, nighttime and daytime exclusive quests, weekend quests, etc. The example provided below is a simple Halloween quest.

```
  Quests:
    halloween-quest:
      Name: "Halloween quest"
      Objectives:
      - Place;jack_o_lantern;10
      Months:
      # Name or number of month
      - October
      - 10
      Days:
      # Name of a weekday, list of weekdays, day of the month, list of days of the month, or "all"
      - Monday
      - 31
      From: ‘18:00:00’
      Until: ‘23:59:59’
      RewardCommands:
      - "eco give [playerName] 500"
      - "msg You finished the Halloween quest, [playerName]. Go scare some kids and steal their candy!"
      RewardDesc:
      - "Place 10 Jack o'Lanterns"
      - "This is Halloween. Everybody make a scene!"
      Chance: 50
```

The same values could also be added to payouts for specific actions. A simple Halloween-related example is provided below.

```
  Place:
    jack_o_lantern:
      income: 50.0
      points: 40.0
      experience: 50.0
      months:
        - 10
      days: 
        - 31
      from: '18:00:00'
      until: '23:59:00'
```

I also suggest adding permissions checks for both, meaning you need to have a specific permission to get paid for the action or to get offered the quest. Examples for both payouts and quests provided below.

```
  Place:
    jack_o_lantern:
      permission: halloween.job
```

```
  Quests:
    halloween-quest:
      Name: "Halloween quest"
      permission: halloween.quest
```

**Comment by Donkk0** [comment]
Another usecase:

I have a few kids on my server and I would like to discourage them from playing late at night without actually kicking anyone. With these options I could enact a "curfew" for Jobs, where they would only get paid during daytime, while the adult accos could still get paid for jobs throughout the day. Config example below:

```
#current config, everyone gets paid all day long, even if they're a minor any play at 2 in the night on a school night

  Place:
    jukebox:
      income: 1.5
      points: 1.5
      experience: 3

# config using permission and time restrictions allowing everyone to get paid at night, but only accounts with adult.worker permission set to be paid at night

  Place:
    jukebox:
      income: 1.5
      points: 1.5
      experience: 3
      permission:
      months:
        - all
      days: 
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
      from: '08:00:00'
      until: '22:00:00'
    jukebox:
      income: 1.5
      points: 1.5
      experience: 3
      permission: adult.worker
      months:
        - all
      days: 
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
      from: '22:00:00'
      until: '08:00:00'
```

Could go further and only have these active during the months when school is on, but not during summer months or around Christmas, etc.
