### ISSUE TITLE
Confliction issue with Jobs permissions and TreeAssist plugin

### ISSUE THREAD

**Issue by JonneSaloranta** [Zrips/Jobs#1393]
## Issue

I'm using Multi-Verse to make a creative world and I've disabled rewards in that world, but I'm still getting rewards while using treefeller plugin. I've tried setting jobs.world.creative and jobs.use to false, deop'd myself, set permission context to world=creative in LuckPerms.

I've come to a conclusion that the problem is either in the Jobs or TreeAssist plugin, so maybe somehow woodcutter job sees events or something happening while TreeAssist cuts the tree.

Other similar bug report #1240 

### Issue demonstration
![72078758715dae90030efaf66f19baa6](https://user-images.githubusercontent.com/72470168/153226555-c1bbaf2a-95d2-4122-aa4a-b5cc5b62f09e.gif)

### Worlds
![image](https://user-images.githubusercontent.com/72470168/153227065-1381af1a-6c8a-49e7-99c9-821ce5a92aff.png)

### Permissions
Tried setting everything to false, but didn't seem to work

![image](https://user-images.githubusercontent.com/72470168/153228445-2b13f333-65e3-4b4e-ab5b-19eee56610e0.png)

## Config

**Config is default except this section (note: world is correctly named)**
```
 DisabledWorlds:
    # By setting this to true, Jobs plugin will be disabled in given worlds
    # Only commands can be performed from disabled worlds with jobs.disabledworld.commands permission node
    Use: true
    # If true, will changes the list behavior, so if a world is added to list
    # the payments will only works in the given worlds.
    UseAsWhiteList: false
    List:
    - creative
```

## Config

**Jobs version:** 
```
Jobs5.0.1.3
CMILib1.1.1.0
```

**Server Type (Spigot/Paper/etc):** 
```
paper-1.18.1-185 MC:1.18.1
```

**Relevant plugins**
```
Multiverse-Core-4.3.1
LuckPerms-Bukkit-5.3.98
TreeAssist v7.3.10
```
