### ISSUE TITLE
Glow item frames don't work

### ISSUE THREAD

**Issue by Donkk0** [Zrips/Jobs#1396]
***Detailed description of the issue:**

Glow item frames are broken.

When creating a job with a Place type payout for glow_item_frame and reloading Jobs, it spits out a warning:

[15:42:04 WARN]: [Jobs] Job Decorator has an invalid Place type property: GLOW_ITEM_FRAME (glow_item_frame)! Material must be a block! Use "/jobs blockinfo" on a target block.

When using "/jobs blockinfo" while looking at a placed glow item frame, the command outputs information on the block behind the glow item frame. Image attached.
![kuva](https://user-images.githubusercontent.com/99261895/153424156-4f43d215-1916-4f90-9e4d-073387a264e3.png)

After this, I tried creating a payout for item_frame-glow: on the off chance it would work like tipped arrows. This loads and doesn't produce any warnings, but it also does not work in-game. No money, exp or points are paid for the user when they place glow item frames.

---

**ERROR**
```
[15:42:04 WARN]: [Jobs] Job Decorator has an invalid Place type property: GLOW_ITEM_FRAME (glow_item_frame)! Material must be a block! Use "/jobs blockinfo" on a target block
```

**CONFIG:**
```
  Place:
    glow_item_frame:
      income: 1.5
      points: 1.5
      experience: 3
    item_frame-glow:
      income: 1.5
      points: 1.5
      experience: 3
```
---

**Jobs version:** 
5.0.1.3 

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
git-paper-160 (mc: 1.18.1)
