### ISSUE TITLE
Money limit timer resets every server restart.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#141]
Jobs v4.1.3 compiled as of commit https://github.com/Zrips/Jobs/commit/262c250cbe2950ba160021b4ccc75db8e88a691b

MySQL database.

Getting reports from players that the time limit for how much money someone can earn in a day seems to be resetting every server restart. The timer does not continue where it left off. Every server restart, players are able to earn money again.

```
  Limit:
    # Money gain limit
    # With this enabled, players will be limited how much they can make in defined time
    # Time in seconds: 60 = 1min, 3600 = 1 hour, 86400 = 24 hours
    Money:
      Use: true
      # Do you want to stop money gain when exp limit reached?
      StopWithExp: false
      # Do you want to stop money gain when point limit reached?
      StopWithPoint: false
      # Equation to calculate max limit. Option to use totallevel to include players total amount levels of current jobs
      # You can always use simple number to set money limit
      # Default equation is: 500+500*(totallevel/100), this will add 1% from 500 for each level player have
      # So player with 2 jobs with level 15 and 22 will have 685 limit
      MoneyLimit: 250+100*(totallevel/300)
      # Time in seconds: 60 = 1min, 3600 = 1 hour, 86400 = 24 hours
      TimeLimit: 86400
      # Delay between announcements about reached money limit
      # Keep this from 30 to 5 min (300), as players can get annoyed of constant message displaying
      AnnouncmentDelay: 300
```

Also would it be possible to have a new config option to reset the limit every new calendar day rather than a forced limit with a timer per player?
