### ISSUE TITLE
Collect not Working o:

### ISSUE THREAD

**Issue by luchs888** [Zrips/Jobs#1427]
**Detailed description of the issue:**

The "Collect" method, which is also in the example config,
is not recognized by the plugin and does not work.
We copied the part from the example config for test purposes and changed the price, it didn't work.

#####################################
##RELEVANT CONFIG SECTION##
#####################################

  Collect:
    sweet_berries-2:
      income: 0.2
      points: 0.2
      experience: 0.2
    sweet_berries-3:
      income: 0.5
      points: 0.5
      experience: 0.5

---

**Jobs version:** 
- 5.0.1.2

**Server Type:** 
- Paper (Waterfall)

**Server Version:** 
- 1.18.1

**Comment by SpeedManT** [comment]
Hi, we are using collect on our server and it works fine. I think the problem is sweet-berries-3. Thats our config:

```
  Collect:
    bone_meal:
      income: x.xx
      experience: x.xx
    glow_berries:
      income: x.xx
      experience: x.xx
    honeycomb:
      income: x.xx
      experience: x.xx
    honey_bottle:
      income: x.xx
      experience: x.xx
    sweet_berries:
      income: x.xx
      experience: x.xx
```
