### ISSUE TITLE
Fishing mcMMO Treasure Pays 2X The Set Value

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Zrips/Jobs#1438]
***Detailed description of the issue:**
When you fish an mcMMO Treasure item, it pays twice as much as the value you have configured it to pay.

For example, I have set fishing up Diamond Boots to these values.
```
    DIAMOND_BOOTS:
      income: 110.0
      points: 110.0
      experience: 110.0
```
But fishing them up yields $220 and 220xp

---

**Jobs version:** 5.0.2.1

**Server Type (Spigot/Paper/etc):** Purpur-1612

**Server Version (using `/ver`):** MC 1.18.2

**Relevant plugins (Delete if this isn't needed):** mcMMO 2.1.211
