### ISSUE TITLE
Enchanter job doesnt get paid when using anvils

### ISSUE THREAD

**Issue by UnitedCraft** [Zrips/Jobs#1456]
***Detailed description of the issue:**

I would like the enchanting of items in the anvils to be paid as enchanter

```
 Gui:
    Item: ANVIL
  Enchant:
    wood_sword:
      income: 1.5
      points: 1.5
      experience: 3.0
  Gui:
    Item: enchanting_table
  Enchant:
    wood_sword:
      income: 1.5
      points: 1.5
      experience: 3.0

```
[latest log]
(https://pastebin.com/N3TSca5q)
```

---

**Jobs version:** 
latest
**Server Type (Spigot/Paper/etc):** 
paper latest 366
**Server Version (using `/ver`):** 
1.18.2
**Relevant plugins (Delete if this isn't needed):**
