### ISSUE TITLE
Schedules bug

### ISSUE THREAD

**Issue by D3dWiz** [Zrips/Jobs#1460]
***Detailed description of the issue:**
I wanted to create a schedule for daily bonuses for different jobs, but nothing really happens.
When I try to enable the schedule it says it's already enabled, but I don't get any message nor I see any job boosted.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Boost:
  Monday:
    Enabled: true
    Exp: 1.25
    Money: 1.25
    From: 00:00:01
    Until: 23:59:59
    Days:
    - Monday
    Jobs:
    - Farmer
    BroadcastOnStart: true
    MessageOnStart:
    - '&6╔═════════════════════════════'
    - '&6║ &eПонеделничен бонус!'
    - '&6║ &eПрофесията &6Фермер &eполучава'
    - '&6║ &61.25X &eповече XP и пари!'
    - '&6╚═════════════════════════════'
    BroadcastOnStop: false
    MessageOnStop: []
    BroadcastInterval: 15
    BroadcastMessage:
    - '&6╔═════════════════════════════'
    - '&6║ &eАктивни бонуси на професии:'
    - '&6║ &e1.25x бонус на професията &6Фермер'
    - '&6║ &eдо края на понеделника'
    - '&6╚═════════════════════════════'
```

---

**Jobs version:**  5.0.3.0

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** git-Purpur-1659 (MC: 1.19)
