### ISSUE TITLE
Grouping multiple items / blocks into one section

### ISSUE THREAD

**Issue by Tencryn** [Zrips/Jobs#1471]
**Description of new idea or improvement on existing one**
Specifying a section for many different blocks that have the same options is inconvenient and makes the configuration very large. Right now, if you wanted to add all the varieties of granite to a job, one would agree that the following is very cumbersome. 
```yaml
granite:
    income: 0
    points: 0
    experience: 0
granite_slab:
    income: 0
    points: 0
    experience: 0
granite_stair:
    income: 0
    points: 0
    experience: 0
polished_granite:
    income: 0
    points: 0
    experience: 0
polished_granite_slab:
    income: 0
    points: 0
    experience: 0
polished_granite_stair:
    income: 0
    points: 0
    experience: 0
```

Instead, what would be better, is grouping them together. Take these couple of examples:
```yaml
"cobblestone_[slab,stairs,wall]":
    income: 0
    points: 0
    experience: 0
"[polished_]granite[_slab,stair]":
    income: 0
    points: 0
    experience: 0
```

We can also group sections together by using placeholders that function similar to wildcards. Take this example:
```yaml
"%color%_wool":
    income: 0
    points: 0
    experience: 0
"%wood%_planks":
    income: 0
    points: 0
    experience: 0
```

It could also be possible for these placeholders to be defined in the configuration itself such as:
```yaml
placeholders:
    wood: [oak,dark_oak,birch,acacia,mangrove,crimson,warped]
```
However, I would consider this to be less of importance unless there was a real use case where this would be useful.

**Detailed information what should do**
If we take the key shown in the above example `[polished_]granite[_slab,stair]`, we can trust that the section would apply for `granite`, `granite_slab`, `granite_stair`, `polished_granite`, `polished_granite_slab`, and `polished_granite_stair`, drastically cutting down on the size of the configuration and making it more convenient to all the different variations of items.

As for the `%color%_wool` key, that would correspond to `white_wool`, `red_wool`, `green_wool` and so on and so forth. `%wood%` would correspond to your different types of wood.
