### ISSUE TITLE
ExploitProtection not preventing PlaceAndBreak from +2 players

### ISSUE THREAD

**Issue by 4L0N50asd** [Zrips/Jobs#1488]
***Detailed description of the issue:**
Jobs has a section in config to prevent players from getting money by placing and breaking the same block at the same location, but there's another way to do it. You need someone (player A) to place those blocks and you (player B) just mine them. By this way Jobs is not preventing the player B from getting money from no-natural blocks.

Of course you can set in the config that if you place blocks you will lose money, but playerA can leave that job so he won't lose money when placing blocks.

Example of this:
PlayerB has the miner job and PlayerA left the miner job. PlayerA places diamond ores, gold ores, etc (won't lose money) and Player B mine them and can continue doing this forever.

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ExploitProtections:
  General:
    PlaceAndBreak:
      # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
      # Modify restrictedBlocks.yml for blocks you want to protect
      Enabled: true
      # Enabling this we will ignore blocks generated in ore generators, liko stone, coublestone and obsidian. You can still use timer on player placed obsidian block
      IgnoreOreGenerators: true
      # For how long in days to keep block protection data in data base
      # This will clean block data which ones have -1 as cooldown value
      # Data base cleanup will be performed on each server startup
      # This cant be more then 14 days
      KeepDataFor: 14
```
---

**Jobs version:** 
5.1.0.0

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
