### ISSUE TITLE
Execute Commands when player joins/leave a job

### ISSUE THREAD

**Issue by th3lucas** [Zrips/Jobs#1492]
**Description of new idea or improvement on existing one**

I would like a feature where a command is executed when a player joins or leaves a job (or uses leaveall).
You could assign a player a LuckPerms Group this way or give him special items usings kits or something.

**Detailed information what should do**

Add a new section in the job file.
I think "JoinCommand" and "LeaveCommand" could work really well.
Admin could add multiple commands that get executed when a player joins or leave a job.
Should work with the /jobs leave JOB command and the /jobs browse gui.
If a user uses /jobs leaveall ALL LeaveCommand from all his jobs should execute.

i tried using cmi aliaseditor but it does not work for this (especially in the jobs browse gui).
A native solution would be amazing. :)

**Example:**
```
Woodcutter:
  fullname: Woodcutter
  shortname: W
  FullDescription:
  - "Earns money felling and planting trees"
  ChatColour: GREEN
  chat-display: full
  JoinCommand:
  - "lp user [playerName] parent add Woodcutter"
  - "cmi kit Woodcutter [playerName]"
  - "msg [playerName] A great day to visit the woods!"
  LeaveCommand:
  - "lp user [playerName] parent remove Woodcutter"
  - "cmi kit Woodcutter [playerName]"
  - "msg [playerName] See you soon!"
  max-level: 200
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 1
  Quests:
    '1': .....
```
