### ISSUE TITLE
Automatically remove job from people after being offline for specified amount of time

### ISSUE THREAD

**Issue by CSmither** [Zrips/Jobs#1505]
**Description of new idea or improvement on existing one**
Automatically remove job from person after being offline for specified amount of time. For example automatically fire someone from a being a miner after being offline for two weeks. 
This would allow us to use the `slots` config limit in the job. Currently if we use `slots` for a job it eventually gets filled by AFK players and new people can't join even though there are no active people with that job.

**Detailed information what should do**
This should be an hourly asynchronous check, with the `offline_fire_days` specified in whole days. Once a player has been offline for that many days they automatically leave the job.

Can use the [OfflinePlayer.getLastPlayed()](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/OfflinePlayer.html#getLastPlayed()) method for checking last seen time

**Example Config**

```yaml
exampleJob:
  ...
  slots: 5  # Maximum 5 people allowed in this job
  offline_fire_days: 7  # Automatically leave job if offline for 7 whole days
  ...
```

**Other considerations**
Should this count as a job leave and so cause you to lose job xp/levels as configured for that job?
