### ISSUE TITLE
TRANSLATION OF TOOL TO ENCHANT

### ISSUE THREAD

**Issue by nolberh2** [Zrips/Jobs#1523]
***Detailed description of the issue:**

In the words folder are the translations for: "Itemlist" "Entitylist" "EnchantList" "PottionEffects" "Color" "MythicEntityList". 

I translated everything to spanish and everything works correctly except for one thing and that is specifying a tool and it does not identify the item in "Itemlist" I have set: IRON_SWORD: Iron Sword and it identifies "IRON_SWORD" in the "Objectives :" for enchantment (ex: - Enchant;iron_sword;1) but this does not happen with other types of objectives. 

(Since I started using the plugin this has been happening)
```
(https://imgur.com/a/JM2WqcJ)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
IRON_SWORD: Espada de hierro (Words_en)

    '32':
      Name: §fHerrero §8| §7Objetivo - Medio
      Objectives:
      - Enchant;iron_sword;1
      - Enchant;iron_helmet;1
      - Enchant;iron_chestplate;1
      - Enchant;iron_leggings;1
      - Enchant;iron_boots;1
      RewardCommands:
      - rawmsg [playerName] false <n>&2&l¡Mision completada! <n>&fBuen trabajo &e[playerName]
      - eco give [playerName] 3000
      - jobs:jobs exp [playerName] Herrero add 1250
      - rawmsg [playerName] false &7
      RewardDesc:
      - ' &7Recompensa: &6$3000'
      - ' &7Experiencia: &d🧪 1250'
      - ''
      - '&a&l► &aEncanta el siguiente armamento'
      - ''
      
 locale-language: en
```

---

**Jobs version:** 5.1.0.1 

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):**  1.19.2
