### ISSUE TITLE
No money from breeding cows and pigs with StackMob

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/Jobs#1546]
***Detailed description of the issue:**

Hey,

I use Jobs and StackMob. I have job integration turned on. I don't get money from breeding cows and pigs 🙁. Could you please check that?

I've been redirected here from StackMob Discord server pointing to this code here from Jobs: https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/hooks/stackMob/StackMobHandler.java

StackMob config: [https://pastebin.com/UtfLq1gy](https://pastebin.com/UtfLq1gy).

Jobs Farmer config:

```
    Cow:
      income: 4.0
      points: 4.0
      experience: 5.0
    Pig:
      income: 4.0
      points: 4.0
      experience: 5.0
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:** 5.1.0.1

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** Purpur-1835 (MC: 1.19.2)

**Relevant plugins (Delete if this isn't needed):**
StackMob 5.8.4
