### ISSUE TITLE
Sometimes Quests didn't reset

### ISSUE THREAD

**Issue by Replaycchi** [Zrips/Jobs#1550]
***Detailed description of the issue:**

Sometimes jobs quests didn't reset, it seems to be when a player finish the quest and he should have the same after the quest reset. So the quest appear already finished and i have to do /jobs resetquests to give some new quests. (They have 2 quests per day)

---

```
DailyQuests:
  # Defines time in 24hour format when we want to give out new daily quests
  # Any daily quests given before reset will be invalid and new ones will be given out
  ResetTime:
    Hour: 4
    Minute: 50
```

**Jobs version:** 
5.1.2.0

**Server Type (Spigot/Paper/etc):** 
Purpur

**Server Version (using `/ver`):** 
git-Purpur-1835 (MC: 1.19.2)*
