### ISSUE TITLE
Non-world generated blocks give money

### ISSUE THREAD

**Issue by JoncoHD** [Zrips/Jobs#1560]
Can u deactivate non-world generated Block from the Jobs Plugin.

For example as a miner you can mine a diamond ore with silktouch and you get the money for it, but if you place that back there and mine it, then there shouldn't be any more money because it's no longer a world generated block.

Is it a Bug or only Config Setting?
Or is it not avaible in ur Plugin to deactivate this?

**Comment by Zrips** [comment]
Check generalConfig file and enable this
```
  General:
    PlaceAndBreak:
      # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
      # Modify restrictedBlocks.yml for blocks you want to protect
      Enabled: true
```
after that you can check restrictedBlocks.yml file for any new blocks you would want to add or remove from the list. But this should be enabled by default and protection should be up and running already. Diamond ore is present already by default and has infinite timer set to it. Double check that placed diamond block is marked with black glass block when you use **/jobs bp** command. Closing for now as this should be up and running.
