### ISSUE TITLE
Issue with "ExploitProtections" not preventing a certain "exploit"

### ISSUE THREAD

**Issue by SirKillian** [Zrips/Jobs#1569]
**Detailed description of the issue:**
Exploit Protection in generalConfig.yml only protects from hoppers and not from droppers. This means players can shoot items from a dropper directly into the furnace and brewing stand container and they will still get paid for it.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ExploitProtections:
  Smelt:
    PreventHopperFillUps: true
  Brew:
    PreventBrewingStandFillUps: true
```

---

**Jobs version:** 
5.1.2.2

**Server Type (Spigot/Paper/etc):** 
Custom Pufferfish fork

**Server Version (using `/ver`):** 
1.19.3.
