### ISSUE TITLE
Deny Silk Touchers Profit

### ISSUE THREAD

**Issue by t347549** [Zrips/Jobs#1575]
Hello, this issue is for the Miner job. I currently have Jobs set up where I don't take any money for placing ores because my formula can't accommodate a negative baseincome value.

So this opens up a way for people to abuse ore income by silk touching them, placing them back, and doing so again repeatedly.

Is there an option to detect and completely ignore actions performed using Silk Touch. I asked the help channel and they said there isn't one

**Comment by mercurialmusic** [comment]
This is possible with the setting in the generalConfig.yml:
```
      # Enable silk touch protection.
      # With this enabled players wont get paid for broken blocks from restrictedblocks list with silk touch tool.
      SilkTouchProtection: true
```
Then just set the blocks you want in restrictedBlocks.yml.

You can also use the following section in the generalConfig.yml for similar results:
```
  General:
    PlaceAndBreak:
      # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
      # Modify restrictedBlocks.yml for blocks you want to protect
      Enabled: true
```
