### ISSUE TITLE
Wither Skeletons do not give job rewards

### ISSUE THREAD

**Issue by ArmonicPvP** [Zrips/Jobs#1578]
***Detailed description of the issue:**
When killing Wither Skeletons, they do not give job rewards, despite showing in the Jobs info command for the Hunter job.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
WITHER_SKELETON:
      income: 1.0
      points: 0.5
      experience: 5.5
```

---

**Jobs version:** 
5.1.2.2
**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-439
**Relevant plugins (Delete if this isn't needed):**
Plugins which link to Jobs or that it is linking with:

MythicMobs
Plan
Vault
EssentialsX
