### ISSUE TITLE
HideWithoutPermission in shopItems.yml does not work

### ISSUE THREAD

**Issue by GabrielChev** [Zrips/Jobs#1581]
Hello,

All items in jobs shop are visible even if the user does not have the permission set in "RequiredPermission:" and when HideWithoutPerimission is set to true.
However the permission works for authorize or not the user to buy the item.
I try with essentials permissions in a first time and after with luckperm.
There is an example of my shopItems.yml :
```
Items:
  ArbaleteSemiAuto:
    Price: 100000.0
    Icon:
        Id: crossbow
        Amount: 1
        Name: "&5&lArbalète semi-automatique"
        Lore:
        - "&7Brevetée par le Maître Artisan, cette"
        - "&7arbalète semi-automatique à cadance"
        - "&7très élevée est incassable. C'est"
        - "&7une vraie merveille de technologie."
        - "&9 Charge rapide V"
        - "&9 Perforation IV"
        - "&9 Incassable"
        - "&9Mains droite et gauche :"
        - "&9 Déplacement impossible"
    HideWithoutPermission: true
    HideIfThereIsNoEnoughPoints: false
    RequiredPermission:
      - jobs.item.arbaletesemiauto
    RequiredJobLevels:
      - Crafter-50
    PerformCommands:
    - "msg &eFélicitation pour l'achat de &5&lArbalète semi-automatique &e!!!"
    - "me [player] &ea acheté &5&lArbalète semi-automatique &eau Maître Artisan ! Félicitations !"
    - "minecraft:give [player] crossbow{Unbreakable:1,RepairCost:50,AttributeModifiers:[{AttributeName:\"generic.movement_speed\",Amount:-1,Slot:mainhand,Name:\"generic.movement_speed\",UUID:[I;-12297,8905,13358,-17810]},{AttributeName:\"generic.movement_speed\",Amount:-1,Slot:offhand,Name:\"generic.movement_speed\",UUID:[I;-12297,9005,13358,-18010]}],display:{Name:'[{\"text\":\"Arbalète semi-automatique\",\"italic\":false,\"bold\":true,\"color\":\"dark_purple\"}]',Lore:['[{\"text\":\"\",\"italic\":false}]','[{\"text\":\"Brevetée par le Maître Artisan cette\",\"italic\":false,\"color\":\"white\"}]','[{\"text\":\"arbalète semi-automatique à cadance\",\"italic\":false,\"color\":\"white\"}]','[{\"text\":\"très élevée est incassable. C\\'est\",\"italic\":false,\"color\":\"white\"}]','[{\"text\":\"une vraie merveille de technologie.\",\"italic\":false,\"color\":\"white\"}]']},Enchantments:[{id:piercing,lvl:4},{id:quick_charge,lvl:5}], JobsItemBoost:\"arbaletesemiauto\"} 1"
    - "lp user [player] permission set jobs.item.arbaletesemiauto false server=keriumsemirp"
    - "lp user [player] permission set jobs.item.arbaletesemiauto2 true server=keriumsemirp"
```
    
    Thanks a lot in advance for your time
    
    Gabriel
