### ISSUE TITLE
Cannot pickup Sweet Berries

### ISSUE THREAD

**Issue by daniel-skopek** [Zrips/Jobs#1615]
***Detailed description of the issue:**
When a player has a Miner job, he can't collect, for example, Sweet Berries.

---

**Jobs version:** 5.2.0.0

**Server Type (Spigot/Paper/etc):** Pufferfish

**Server Version (using `/ver`):** Pufferfish-72 (1.19.4)

**Comment by Zrips** [comment]
It should be defined as 
```
  Collect:
    sweet_berries-2:
      income: 0.2
      points: 0.2
      experience: 0.2
    sweet_berries-3:
      income: 0.5
      points: 0.5
      experience: 0.5
```
and it should be working as intended
