### ISSUE TITLE
[Enhancement] limitedItems Blacklist

### ISSUE THREAD

**Issue by PaxJaromeMalues** [Zrips/Jobs#1617]
### Description of new idea or improvement on existing one
**This is not thought to replace limitedItems!**
Its thought as a parallel feature using the same mechanics but in a different way.
As This is using already in place functionality, maybe the whole feature also takes less time to implement, if considered.

Using the same mechanics to prohibiting the use of an item by `limitedItems`, implement a blacklist (probably at the end of a config) for items by their ingame designation.

### Detailed information

If an item is named in the blacklist for example `DIAMOND_PICKAXE`:
- prohibit use by this job
- prohibit crafting by this job
- do not prohibit from picking up or storing in inventories
- if `DIAMOND_PICKAXE` matches entries in blacklist AND `limitedItems`: only allow variations of `DIAMOND_PICKAXE` from `limitedItems` but deny usage/crafting all others as per blacklist.
As this resembles a full blacklist, these items conditions should also meet `DIAMOND_PICKAXE` with any sort of lore or enchant (you could say the function is to ignore anything besides the string `DIAMOND_PICKAXE` which identifies the item towards the minecraft servers item database)

### Config Example
```yaml
  ... jobs/job.yml

  cmd-on-leave:
  - msg [name] You have left this awesome [jobname] job
  - msg [name] See you soon!
  limitedItems:
    firstOne:
      id: 278
      level: 5
      name: '&8Miner Pickaxe'
      lore:
      - '&eBobs pick'
      - '&710% bonus XP'
      enchants:
      - DAMAGE_ALL=1
      - FIRE_ASPECT=1
  item-blacklist:
    DIAMOND_PICKAXE:
      prohibit_usage: true/false
      prohibit_crafting: true/false
    DIAMOND_AXE:
      prohibit_usage: true/false
      prohibit_crafting: true/false
    DIAMOND_SHOVEL:
      prohibit_usage: true/false
      prohibit_crafting: true/false
```
