### ISSUE TITLE
RestrictedAreas not initializing on server-startup, only after forcing a jobs reload in-game.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#164]
JobsReborn 4.3.1
Paper dev 1313 (Spigot 1.12.2)

@Zrips restrictedAreas.yml is not initializing on server-startup / initial loading of jobs plugin. When going into a world that is suppose to be restricted and typing ```/jobs area info```, it doesn't return any restricted areas. Players are able to exploit money and experience from creative worlds.

Forcing a reload via ```/jobs reload```, the restrictions finally enable and players are not able to gain any xp or money while in that world. ```/jobs area info``` returns the restricted region after a config reload.

Thus this leads me to believe the restrictedAreas.yml is not initializing or being read at plugin initialization / server startup.

```
restrictedareas:
  creative:
    multiplier: -1.0
    world: build1
    point1:
      x: -5000
      y: 0
      z: -5000
    point2:
      x: 5000
      y: 256
      z: 5000
  worldedit:
    multiplier: -1.0
    world: build2
    point1:
      x: -5000
      y: 0
      z: -5000
    point2:
      x: 5000
      y: 256
      z: 5000

```
