### ISSUE TITLE
Hunter Job players get no money or ecp when killing a warden

### ISSUE THREAD

**Issue by PanetiX** [Zrips/Jobs#1645]
***Detailed description of the issue:**
We have a "hunter" job and players get no money or exp when they kill a warden. All other mobs are working. 

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Quests:
  Gui:
    Item: bow
  Kill:
    Warden:
      income: 1500.0
      points: 40
      experience: 100.0
```
```
Jäger:
  fullname: Jäger
  shortname: J
  FullDescription:
  - "Verdient Geld durch das Töten von Monstern"
  ChatColour: RED
  chat-display: full
  max-level: 50
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 0
  Quests:
  Gui:
    Item: bow
```
---

**Jobs version:** 
Jobs Reborn 5.2.0.0

**Server Type (Spigot/Paper/etc):** 
Paper Build [#163]

**Server Version (using `/ver`):**
