### ISSUE TITLE
Add "STRIPPED_BAMBOO_BLOCK" in "StripLogs" action

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/Jobs#1649]
**Description of new idea or improvement on existing one**
Hello,
Would it be possible to add the "STRIPPED_BAMBOO_BLOCK" to the "StripLogs" action, please?

**Detailed information what should do**
Because it's not considered wood, it doesn't count in this action.

**Maybe a config example if related**
```yml
  StripLogs:
    STRIPPED_BAMBOO_BLOCK:
      income: 1.0
      experience: 2.0
```
