### ISSUE TITLE
resetlimit will not reset the data of all players but only online players.

### ISSUE THREAD

**Issue by gary81013** [Zrips/Jobs#1653]
***Detailed description of the issue:**
resetlimit will not reset the data of all players but only online players.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Limit:
    # Money gain limit
    # With this enabled, players will be limited how much they can make in defined time
    # Time in seconds: 60 = 1 min, 3600 = 1 hour, 86400 = 24 hours
    Money:
      Use: true
      # Do you want to stop money gain when exp limit reached?
      StopWithExp: false
      # Do you want to stop money gain when point limit reached?
      StopWithPoint: false
      # Equation to calculate max limit. Option to use total level to include players total amount levels of current jobs
      # You can always use simple number to set money limit
      # Default equation is: 500+500*(totallevel/100), this will add 1% from 500 for each level player have
      # So player with 2 jobs with level 15 and 22 will have 685 limit
      MoneyLimit: 15000+15000*(totallevel/100)
      # Time in seconds: 60 = 1 min, 3600 = 1 hour, 86400 = 24 hours
      TimeLimit: 3600
      # Time in 24 hour format when limit should reset. This will override TimeLimit if defined
      # Example: '00:00:00' will reset timer at midnight, '04:30:00' will reset at 4:30 in the morning
      # Set to empty field if you want to use TimeLimit
      ResetTime: 00:00:30
      # Delay between announcements about reached money limit
      # Keep this from 30 to 5 min (300), as players can get annoyed of constant message displaying
      AnnouncementDelay: 30
```

---

**Jobs version:** 
Jobs5.2.1.0
**Server Type (Spigot/Paper/etc):** 
paper-1.20.1-174
**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**
MysqlPlayerDataBridge-v4.9.2
XConomy-Paper-2.25.1
Vault
waterfall
