### ISSUE TITLE
CustomModelData does not work on job icons

### ISSUE THREAD

**Issue by BrayaanPS** [Zrips/Jobs#1674]
***Detailed description of the issue:**
When using "CustomModelData" the items are changed to a green wool block. This happens only in the icons for jobs.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Minero:
  fullname: Minero
  shortname: Min
  description: '&e¡Gana dinero extrayendo minerales y minerales!'
  ChatColour: GREEN
  chat-display: full
  max-level: 20
  leveling-progression-equation: 1*(joblevel)+(joblevel*joblevel*1)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.001)-((baseincome+(baseincome*(joblevel-1)*0.001))
    * ((numjobs-1)*0.001))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.001)-((basepoints+(basepoints*(joblevel-1)*0.001))
    * ((numjobs-1)*0.001))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.001))
  rejoinCooldown: 60
  Gui:
    Item: PAPER{CustomModelData:57064}
```

---

**Jobs version:** 5.2.1.2

**Server Type (Spigot/Paper/etc):** Purpur

**Server Version (using `/ver`):** 1.20.2
