### ISSUE TITLE
Fishing get not Blocked by world-blacklist

### ISSUE THREAD

**Issue by Girollplay** [Zrips/Jobs#1680]
Plugin Versions:
Jobs Reborn: 5.2.1.2
Cmilib: 1.4.3.0

Shortend Config: 
```
Fischer:
  fullname: Fischer
  shortname: Fi
  FullDescription:
  - "Verdiene Geld durchs Angeln."
  ChatColour: AQUA
  chat-display: full
  max-level: 200
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: (baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05)))
    *((1+((joblevel+1-(joblevel+1)%25)/25*0.10))+((joblevel+1-(joblevel+1)%100)/100*0.50))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  Gui:
    Item: fishing_rod
  Fish:
    materials:
    - cod;1;;2
    - salmon;1;;2
    - tropical_fish;1;;2
    - pufferfish;1;;2
  Kill:
    materials:
    - DROWNED;1;;1
    - elder_guardian;20.0;;20.0
    - GUARDIAN;0.5;;0.5
    - squid;0.5;;0.5
    - glow_squid;0.75;;0.75
    - cod;0.5;;0.5
    - salmon;0.5;;0.5
    - tropical_fish;0.5;;0.5
  Break:
    materials:
    - Prismarine;0.01;;0.01
    - Prismarine_Bricks;0.01;;0.01
    - Dark_Prismarine;0.01;;0.01
    - Sea_Lantern;0.01;;0.01
```
    
```
  # Turns the 'world-blacklist' list into a whitelist. This essentially means the job only works in the specified worlds.
  reverse-world-blacklist-functionality: true
  # World list in which this job will not work. World name should be exact
  world-blacklist:
  - Farmwelt08
```
  
Breaking Block and Kill get blocked in every other world. For example Citybuild
