### ISSUE TITLE
The item is exchanged for wool

### ISSUE THREAD

**Issue by BrayaanPS** [Zrips/Jobs#1687]
***Detailed description of the issue:**
The items in the job menu appear as green wool blocks.
![image](https://github.com/Zrips/Jobs/assets/30274810/197a4c8a-ba01-4fdb-ba28-547e2385f6ab)

```
Explorador:
  fullname: Explorador
  shortname: Exp
  description: '&e¡Gana dinero explorando el mapa!'
  ChatColour: GREEN
  chat-display: full
  max-level: 20
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01)
    * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01)
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 60
  Gui:
    ItemStack: paper;cm{85742}
```

**Jobs version:** 5.2.2.1
**CMILib:** 1.4.3.4
**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** Paper (297) 1.20.2
![image](https://github.com/Zrips/Jobs/assets/30274810/46fdedf4-b7ae-4c04-a2d5-9f464e0710e6)
