### ISSUE TITLE
Woodcutter does not work

### ISSUE THREAD

**Issue by Aquamonk** [Zrips/Jobs#169]
Hello, I got a problem with the job Woodcutter, it doesnt work with the default config, it doesnt reward me anything, but Miner works perfectly, rewards everything correctly. I am using Paperspigot 1.12. Could you help me?

Cordial Greeting.
Thanks.

**Comment by montlikadani** [comment]
@Aquamonk 
Please send the Woodcutter job in jobConfig.yml.

**Comment by postal291** [comment]
I'm having the same issue.
Here's my woodcutter from jobConfig.yml

```
Woodcutter:
    fullname: Woodcutter
    shortname: W
    description: Earns money felling and planting trees
    ChatColour: GREEN
    chat-display: none
    max-level: 200
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    Gui:
      Id: 17
      Data: 2
    Break:
      17-0:
        income: 2.5
        points: 2.5
        experience: 2.5
      17-1:
        income: 2.0
        points: 2.5
        experience: 2.0
      17-2:
        income: 2.5
        points: 2.5
        experience: 2.5
      17-3:
        income: 2.5
        points: 2.5
        experience: 2.5
      18-0:
        income: 0.5
        points: 0.5
        experience: 0.5
      18-1:
        income: 0.5
        points: 0.5
        experience: 0.5
      18-2:
        income: 0.5
        points: 0.5
        experience: 0.5
      18-3:
        income: 0.5
        points: 0.5
        experience: 0.5
      161-0:
        income: 0.5
        points: 0.5
        experience: 0.5
      161-1:
        income: 0.5
        points: 0.5
        experience: 0.5
      162-0:
        income: 2.5
        points: 2.5
        experience: 2.5
      162-1:
        income: 2.5
        points: 2.5
        experience: 2.5
    Kill:
      Player:
        income: 7.5
        points: 7.5
        experience: 7.5
    custom-kill:
      Woodcutter:
        income: 10.0
        points: 10.0
        experience: 10.0
```
