### ISSUE TITLE
No Rewards for Boss Mobs

### ISSUE THREAD

**Issue by InDirectVariant** [Zrips/Jobs#1693]
***Detailed description of the issue:**
Players are not receiving rewards for killing the Ender Dragon, Warden, or Withers. The mobs show up in the job info page and all other mobs are paying out as expected. We've set the names in the config to match the Spigot Javadocs names to ensure proper compatibility. There are no errors in console on plugin load or upon players killing the mobs.

---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Hunter:
  fullname: Hunter
  shortname: H
  FullDescription:
  - '&bEarns money killing animals and monsters.'
  ChatColour: ORANGE
  chat-display: full
  max-level: 25
[Removed for Brevity]
  Gui:
    Item: netherite_sword
  Kill:
    Ender_Dragon:
      income: 150
      points: 0
      experience: 75
    WITHER:
      income: 150
      points: 0
      experience: 75
    WARDEN:
      income: 150
      points: 0
      experience: 75
    axolotl:
      income: 0.5
      points: 0
      experience: 1
[Removed for brevity]
```

---

**Jobs version:** 5.2.2.1 MySQL

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):** Build 318 1.20.2-R0.1-SNAPSHOT
