### ISSUE TITLE
Request: Fullnameplaceholder and JobshortPlaceholder for Jobs and shorts the player has

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/Jobs#1700]
If a Player has multiple jobs i wanne be able to parse out his job short and full name
a dined in the job file.

Here an Example:

```
Fisherman:
  fullname: Fischer
  shortname: Fi
  description: Verdiene Taler mit Angeln.
  ChatColour: AQUA
  chat-display: none
```

The Fullname is defined has Fischer
Now lets say a player has Fischer as first Job and i wanne show this somewhere.

If i would use %jobsr_user_job_1%  then i get Fisherman
For short none seems to exist.

So i sugest **%jobsr_user_fullname_job_1%**  that would parse out Fischer
and **%jobsr_user_shortname_job_1%** that would parse our Fi

This should be possible for may up to 5 or 10 jobs a player has.
So we could show them all for the player in own boards etc..
