### ISSUE TITLE
Pay trades much higher than the configuration. 

### ISSUE THREAD

**Issue by centerworld2023** [Zrips/Jobs#1701]
Good morning, 
I have a problem with a player; 
The player is level 4 at the job of Hunter, killing a cow ("vache" or a pig "cochon" the player wins + 200$ while he is supposed to get 2.5 or less. I want to clarify that the wage formulas are the original ones. If this problem exists on the "Chasseur" (Hunter) job, it is likely that the others are also concerned. 

Can someone help me understand? 

Thank you.

![image](https://github.com/Zrips/Jobs/assets/156122494/c34b70b2-342b-409c-8836-a11f8b2e5082)

![image](https://github.com/Zrips/Jobs/assets/156122494/063aa657-7d42-4a0a-9754-e2be32b1efec)

![image](https://github.com/Zrips/Jobs/assets/156122494/3e8ff378-92a6-48a3-8a54-5f91d1892f25)

**CONFIG SECTION :**
```
Hunter:
  fullname: Chasseur
  shortname: C
  FullDescription:
  - "Tuez des montres et des animaux pour être payé !"
  ChatColour: RED
  chat-display: full
  max-level: 200
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 2
  Quests:
    '1':
      Name: Prédateur
      Objectives:
      - Kill;Wolf;10
      - Kill;Creeper;3
      - Kill;Skeleton;10
      RewardCommands:
      - eco give [playerName] 50
      - msg [playerName] Quête réussite!
      RewardDesc:
      - Tuez et recevez votre récompense.
      - Recevez 50 pour cette quête !
  Gui:
    ItemStack: diamond_sword
  Tame:
    Wolf:
      income: 7.0
      points: 7.0
      experience: 7.0
    Ocelot:
      income: 7.0
      points: 7
      experience: 7.0
    Horse:
      income: 10.0
      points: 10
      experience: 10.0
  Kill:
    Chicken:
      income: 2.5
      points: 2.5
      experience: 2.5
    Cow:
      income: 2.5
      points: 2.5
      experience: 2.5
    Pig:
      income: 2.5
      points: 2.5
      experience: 2.5
    Sheep:
      income: 2.5
      points: 2.5
      experience: 2.5
    Wolf:
      income: 5.0
      points: 5
      experience: 2.5
    Creeper:
      income: 5
      points: 5
      experience: 5.0
    Skeleton:
      income: 7.0
      points: 7
      experience: 7.0
    Spider:
      income: 8.0
      points: 8
      experience: 8.0
    Zombie:
      income: 5.0
      points: 5
      experience: 5.0
    BLAZE:
      income: 7.0
      points: 7
      experience: 7.0
    CAVE_SPIDER:
      income: 10.0
      points: 10
      experience: 10.0
    ENDERMAN:
      income: 2.0
      points: 2
      experience: 2.0
    GHAST:
      income: 12.0
      points: 12
      experience: 12.0
    GIANT:
      income: 100.0
      points: 100
      experience: 50.0
    IRON_GOLEM:
      income: 15.0
      points: 15
      experience: 15.0
    mushroom_cow:
      income: 2.5
      points: 2.5
      experience: 2.5
    SILVERFISH:
      income: 1.5
      points: 1.5
      experience: 0.25
    SNOWMAN:
      income: 1
      points: 1
      experience: 2.0
    SQUID:
      income: 1.0
      points: 1
      experience: 1.0
    RABBIT:
      income: 1.0
      points: 1
      experience: 1.0
    GUARDIAN:
      income: 1.0
      points: 1
      experience: 1.0
    SHULKER:
      income: 2.5
      points: 2.5
      experience: 2.5
    PHANTOM:
      income: 2.5
      points: 2.5
      experience: 2.5
    DROWNED:
      income: 2.5
      points: 2.5
      experience: 2.5
    HUSK:
      income: 2.5
      points: 2.5
      experience: 2.5
    WITHER:
      income: 25.0
      points: 25
      experience: 50.0
    ENDER_DRAGON:
      income: 1000.0
      points: 1000
      experience: 2000.0
    Player:
      income: 5
      points: 5
      experience: 5.0

```

---

**Jobs version: 5.2.2.2** 

**Server Type (Spigot/Paper/etc): Spigot 1.19.3** 

**Server Version (using `/ver`): This server is running CraftBukkit version 3638-Spigot-d90018e-7dcb59b (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT**
