### ISSUE TITLE
reset limit cannot reset all database players

### ISSUE THREAD

**Issue by gary81013** [Zrips/Jobs#1713]
***Detailed description of the issue:**
I use mysql to synchronize multiple servers
However, whenever I use the ResetTime function to reset the player Limit
Not all players will be remade, but only online players will be remade. I have reported this problem before, but now it has happened again.
And I use the command /jobs resetlimit all and the result is the same.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
  Limit:
    # Money gain limit
    # With this enabled, players will be limited how much they can make in defined time
    # Time in seconds: 60 = 1 min, 3600 = 1 hour, 86400 = 24 hours
    Money:
      Use: true
      # Do you want to stop money gain when exp limit reached?
      StopWithExp: false
      # Do you want to stop money gain when point limit reached?
      StopWithPoint: false
      # Equation to calculate max limit. Option to use total level to include players total amount levels of current jobs
      # You can always use simple number to set money limit
      # Default equation is: 500+500*(totallevel/100), this will add 1% from 500 for each level player have
      # So player with 2 jobs with level 15 and 22 will have 685 limit
      MoneyLimit: 15000+15000*(totallevel/100)
      # Time in seconds: 60 = 1 min, 3600 = 1 hour, 86400 = 24 hours
      TimeLimit: 86400
      # Time in 24 hour format when limit should reset. This will override TimeLimit if defined
      # Example: '00:00:00' will reset timer at midnight, '04:30:00' will reset at 4:30 in the morning
      # Set to empty field if you want to use TimeLimit
      ResetTime: 00:00:30
      # Delay between announcements about reached money limit
      # Keep this from 30 to 5 min (300), as players can get annoyed of constant message displaying
      AnnouncementDelay: 30
#####################################
```

---

**Jobs version:** 
Jobs-5.2.2.3
**Server Type (Spigot/Paper/etc):** 
Paper-196 (MC: 1.20.1)
**Server Version (using `/ver`):** 
1.20.1
