### ISSUE TITLE
Jobs shop no longer showing points cost of items, nor points user has

### ISSUE THREAD

**Issue by Momshroom** [Zrips/Jobs#1719]
***Detailed description of the issue:**
After updating my server to 1.20.4, points are no longer showing in Jobs Shop: neither prices nor user balance.  (We were coming from 1.20.1)
In an attempt to fix it, I changed one item to the new ItemStack format.  That didn't help.
The items all show properly, but no prices.  No user balance.
I've included two items from the shopItems.yml file below: one in the old format and the one I converted.
I have not edited the language file and I have confirmed it still shows it's supposed to show points

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Jobs25MoneyBoost:
    Price: 5.0
    Icon:
      Id: sweet_berries
      Amount: 1
      Name: "&bGet a kit that gives you an item that gives you 25% more money from jobs for half an hour"
      HideWithoutPermission: false
      HideIfThereIsNoEnoughPoints: false
    PerformCommands:
    - "lp user [player] permission set cmi.kit.JobsMoneyBoost"
    - "msg &bMake sure to claim your kit before you buy this again! It will not give you a new kit if you have not claimed your previous kit"
  Jobs100XPBoost:
    Price: 5.0
    Icon:
      ItemStack: cooked_salmon;&bGet_a_kit_that_gives_you_an_item_that_gives_you_twice_the_jobs_xp_for_half_an_hour;1
      HideWithoutPermission: false
      HideIfThereIsNoEnoughPoints: false
    PerformCommands:
    - "lp user [player] permission set cmi.kit.JobsXPBoost"
    - "msg &bMake sure to claim your kit before you buy this again! It will not give you a new kit if you have not claimed your previous kit"

```

---

**Jobs version:** 
5.2.2.3
**Server Type (Spigot/Paper/etc):** 
paper
**Server Version (using `/ver`):** 
paper 408, 1.20.4
