### ISSUE TITLE
Translation support for GUI items

### ISSUE THREAD

**Issue by Kovalski4** [Zrips/Jobs#1720]
**Description of new idea or improvement on existing one**
Ability to change text on gui buttons
**Detailed information what should do**
I want to change text on gui items like confirm, join, close etc. but there is only texture support.

```
  InfoButton:
    # Slot for info button. Set it to 0 if you want to disable it
    # Locale can be customized in locale file under gui->infoLore section
    Slot: 0
    Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjcwNWZkOTRhMGM0MzE5MjdmYjRlNjM5YjBmY2ZiNDk3MTdlNDEyMjg1YTAyYjQzOWUwMTEyZGEyMmIyZTJlYyJ9fX0=
    # closeinv! can be used to close players inventory when you click this icon
    Commands:
    - closeinv!
  JoinButton:
    Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmZlYzNkMjVhZTBkMTQ3YzM0MmM0NTM3MGUwZTQzMzAwYTRlNDhhNWI0M2Y5YmI4NThiYWJmZjc1NjE0NGRhYyJ9fX0=
  LeaveButton:
    Material: head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzY1ZjNiYWUwZDIwM2JhMTZmZTFkYzNkMTMwN2E4NmE2MzhiZTkyNDQ3MWYyM2U4MmFiZDlkNzhmOGEzZmNhIn19fQ==
```
