### ISSUE TITLE
Mobs not giving exp

### ISSUE THREAD

**Issue by WarnDa** [Zrips/Jobs#1728]
**Detailed description of the issue:**
Since a recent update where you made mob giving exp but being killed by lava after a player made damage to it
![image](https://github.com/Zrips/Jobs/assets/31826333/51cc68ea-0d7c-4dd0-98ff-c4950835834e)
But now, I face two issues.
If I set : 
```
    MonsterDamage:
      # This section controls how much damage player should do to monster for player to get paid
      # This prevents from killing monsters in one hit when they suffer in example fall damage
      Use: false
      Percentage: 1
```
If player hurt once the mob, pull it in lava, he will get exp for every mob that will die after.

So I set : 
```
    MonsterDamage:
      # This section controls how much damage player should do to monster for player to get paid
      # This prevents from killing monsters in one hit when they suffer in example fall damage
      Use: true
      Percentage: 1
```
Then sometimes mobs do not give any exp when you kill it (even if you deal all the damage)
It doesn't happen all the time, but sometimes randomly, can't figure out why and when, you don't drop exp during 5mn, then it gives exp again..

So the best things would to be put a toggle ON/OFF for THIS option :  
![image](https://github.com/Zrips/Jobs/assets/31826333/e9cb022e-34d9-4a0c-8a68-99934f723cc5)

---

**Jobs version:** 
![image](https://github.com/Zrips/Jobs/assets/31826333/e0eac33c-bcf7-41a7-a249-df3c4340001f)

**Server Type (Spigot/Paper/etc):** 
Paper
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-459 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 88419b2)

**Relevant plugins (Delete if this isn't needed):**
WildStacker b40 (latest dev build from https://hub.bg-software.com/job/WildStacker%20-%20Dev%20Builds/ )
