### ISSUE TITLE
Netherite Tools and Armor not giving payouts when crafted in a Smithing Table

### ISSUE THREAD

**Issue by Seeroh** [Zrips/Jobs#1731]
***Detailed description of the issue:**

When trying to craft Netherite Items using a Smithing Table, there is no payout given at all. Crafting other items in a regular crafting table gives payouts like normal.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Craft:
    NETHERITE_PICKAXE:
      income: 10
      experience: 20
```

---

**Jobs version:** 
Jobs Version: 5.2.2.3

**Server Type (Spigot/Paper/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-409 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
