### ISSUE TITLE
Raid spawned Entities not giving any reward

### ISSUE THREAD

**Issue by SiSchu** [Zrips/Jobs#1751]
***Detailed description of the issue:**
It seems like all the raid-spawned mobs not giving points neither money or exp. When I spawn them using spawn egg or kill for example the pillager at an outpost, only then I will get any reward out of them.

**CONFIG SECTION:**
Jobs/hunter.yml
```
    VINDICATOR:
      income: 20.0
      points: 20
      experience: 30.0
    VEX:
      income: 60.0
      points: 20
      experience: 60.0
    PILLAGER:
      income: 20.0
      points: 30
      experience: 30.0
    WITCH:
      income: 40.0
      points: 40
      experience: 50.0
    EVOKER:
      income: 50.0
      points: 40
      experience: 60.0
```

**Jobs version:**
5.2.2.5 

**Server Type (Spigot/Paper/etc):**
Paper 

**Server Version (using `/ver`):**
1.20.4 (Paper 478)
