### ISSUE TITLE
BossBarCoulor not working.

### ISSUE THREAD

**Issue by matipoirierg** [Zrips/Jobs#1758]
BossBarColour is not working, when used is not changing the color of the job boss bar. I'm on 5.2.2.5, CmiLib 1.4.7.7

```
Minero:
  fullname: Minero
  shortname: Mi
  FullDescription:
  - "Gana dinero minando menas y minerales."
  ChatColour: DARK_GRAY
  BossBarColour: YELLOW
  chat-display: full
  max-level: 100
  leveling-progression-equation: 13*(joblevel)+(joblevel*joblevel*5)
  income-progression-equation: baseincome+(baseincome*(joblevel-2)*0.01)-((baseincome+(baseincome*(joblevel-2)*0.01))
    * ((numjobs-1)*0.01))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 0
  Gui:
    Item: wooden_pickaxe
  Break:
    andesite:
      income: 0.1
      experience: 0.1
    granite:
      income: 0.1
      experience: 0.1
    diorite:
      income: 0.1
      experience: 0.1
    sandstone:
      income: 0.015
      experience: 0.02
    chiseled_sandstone:
      income: 0.015
      experience: 0.02
    cut_sandstone:
      income: 0.015
      experience: 0.02
    coal_ore:
      income: 0.3
      experience: 0.2
    deepslate_coal_ore:
      income: 0.4
      experience: 0.3
    redstone_ore:
      income: 0.25
      experience: 0.4
    deepslate_redstone_ore:
      income: 0.35
      experience: 0.6
    copper_ore:
      income: 0.35
      experience: 0.4
    deepslate_copper_ore:
      income: 0.45
      experience: 0.6
    iron_ore:
      income: 0.7
      experience: 0.4
    deepslate_iron_ore:
      income: 0.9
      experience: 0.6
    gold_ore:
      income: 5
      experience: 2
    deepslate_gold_ore:
      income: 6
      experience: 3
    lapis_ore:
      income: 7.5
      experience: 2
    deepslate_lapis_ore:
      income: 8.5
      experience: 3
    diamond_ore:
      income: 10
      experience: 10
    deepslate_diamond_ore:
      income: 12.5
      experience: 12.5
    emerald_ore:
      income: 15
      experience: 30
    deepslate_emerald_ore:
      income: 17.5
      experience: 35
    nether_quartz_ore:
      income: 0.5
      experience: 0.8
    nether_gold_ore:
      income: 0.5
      experience: 0.3
    ancient_debris:
      income: 200.0
      experience: 50.0
```
