### ISSUE TITLE
Add action for brushing

### ISSUE THREAD

**Issue by Pirito10** [Zrips/Jobs#1763]
**Add a new action that allows players to get paid for using the brush on suspicious sand/gravel:**

```
  Brush:
    suspicious_sand:
      income: 1
      points: 1
      experience: 1
    suspicious_gravel:
      income: 1
      points: 1
      experience: 1
```
