### ISSUE TITLE
PyroFishing still has a bug that disables fisherman job.

### ISSUE THREAD

**Issue by Lia-LV** [Zrips/Jobs#1774]
***Detailed description of the issue:**
If I fishing on a server with PyroFishing, Jobs Reborn's fisherman level still doesn't go up and income won't be paid.
and Jobs 5.2.3.1 update note says "Fix for PyroFishing compatibility breaking regular fishing".

```
below, my jobs version info in server.
------------------------------------------------
Jobs: 5.2.3.1 SqLite-> 5.2.3.0
CMILib: 1.4.7.15 -> 1.4.7.16
Server: 2218 1.20.6-R0.1-SNAPSHOT
Economy: CMIEconomy Vault: 1.7.3-CMI
------------------------------------------------
```
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
<-- Try to use pastebin.com server if you have long error. -->
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Jobs version:** 5.2.3.1

**Server Type (Spigot/Paper/etc):** Purpur(forked of Paper)

**Server Version (using `/ver`):** 1.20.6-2218-ec1b4fa (MC: 1.20.6)

**Relevant plugins (Delete if this isn't needed):** PyroFishingPro

**Comment by Lia-LV** [comment]
Sorry, I didn't know that I have to custom settings.

**Comment by mrfloris** [comment]
Okay, this seems to work for me with .1 of jobs

```yaml
  # Catching CUSTOM fish of the PyroFishingPro plugin
  PyroFishingPro:
    CustomTier:
      income: 5.0
      points: 5.0
      experience: 7.0
    Bronze:
      income: 5.0
      points: 5.0
      experience: 7.0
    Gold:
      income: 5.0
      points: 5.0
      experience: 7.0
    Silver:
      income: 5.0
      points: 5.0
      experience: 7.0
    Diamond:
      income: 5.0
      points: 5.0
      experience: 7.0
    Platinum:
      income: 5.0
      points: 5.0
      experience: 7.0
    Mythical:
      income: 5.0
      points: 5.0
      experience: 7.0
```
