### ISSUE TITLE
Extending capabilities of restricted areas

### ISSUE THREAD

**Issue by MadeBySaints** [Zrips/Jobs#1819]
Restricted areas are an untapped superpower of Jobs

I think it would be great to extend their functionality in the following ways:

Add an option in the config to restrict an area to a specific job and level
Add options for restricted areas to boost payout of points, exp or money, rather than just a single multiplier for everything.
Add custom area permission restrictions. these would essentially ignore players without permissions in a restricted area, and they would gain no bonus

Selection improvements:
Add option to add world edit selection as restricted area
/jobs area add we [bonus]

quality of life improvements:
Add clickable text to modify restricted area values such as multipliers, or adding/removing jobs from areas. A list similar to the way holograms are handled in CMI would be ideal

example config:

```
restrictedareas:
  Wilderness1:
    world: Wasteland
    permission: jobs.area.[areaName]
    ignoreWithoutPermission: true
    jobs:
      miner-10
      any
    Payouts:
      money: 1.25
      exp: -1.0
      points: 6.55
    Area:
      point1:
        x: -3975
        y: 41
        z: -3866
      point2:
        x: -3833
        y: 99
        z: -3705
```
