### ISSUE TITLE
Conditional permission at a certain job level

### ISSUE THREAD

**Issue by ElLlelouch** [Zrips/Jobs#1820]
Hello, I have an issue about Jobs' conditions to give temporary permissions once a certain level is obtained...

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  conditions:
    buch:
      requires:
      - j:Bucheron-40
      - p:tier.jobs2
      perform:
      - p:jobs.join.Menuisier-true`


```
I have players that have the first job "Bucheron", which is required to be lvl 40 to take "Menuisier". Except they can't.
After some tests I saw that they needed their secondary job (Miner, for my test subject) to get to lvl 40 to take "Menuisier".

May someone help me about this?
(Same goes for other jobs with 2 prerequisites, but not for all of they jobs I have on server...)
---

**Jobs version:** 5.2.4.0

**Server Type (Spigot/Paper/etc):**  Purpur

**Server Version (using `/ver`):** 1.21.0

**Relevant plugins (Delete if this isn't needed):** LuckPermBungee ?
