### ISSUE TITLE
Impossible to modify equation

### ISSUE THREAD

**Issue by iJuju68** [Zrips/Jobs#1826]
### Description of Issue

When I change the equation, the jobs no longer works, and I no longer receive money or XP.

### Version Information

```shell
Jobs version: 5.2.2.1

PaperSpigot

PaperSpigot-445 (MC: 1.8.8)
```

### Relevant Config Sections

```yaml
Chasseur:
  fullname: Chasseur
  shortname: C
  FullDescription:
  - "Gagne de l'argent tuant des monstres"
  ChatColour: ORANGE
  chat-display: full
  max-level: 100
  leveling-progression-equation: 1*(joblevel)*(1.2)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01)) * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01)) * ((numjobs-1)*0.05))
  experience-progression-equation: (baseexperience)*1.1
  #  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 1
  Quests:
    '1':
      Name: DarkOne
      Objectives:
      - Break;stone;50
      - Break;granite;50
      - Break;sandstone;5000000
      RewardCommands:
      - eco give [playerName] 100
      - msg [playerName] Completed quest!
      RewardDesc:
      - Break blocks and get money
      - Get 100 for this!
  Gui:
    Item: DIAMOND_SWORD
  Kill:
    Chicken:
      income: 20.83
      points: 0.1
      experience: 0.5
    Cow:
      income: 20.83
      points: 0.1
      experience: 0.5
    Pig:
      income: 20.83
      points: 0.1
      experience: 0.5
    Sheep:
      income: 20.83
      points: 0.1
      experience: 0.5
    Creeper:
      income: 15.0
      points: 0.1
      experience: 1.0
    Skeleton:
      income: 13.89
      points: 0.1
      experience: 1.0
    Spider:
      income: 13.89
      points: 0.1
      experience: 1.0
    Zombie:
      income: 13.89
      points: 0.1
      experience: 1.0
    PIG_ZOMBIE:
      income: 69.44
      points: 0.1
      experience: 1.0
    BLAZE:
      income: 13.89
      points: 0.1
      experience: 1.0
    CAVE_SPIDER:
      income: 13.89
      points: 0.1
      experience: 1.0
    ENDERMAN:
      income: 34.72
      points: 0.1
      experience: 0.5
```

### Relevant Plugins

Vault 1.7.2-b131
