### ISSUE TITLE
Permission-Based Quest Access Control

### ISSUE THREAD

**Issue by 7hatGuyAJ** [Zrips/Jobs#1829]
I would like to request the addition of a permission-based check system for quests, allowing for greater control over which quests can be accessed and when. While I am aware that quests can already be grouped by level requirements, this does not address the current issues with randomness or repeatability. Quests are still given out in a random and often repetitive order, which limits their potential. By introducing a permissions-based system, quests could follow a more structured progression, making them a much more integral and engaging part of Jobs Reborn, rather than feeling like a repetitive gimmick. This feature would offer players a more meaningful and customizable questing experience.

Introduce a permission-based check for quests, allowing server owners to control access to specific quests based on player permissions. This would prevent quests from being randomly assigned or repeated until specific criteria are met. The system could support the following format in the configuration file.
```
  Quests:
    first:
      Name: "Break Oak wood"
      Objectives:
      - "Break;oak_log;300"
      - "Place;stone,cobblestone;5"
      RewardCommands:
      - "eco give [playerName] 500"
      - "msg [playerName] Completed quest!"
      RewardDesc:
      - "Break 300 Oak wood"
      - "Get 500 bucks for this"
      RestrictedAreas:
      - "Arenas"
      - "myarena"
      HasPermissions: "<permission.node>"
```
