### ISSUE TITLE
Time to Cook (Cook position)

### ISSUE THREAD

**Issue by r4gep1ay** [Zrips/Jobs#1831]
### Description of Issue

I want to create a position - Cook.
I enter config.yml - Bake, no experience and money, I enter - Cook and Smelt, the same thing. I need that when frying food in the oven and on the fire, the player is given experience and money for preparing delicious food. Also interested in the question of eating food. I enter Eat into the config and notice that experience and money cannot be obtained for eating cake and potatoes, I haven’t checked anything else. Tell me how can I do it the way I want?
--------------------------------------------------------------------------------------------------------------------------------------------
Хочу создать должность - Повар.
Ввожу config.yml - Bake, опыта и денег нет, ввожу - Cook и Smelt, тоже самое. Мне нужно, чтобы при жарке еды в печи и на костре игроку давали опыт и деньги за приготовление вкусной еды. Также интересует вопрос по поеданию еды. Ввожу Eat в конфиг и замечаю, что за поедание торта и картошки опыт и деньги получить нельзя, больше ничего не проверял. Подскажите, как сделать так, как я хочу?

### Version Information

```shell
5.2.4.2
```

### Errors

```shell
I noticed earlier that when entering /jobs join (and other commands: Leave, Leaveall, etc.) into the console, the player's nickname is spammed: /jobs [ command] browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse, and so on. I reinstalled the plugin and everything was solved
-------------------------------------------------------------------------------------------------------------------------------------------
ранее заметил, что при вписывании /jobs join (и другие команды: Leave, Leaveall и тд) в консоль спамит никнейм игрока: /jobs [ command] browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse browse, и так далее. я переустановил плагин и всё решилось
```

### Relevant Config Sections

```yaml
Повар:
  fullname: Повар
  shortname: П
  FullDescription:
  - "Зарабатывайте деньги, приготовляя вкусную пищу."
  ChatColour: GREEN
  chat-display: shortfull
  max-level: 200
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 1
  Quests:
    '1':
      Name: Кулинарный вызов
      Objectives:
      - Craft;Bread;5
      - Bake;Cooked_Beef;3
      - Bake;Cooked_Chicken;2
      RewardCommands:
      - eco give [playerName] 500
      - msg [playerName] Задание выполнено!
      RewardDesc:
      - Приготовь вкусную пищу и получи за это 500₽!
  Gui:
    ItemStack: cookie
  Craft:
    Bread:
      income: 5.0
      points: 5.0
      experience: 5.0
    Pumpkin_Pie:
      income: 15.0
      points: 15.0
      experience: 15.0
    mushroom_stew:
      income: 10.0
      points: 10.0
      experience: 10.0
    rabbit_stew:
      income: 10.0
      points: 10.0
      experience: 10.0
    beetroot_soup:
      income: 10.0
      points: 10.0
      experience: 10.0
    golden_carrot:
      income: 20.0
      points: 20.0
      experience: 20.0
    Cake:
      income: 50.0
      points: 50.0
      experience: 50.0
    golden_apple:
      income: 100.0
      points: 100.0
      experience: 100.0
    Cookie:
      income: 35.0
      points: 35.0
      experience: 35.0
    honey_bottle:
      income: 20.0
      points: 20.0
      experience: 20.0
    suspicious_stew:
      income: 25.0
      points: 25.0
      experience: 25.0
  Eat:
    cookie:
      income: 5
      experience: 5
    baked_potato:
      income: 5
      experience: 5
    cooked_beef:
      income: 10.0
      experience: 10.0
    cooked_chicken:
      income: 8.0
      experience: 8.0
    cooked_cod:
      income: 8.0
      experience: 8.0
    cooked_salmon:
      income: 8.0
      experience: 8.0
    cooked_mutton:
      income: 7.0
      experience: 7.0
    cooked_porkchop:
      income: 9.0
      experience: 9.0
    cooked_rabbit:
      income: 6.0
      experience: 6.0
    baked_potato:
      income: 5
      experience: 5
  Bake:
    beef:
      income: 1.0
      experience: 1.0
    porkchop:
      income: 0.5
      points: 0.4
    potato:
      income: 5
      experience: 5
```

### Relevant Plugins

Vault 1.7.3, LuckPerms (last versions), EssentialsX (last versions)
