### ISSUE TITLE
Block Protection System Potentially Incorrect

### ISSUE THREAD

**Issue by DarioMavilia** [Zrips/Jobs#1832]
### Description of Issue

I'm trying to make it so placed ores can't be broken again for money (by setting their `blocksTimer` to -1 in `restrictedBlocks.yml`). Though, when I place coal ore and wait about a minute, i can break it again and get paid. From what I can read on the docs and comments, a -1 should mean that block is protected indefinitely after it's placed.

### Version Information

```shell
:36:03 INFO]: Jobs: 5.2.4.3 MySQL
[17:36:03 INFO]: CMILib: 1.5.1.4 
[17:36:03 INFO]: Server: 2321 1.21.1-R0.1-SNAPSHOT
[17:36:03 INFO]: Economy: CMIEconomy Vault: 1.7.3-b131(CMIEInjector)
```

### Errors

```shell
N/A
```

### Relevant Config Sections

```yaml
General:
    PlaceAndBreak:
      # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
      # Modify restrictedBlocks.yml for blocks you want to protect
      Enabled: true
      # Should we use new block protection method
      # In most cases this is more efficient way to check for break/place protection and doesn't involve any cache or data saving into database
      # Only works with 1.14+ servers
      NewMethod: true
      BlockTracker:
        # Should we use BlockTracker plugin instead of built in block tracker
        Enabled: false
      # Enabling this we will ignore blocks generated in ore generators, liko stone, coublestone and obsidian. You can still use timer on player placed obsidian block
      IgnoreOreGenerators: true
      # Only applies when old method is used
      # For how long in days to keep block protection data in data base
      # This will clean block data which ones have -1 as cooldown value
      # Data base cleanup will be performed on each server startup
      # This cant be more then 14 days
      KeepDataFor: 14
      GlobalBlockTimer:
        # All blocks will be protected X seconds after player places it
        Place:
          Use: true
          # Time in seconds. This can only be positive number and no higher than 900
          # If higher timers are needed then it can be defined in restrictedBlocks.yml file for each specific block
          Timer: 900
        Break:
          Use: true
          # Time in seconds. This can only be positive number and no higher than 60
          # This is only to prevent player from placing blocks into same place and getting paid once more
          Timer: 60
      # Enable silk touch protection.
      # With this enabled players wont get paid for broken blocks from restrictedblocks list with silk touch tool.
      SilkTouchProtection: false```
```
