### ISSUE TITLE
ActionBar payments/exp 

### ISSUE THREAD

**Issue by Serial1990** [Zrips/Jobs#1843]
### Description of Issue

https://github.com/user-attachments/assets/b962ac47-f8f0-4f18-bb91-d72a5cec7b08

### Version Information

```shell
Jobs: 5.2.4.2 MySQL-> 5.2.4.5
CMILib: 1.5.1.1 -> 1.5.1.6
Server: 123 1.21.1-R0.1-SNAPSHOT
Economy: AdvancedEconomyPlus Vault: 1.7.3-b23
```

### Errors

```shell
-
```

### Relevant Config Sections

```yaml
ActionBars:
  Messages:
    # When this set to true player will see action bar messages by default
    # When false, players will see chat messages instead.
    EnabledByDefault: true
    # Time in seconds action bar will remain visible if enabled
    # This time is used to define for how long we will accumulate payments to be shown in action bar
    # If no payments are being issued in defined time then it will reset to 0 and remain hidden
    KeepFor: 5
```

### Relevant Plugins

MobStacker
