### ISSUE TITLE
Message is broadcast anyway

### ISSUE THREAD

**Issue by Valtn** [Zrips/Jobs#185]
generalConfig.yml:
```yaml
broadcast:
  on-skill-up:
    # Do all players get a message when somone goes up a skill level?
    use: false
  on-level-up:
    # Do all players get a message when somone goes up a level?
    use: true
    # For what levels you want to broadcast message? Keep it at 0 if you want for all of them
    levels:
    - 100
```

If you set the first option to `false` and the second one to `true` all players receive a broadcast with `message.skillup.nobroadcast`
