### ISSUE TITLE
Suspicious Stew not giving job rewards when crafted

### ISSUE THREAD

**Issue by hvtess** [Zrips/Jobs#1854]
### Description of Issue

Crafting suspicious stew does not pay income, experience or points.

Confirmed with /jobs iteminfo we are using the correct config file usage.

### Version Information

```shell
Jobs: 5.2.4.5 SqLite
CMILib: 1.5.2.3
Server: DEV 1.21.1_R0.1-SNAPSHOT
Economy: EssentialsX Economy Vault: 1.7.3-b131
```

### Relevant Config Sections

```yaml
Craft:    
    SUSPICIOUS_STEW:
      income: 20
      points: 20
      experience: 20
```
