### ISSUE TITLE
Exploitprotection 'PreventHopperFillUps' for smelting not working

### ISSUE THREAD

**Issue by Rubyo2000** [Zrips/Jobs#1860]
### Description of Issue

Even though I have the exploit protect configured to prevent hopper fill ups to work for smelting, it was reported to me by our players that it does work. After experimenting with it myself, I can confirm that indeed it pays for their smelting jobs.. This protection did work for me in earlier versions.

![image](https://github.com/user-attachments/assets/1dab6d5c-73c8-450d-955c-82f6112f9785)

### Version Information

```shell
[10:24:44 INFO]: --------------------------------------------------
[10:24:44 INFO]: Jobs: 5.2.4.5 MySQL
[10:24:44 INFO]: CMILib: 1.5.2.3 -> 1.5.2.5
[10:24:44 INFO]: Server: 2329 1.21.1-R0.1-SNAPSHOT
[10:24:44 INFO]: Economy: EssentialsX Economy Vault: 1.7.3-b131
[10:24:44 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
In GeneralConfig.yml:

ExploitProtections:
  Furnaces:
    # When enabled, players interacted furnaces will be saved into a file and will be reassigned after restart to keep giving out money
    # Players will no longer need to click on furnace to get paid from it after server restart
    Reassign: true
    # Defines max available furnaces each player can have to get paid from
    # This can be overridden with jobs.maxfurnaces.[amount] permission node
    MaxDefaultAvailable: 12
  BlastFurnaces:
    Reassign: true
    MaxDefaultAvailable: 12
  Smokers:
    Reassign: true
    MaxDefaultAvailable: 12
  BrewingStands:
    # When enabled, players interacted brewing stands will be saved into file and will be reassigned after restart to keep giving out money
    # Players will no longer need to click on brewing stand to get paid from it after server restart
    Reassign: true
    # Defines max available brewing stands each player can have to get paid from
    # Set to 0 if you want to disable this limitation
    # This can be overridden with jobs.maxbrewingstands.[amount] permission node
    MaxDefaultAvailable: 12
  General:
    PlaceAndBreak:
      # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
      # Modify restrictedBlocks.yml for blocks you want to protect
      Enabled: true
      # Should we use new block protection method
      # In most cases this is more efficient way to check for break/place protection and doesn't involve any cache or data saving into database
      # Only works with 1.14+ servers
      NewMethod: true
      BlockTracker:
        # Should we use BlockTracker plugin instead of built in block tracker
        Enabled: false
      # Enabling this we will ignore blocks generated in ore generators, liko stone, coublestone and obsidian. You can still use timer on player placed obsidian block
      IgnoreOreGenerators: true
      # Only applies when old method is used
      # For how long in days to keep block protection data in data base
      # This will clean block data which ones have -1 as cooldown value
      # Data base cleanup will be performed on each server startup
      # This cant be more then 14 days
      KeepDataFor: 14
      GlobalBlockTimer:
        # All blocks will be protected X seconds after player places it
        Place:
          Use: true
          # Time in seconds. This can only be positive number and no higher than 900
          # If higher timers are needed then it can be defined in restrictedBlocks.yml file for each specific block
          Timer: 3
        Break:
          Use: true
          # Time in seconds. This can only be positive number and no higher than 60
          # This is only to prevent player from placing blocks into same place and getting paid once more
          Timer: 3
      # Enable silk touch protection.
      # With this enabled players wont get paid for broken blocks from restrictedblocks list with silk touch tool.
      SilkTouchProtection: false
    MonsterDamage:
      # This section controls how much damage player should do to monster for player to get paid
      # This prevents from killing monsters in one hit when they suffer in example fall damage
      Use: false
      Percentage: 60
      # When enabled we will avoid checking damage done to ender dragon, wither and warden
      # This can help out in case you have server with custom damage sources which might not be registered and payouts might not be given out
      IgnoreBosses: true
    # Should tamed animals payout to their owners?
    TameablesPayout: true
  # McMMO abilities
  McMMO:
    # Players will get part of money from cutting trees with treefeller ability enabled.
    # 0.2 means 20% of original price
    TreeFellerMultiplier: 0.02
    # Players will get part of money from braking blocks with gigaDrill ability enabled.
    # 0.2 means 20% of original price
    gigaDrillMultiplier: 0.5
    # Players will get part of money from braking blocks with super breaker ability enabled.
    # 0.2 means 20% of original price
    superBreakerMultiplier: 0.5
  # MythicMobs plugin support
  # Disable if you having issues with it or using old version
  MythicMobs:
    enabled: true
  Smelt:
    # Prevent payments when hoppers moving items into furnace
    # Player will not get paid, but items will be smelted
    PreventHopperFillUps: true
  Brew:
    PreventBrewingStandFillUps: true
  # Do you want to show informational message when payments from blocks gets disabled due to hopper transfers
  informOnPaymentDisable: true
```
