### ISSUE TITLE
Anvil repair not counting towards quests

### ISSUE THREAD

**Issue by Momshroom** [Zrips/Jobs#1866]
### Description of Issue

Repairing a diamond pickaxe on an anvil no longer completes a quest to do so, with neither a diamond nor another pick.

The quest config:
`    4:
      Name: "A Diamond Is Forever"
      Objectives:
      - repair;diamond_pickaxe;1
      RewardCommands:
      - cmi ctellraw [playerName] <T>&f[&bJobsQuest&f] &7Completed the A Diamond Is Forever quest! You got $100 and 16 diamonds!</T><H>&b/jobs quests &7for more info</H><C>jobs quests</C>
      - money grant [playerName] 100
      - cmi give [playerName] diamond 16
      RewardDesc:
      - Repair a diamond pickaxe with an anvil
      - Get $100 and 16 diamonds!
      Chance: 10
      toLevel: 300
      fromLevel: 3`

### Version Information

```shell
[23:52:09 INFO]: --------------------------------------------------
[23:52:09 INFO]: Jobs: 5.2.4.5 SqLite
[23:52:09 INFO]: CMILib: 1.5.2.7 
[23:52:09 INFO]: Server: 82 1.21.3-R0.1-SNAPSHOT
[23:52:09 INFO]: Economy: iConomy 5.25 Vault: 1.7.3-b131 
[23:52:09 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
`    4:
      Name: "A Diamond Is Forever"
      Objectives:
      - repair;diamond_pickaxe;1
      RewardCommands:
      - cmi ctellraw [playerName] <T>&f[&bJobsQuest&f] &7Completed the A Diamond Is Forever quest! You got $100 and 16 diamonds!</T><H>&b/jobs quests &7for more info</H><C>jobs quests</C>
      - money grant [playerName] 100
      - cmi give [playerName] diamond 16
      RewardDesc:
      - Repair a diamond pickaxe with an anvil
      - Get $100 and 16 diamonds!
      Chance: 10
      toLevel: 300
      fromLevel: 3`
```
