### ISSUE TITLE
"/jobs stats" english even after translating

### ISSUE THREAD

**Issue by PhilippStamp** [Zrips/Jobs#1874]
### Description of Issue

When entering _/job stats_ all the jobs are english. Translating them in the jobs files does not change anything.

### Version Information

```shell
Jobs: 5.2.4.6 MySQL
CMILib: 1.5.2.8
Server: 118 1.21.4-R0.1-Snapshot
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
e.g.
Brewer:
  fullname: Brauer
  shortname: Br
```

### Relevant Plugins

Vault 1.7.3
