### ISSUE TITLE
Problem with variable chat {jobs}

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#1877]
### Description of Issue

When I use the {jobs} in the EssentialsChat it's not displaying the jobs of the player.

### Version Information

```shell
5.2.4.6
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
gdm_survie16_fondateur:
       shout: '&7[&2Octopia&7]&r{STELYTEAM_PREFIX}{DISPLAYNAME} &f➢ &9{MESSAGE}'
       local: '{jobs}{STELYTEAM_PREFIX}{DISPLAYNAME} &f➢ &9{MESSAGE}'
```

### Relevant Plugins

Essentials 2.21.0
