### ISSUE TITLE
Issue with Mythic Mobs Compatibility

### ISSUE THREAD

**Issue by CptToastey** [Zrips/Jobs#1883]
### Description of Issue

Hello! 
I have an issue with jobs reborn. I am running version 5.2.4.6(CMI lib 1.5.3.5) and use Mythic Mobs on my server.

There is a job defined that uses the Mythic Mobs hook to award XP and currency when a mob is killed.
On initial start it doesn´t recognize a kill on a Mythic Mob. However when I reload Jobs, it works as expected.
Further research showed that jobs does not load the mythic mobs compatibility on first boot, but does when the plugin is reloaded. Hope this helps 

I appreciate the support regarding this matter. Thank you!
If I can help out with information or logs, please do let me know

### Version Information

```shell
Jobs: 5.2.4.5 MySQL
CMILib: 1.5.3.5
Server: 177 1.21.4-R0.1-Snapshot
Economy: Royale Economy Vault: 1.7.3-b131
```

### Errors

```shell

```

### Relevant Config Sections

```yaml
MMKill:
    # mob name
    PlainZombie:
      # base income
      income: 10.0
      # base experience
      experience: 10.0
      # base points
      points: 10.0
```

### Relevant Plugins

Mythic Mobs 5.8.1 Premium
