### ISSUE TITLE
Reassign function broken after restart

### ISSUE THREAD

**Issue by Serial1990** [Zrips/Jobs#1892]
### Description of Issue

I have to re-register the furnaces(and all others) every time I restart, 
even though I have Reassign: true in the config

No file is created where the Furnace(and all others) are saved...

I have delete the entire Jobs folder and create it new. Same problem.

### Version Information

```shell
5.2.5.0 -> 1.21.4
5.3.5.0 -> 1.21.5 (Test Server)
```

### Errors

```shell
No errors
```

### Relevant Config Sections

```yaml
ExploitProtections:
  Furnaces:
    # When enabled, players interacted furnaces will be saved into a file and will be reassigned after restart to keep giving out money
    # Players will no longer need to click on furnace to get paid from it after server restart
    Reassign: true
    # Defines max available furnaces each player can have to get paid from
    # This can be overridden with jobs.maxfurnaces.[amount] permission node
    MaxDefaultAvailable: 25
  BlastFurnaces:
    Reassign: true
    MaxDefaultAvailable: 25
  Smokers:
    Reassign: true
    MaxDefaultAvailable: 25
```

### Relevant Plugins

CMILib 1.5.2.9(1.5.4.1), Vault 1.7.3-b23, Paper#212v1.21.4(paper#18v1.21.5)
