### ISSUE TITLE
Important - Jobs archive data cleared after update

### ISSUE THREAD

**Issue by KermX** [Zrips/Jobs#1898]
### Description of Issue

After updating to 5.2.6.0 archived jobs data (jobs the player is no longer in) have their data cleared. If a player rejoins a job after leaving it they will be reset to 0. No data is lost and the issue is resolved by simply reverting the jobs version to 5.2.4.6. However, I believe this could result in duplicate data as a single user can have data for the same job multiple times.

### Version Information

```shell
Error Version: 5.2.6.0
Usable Version: 5.2.4.6

CMIlib Version: 1.5.4.2
```

### Errors

```shell
N/A, no errors are produced on server startup.
```

### Relevant Config Sections

```yaml
Users should not and do not lose any xp or levels when leaving a job. Their data just is not being loaded properly. 

old-job:
  level-loss-percentage: 0
  fix-at-max-level: true
  # Percentage to loose when leaving job at max level
  # Only works when fix-at-max-level is set to false
  level-loss-from-max-level: 0
```
