### ISSUE TITLE
Issues between Jobs and mcMMO

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [Zrips/Jobs#1908]
### Description of Issue

Using the following:
CMILIB 1.5.5.0
Jobs 5.2.6.1
mcMMO 2.2.039
on Paper 1.24.1 the following issue occurs:

I enabled support for mcMMO Treefeller, using this option:
      GlobalBlockTimer:
        Break:
          Use: true
          # Time in seconds. This can only be positive number and no higher than 60
          # This is only to prevent player from placing blocks into same place and getting paid once more
          Timer: 3

The message "You can earn money in xyz again" occurs when using Treefeller on larger trees such as 2x2 spruce, large jungle and dark oak. Chopping them manually works fine.
Using Treefeller on smaller trees the message does not appear, however you do not get paid for them either.

Setting it to 2, 1, 0.5 and 0 didn't help either, only disabling this option. I am not too sure how much this could be abused so I rather want to prevent doing that and also having to define 150 blocks manually in worst case.

### Version Information

```shell
https://prnt.sc/0CiQuN8HQ7IM
CMILIB 1.5.5.0
Jobs 5.2.6.1
mcMMO 2.2.039
on Paper 1.24.1
```

### Errors

```shell
No errors.
```

### Relevant Config Sections

```yaml
GlobalBlockTimer:
        Break:
          Use: true
          # Time in seconds. This can only be positive number and no higher than 60
          # This is only to prevent player from placing blocks into same place and getting paid once more
          Timer: 3
```

### Relevant Plugins

mcMMO 2.2.039
