### ISSUE TITLE
Smelt with Wet Sponge not working

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/Jobs#197]
Smelting Wet Sponge isn't paying out.

From jobConfig.yml
```
    Smelt:
      SPONGE-1:
        income: 0.08
        experience: 0.003
```

From ItemsList.yml
`  - '19:1 - Wet Sponge = sponge'`

Any reason why this is happening?
