### ISSUE TITLE
Enchantments are not recognised, showing as "None"

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/Jobs#208]
Since updating to the 1.13 version of the plugin, our Enchanter job has been rendered useless due to all enchantments not being recognised. 

[https://i.imgur.com/4G4qEw1.png](url)
[https://i.imgur.com/5c20lfL.png](url)

**Comment by montlikadani** [comment]
Please send the plugin version and the command you run.

**Comment by Flexxxxx** [comment]
**Cmi Version (using/cmi version):**
8.0.4.0
**Server Type (Spigot/Paperspigot/etc):**
Spigot
**Server Version (using /ver):**
1.13-RO,1-SNAPSHOT

**Comment by montlikadani** [comment]
Which command did you run then?

**Comment by montlikadani** [comment]
Which command did you run then?

**Comment by montlikadani** [comment]
@Flexxxxx 
Please update your software (Spigot) to the latest version.
The enchantments names working correctly:
![kep](https://user-images.githubusercontent.com/30026208/44004897-d03324d0-9e6a-11e8-8e4d-ff3637fb8e52.png)

**Comment by Flexxxxx** [comment]
But see for yourself, they aren't working correctly even in that picture. You have 6 Protections payouts, when there are 4 (although I'm unsure if your server allows enchanting of higher protections and the job accommodates that, although the protection at the bottom is lower than the one prior, so if that's protection 6, your pricing is wrong lol). Everything is Protection. Enchants in the jobsconfig that are definitely not Protection are displaying as Protection in-game.

**Comment by montlikadani** [comment]
You're right. I have not seen. :(
It may be confused with the other protection enchantments underneath it. For example, PROTECTION_EXPLOSIONS, PROTECTION_FALL etc.

**Comment by Flexxxxx** [comment]
Maybe, but that doesn't explain why it's showing Protection for Thorns, Efficiency, etc, etc, etc. Initially I figured 1.13 changed enchant names, but what we have in the config matches this: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html

¯\_(ツ)_/¯

**Comment by LogGits** [comment]
What does ur jobs enchanter configuration look like? Because this is working correctly for me.
Enchants look like:
```yaml
      PROTECTION_ENVIRONMENTAL-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      PROTECTION_ENVIRONMENTAL-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      PROTECTION_ENVIRONMENTAL-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      PROTECTION_ENVIRONMENTAL-4:
        income: 40.0
        points: 40.0
        experience: 40.0
```
