### ISSUE TITLE
SkeletonStray & ZombieHusk

### ISSUE THREAD

**Issue by weberlepecheur** [Zrips/Jobs#230]
Hi,

I report those two creatures don't gain any payments from the jobs for killing them, i just installed the plugin (which means i have the default jobConfig.yml) I just add the Stray and Husk with same gain from their parents (skeleton and zombie) but when I kill them, there nothing.

```
      STRAY:
        income: 10.0
        points: 10
        experience: 15
```

Spigot 1.12.2
Jobs 4.8.0
Vault 1.6.1
