### ISSUE TITLE
When a player level up, there is no message

### ISSUE THREAD

**Issue by Momonche** [Zrips/Jobs#242]
Hello,

When a player level up in is jobs, no message is displaying in the chat or in action bar.

Config:
```
ActionBars:
  Messages:
    EnabledByDefault: true

BossBar:
  Enabled: true
  Messages:
    EnabledByDefault: true
  ShowOnEachAction: false
  Timer: 6

ShowActionBars:
  OnTitleChange: true
  OnLevelChange: true
  OnEmptyServerAcount: true

ShowChatMessage:
  OnTitleChange: true
  OnLevelChange: true
  OnEmptyServerAcount: true
```
