### ISSUE TITLE
Chicken being detected wrongly

### ISSUE THREAD

**Issue by LogGits** [Zrips/Jobs#253]
In the hunter job i was doing some testing. 
Jobs is recognising Chicken as `RAW_CHICKEN`:
```yaml
      Chicken:
        income: 4.0
        points: 4.0
        experience: 5.0
```
to test this check out the action page or use the ingame editor to edit the hunter job. You can clearly see raw chicken. This could explain why killing chickens doesn't pay in the hunter job.
