### ISSUE TITLE
[Bug] Crops doesnt seem to give money or anything

### ISSUE THREAD

**Issue by Baktus79** [Zrips/Jobs#264]
I have just updated to the new Jobs 4.9.0, and it seems that crops wont work. It wont even display on the job information. Players wont get anything from breaking crops.
```
CROPS-7:
  income: 1.5
  points: 1.5
  experience: 3.0
```

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-368 (MC: 1.13.1)
