### ISSUE TITLE
Add enchant ids for Enchanted_Book material

### ISSUE THREAD

**Issue by montlikadani** [Zrips/Jobs#286]
Example:
```
VTrade:
  ENCHANTED_BOOK-1:
    income: 1.2
    ...
```
1 - Fire Protection
