### ISSUE TITLE
Add file to save block protections

### ISSUE THREAD

**Issue by montlikadani** [Zrips/Jobs#300]
[#post](https://www.spigotmc.org/threads/jobs-reborn.50989/page-229#post-3226019)
Configuration setting with comment (default):
```
ExploitProtections:
  General:
    # Save block protections to blockProtections.yml file?
    SaveDataToFile: false
```
More:
- Save file to add protects when reload & stop the server.
