### ISSUE TITLE
Shearing sheep does not work

### ISSUE THREAD

**Issue by Rakdos8** [Zrips/Jobs#326]
I've updated my jobConfig.yml file as follow:
```yaml
  Fermier:
    fullname: Fermier
    shortname: Fe
    description: Gagne de l'argent avec tes champs et tes animaux
    ChatColour: DARK_GREEN
    chat-display: full
    max-level: 200
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints-(basepoints*((numjobs-1) * 0.01))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) * 0.01))
    Gui:
      Id: 296
      Data: 0
    Shear:
      Red:
        income: 0.1
        points: 0.5
        experience: 0.5
      Orange:
        income: 0.1
        points: 0.5
        experience: 0.5
      Yellow:
        income: 0.1
        points: 0.5
        experience: 0.5
      Green:
        income: 0.1
        points: 0.5
        experience: 0.5
      Blue:
        income: 0.1
        points: 0.5
        experience: 0.5
      'Light Blue':
        income: 0.1
        points: 0.5
        experience: 0.5
      Magenta:
        income: 0.1
        points: 0.5
        experience: 0.5
      Pink:
        income: 0.1
        points: 0.5
        experience: 0.5
      WHITE_WOOL:
        income: 0.1
        points: 0.5
        experience: 0.5
      'Light Gray':
        income: 0.1
        points: 0.5
        experience: 0.5
      BLACK:
        income: 0.1
        points: 0.5
        experience: 0.5
      Brown:
        income: 0.1
        points: 0.5
        experience: 0.5
      Purple:
        income: 0.1
        points: 0.5
        experience: 0.5
      Cyan:
        income: 0.1
        points: 0.5
        experience: 0.5
      Gray:
        income: 0.1
        points: 0.5
        experience: 0.5
      'Lime Green':
        income: 0.1
        points: 0.5
        experience: 0.5
```
and the job is not getting anything when shearing on all of the given colors. As you can see on the configuration, I've either tried full case of the Color enum name `org.bukkit.Color` which is the return type of `sheep.getColor()` (BLAC) and also the block being retrieved (WHITE_WOOL).
Job config example: https://github.com/Zrips/Jobs/blob/master/src/main/resources/jobConfig.yml#L329

I'm using the latest Jobs version as well and the latest Spigot one also (1.13.2 19c3c5a-5932f8a).

I've read some of the line code and followed the case:
1. Listener shear: https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/listeners/JobsPaymentListener.java#L301
2. Retrieve JobInfo: https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/Jobs.java#L945 (and here I suppose it returns `null`)
3. The action name is the sheep's color but it's being compared with the JobInfo's name: https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/container/Job.java#L229

Hope it helps.
