### ISSUE TITLE
Command on level not working

### ISSUE THREAD

**Issue by Endothelium** [Zrips/Jobs#350]
Hello,

I cant use this feature 

```
commands:
    kit:
      command:
      - lp user [player] permission add wtk.job.bucheron10
      - msg [player] !Permission bucheron10 
      levelFrom: 1
      levelUntil: 10
```

When i level from 1 to 2, the commands are not performed.

I am on spigot 1.13.2

**Comment by montlikadani** [comment]
This works properly, only you have a configuration error because it has more space than it needed.
The correct:
```
commands:
  kit:
    command:
    - lp user [player] permission add wtk.job.bucheron10
    - msg [player] !Permission bucheron10 
    levelFrom: 1
    levelUntil: 10
```

**Comment by Endothelium** [comment]
There is an indentation problem when i pasted my config here, but actually the indentation is good in my file and is exactely the same as  you.

**Comment by montlikadani** [comment]
This working for me correctly when I reach the 2 level from 1 and gets the commands. Make sure that the commands you set are working even if you type them in the game.

**Comment by Endothelium** [comment]
Hello,

Yeah sorry, it does work, it was because i was using alias command instead the real command.

Another question, does this seems correct for you, except indentation

```
permissions:
    wtk.job.bucheron:
      value: true
      level: 0
    wtk.job.bucheron10:
      value: true
      level: 10
```

Because i have trouble to make this work too.

Thanks
