### ISSUE TITLE
Quest Progress Bar Not Working?

### ISSUE THREAD

**Issue by Ryukenstein** [Zrips/Jobs#390]
I think Progress Bar is not working **Sometimes** when showing quests available it just look white all the time when i type /jobs quests

it looks like:
*ALL WHITE* |||||||||||||||||||||||||||||||||||||||| Kill Zombies 12/25 *ALL WHITE*
Instead of 
**Green|||||||||||||||||||||||/Green**|||||||||||||||| Kill Zombies 12/25

Msg Config is OK in commands.quests.output.questLine. it looks like

`questLine: '[progress] &7[questName] &f[done]&7/&8[required]'`

Also it's all white, quest name color and numbers looks white.
One of my Example Quests:
```
      miner3:
        Name: "&8&lFull &7&lMetal &f&lMiner"
        Action: Break
        Target: "iron_ore"
        Amount: 100
        RewardCommands:
        - "eco give [playerName] 1500"
        - "msg [playerName] Quest Completed!!"
        RewardDesc:
        - "&5&lBreak 100 Iron Ore"
        - "&5&lEasy Task for a Miner"
        - "&5&lCheers Miner!!"
        - "&5&lYou will get &e&l1500 Money"      
        Chance: 30
        toLevel: 200
        fromLevel: 2
```
The mouse Hover showing description Works well, it gets colorcodes.
Using latest version 4.10.3. in latest spigot 1.13.2 to date.
No errors in the console so far.

PD: THIS HAPPENS ONLY WITH SOME PLAYERS.
