### ISSUE TITLE
TranslatableWords isnt working

### ISSUE THREAD

**Issue by LogGits** [Zrips/Jobs#391]
https://gyazo.com/9ce62781f182df9c3e96e98cd25e527a

The issue is that it is showing stuff like:
```
THORNS:1
Protection fall:3
```

Basically default spigot enchantment names, instead of the regular Minecraft names provided in translatablewords.yml.

Just to be abundantly clear, I have the CustomNames set to true.

**Comment by montlikadani** [comment]
What server version and the server software are you using?

**Comment by LogGits** [comment]
@montlikadani paper 1.13.2 build 591, jobs 4.10.3

**Comment by montlikadani** [comment]
Do you send the Enchanter job parts?

**Comment by LogGits** [comment]
```
  Enchanter:
    fullname: Enchanter
    shortname: E
    description: Earn money by enchanting weapons.
    ChatColour: DARK_BLUE
    chat-display: full
    max-level: 200
    #slots: 10
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    Gui:
      Item: ENCHANTED_BOOK
    Enchant:
      WOOD_SWORD:
        income: 1.5
        points: 1.5
        experience: 3.0
      LEATHER_BOOTS:
        income: 1.0
        points: 1.0
        experience: 6.0
      LEATHER_CHESTPLATE:
        income: 2.0
        points: 2.0
        experience: 6.0
      LEATHER_HELMET:
        income: 1.0
        points: 1.0
        experience: 6.0
      LEATHER_LEGGINGS:
        income: 2.0
        points: 2.0
        experience: 6.0
      IRON_SWORD:
        income: 3.0
        points: 3.0
        experience: 6.0
      IRON_BOOTS:
        income: 2.5
        points: 2.5
        experience: 9.0
      IRON_CHESTPLATE:
        income: 4.5
        points: 4.5
        experience: 9.0
      IRON_HELMET:
        income: 2.5
        points: 2.5
        experience: 9.0
      IRON_LEGGINGS:
        income: 4.5
        points: 4.5
        experience: 9.0
      GOLD_SWORD:
        income: 4.5
        points: 4.5
        experience: 15.0
      GOLD_BOOTS:
        income: 2.5
        points: 2.5
        experience: 15.0
      GOLD_CHESTPLATE:
        income: 5.5
        points: 5.5
        experience: 15.0
      GOLD_HELMET:
        income: 2.5
        points: 2.5
        experience: 15.0
      GOLD_LEGGINGS:
        income: 5.5
        points: 5.5
        experience: 15.0
      DIAMOND_SWORD:
        income: 9.0
        points: 9.0
        experience: 30.0
      DIAMOND_SPADE:
        income: 5.0
        points: 5.0
        experience: 30.0
      DIAMOND_PICKAXE:
        income: 10.0
        points: 10.0
        experience: 30.0
      DIAMOND_AXE:
        income: 10.0
        points: 10.0
        experience: 30.0
      DIAMOND_HELMET:
        income: 6.0
        points: 6.0
        experience: 30.0
      DIAMOND_CHESTPLATE:
        income: 12.0
        points: 12.0
        experience: 50.0
      DIAMOND_LEGGINGS:
        income: 12.0
        points: 12.0
        experience: 50.0
      DIAMOND_BOOTS:
        income: 6.0
        points: 6.0
        experience: 30.0
      #Power
      ARROW_DAMAGE-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      ARROW_DAMAGE-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      ARROW_DAMAGE-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      ARROW_DAMAGE-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      ARROW_DAMAGE-5:
        income: 50.0
        points: 50.0
        experience: 50.0
      #Flame
      ARROW_FIRE:
        income: 10.0
        points: 10.0
        experience: 30.0
      #Infinity
      ARROW_INFINITE:
        income: 20.0
        points: 20.0
        experience: 50.0
      #Punch
      ARROW_KNOCKBACK-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      ARROW_KNOCKBACK-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      #Sharpness
      DAMAGE_ALL-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      DAMAGE_ALL-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      DAMAGE_ALL-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      DAMAGE_ALL-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      DAMAGE_ALL-5:
        income: 50.0
        points: 50.0
        experience: 50.0
      #Bane of Arthropods
      DAMAGE_ARTHROPODS-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      DAMAGE_ARTHROPODS-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      DAMAGE_ARTHROPODS-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      DAMAGE_ARTHROPODS-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      DAMAGE_ARTHROPODS-5:
        income: 50.0
        points: 50.0
        experience: 50.0
      #Smite
      DAMAGE_UNDEAD-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      DAMAGE_UNDEAD-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      DAMAGE_UNDEAD-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      DAMAGE_UNDEAD-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      DAMAGE_UNDEAD-5:
        income: 50.0
        points: 50.0
        experience: 50.0
      #Depth Strider
      DEPTH_STRIDER-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      DEPTH_STRIDER-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      DEPTH_STRIDER-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      #Efficiency
      DIG_SPEED-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      DIG_SPEED-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      DIG_SPEED-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      DIG_SPEED-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      DIG_SPEED-5:
        income: 50.0
        points: 50.0
        experience: 50.0
      #Unbreaking
      DURABILITY-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      DURABILITY-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      DURABILITY-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      #Fire Aspect
      FIRE_ASPECT-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      FIRE_ASPECT-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      #Knockback
      KNOCKBACK-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      KNOCKBACK-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      #Fortune
      LOOT_BONUS_BLOCKS-1:
        income: 20.0
        points: 20.0
        experience: 100.0
      LOOT_BONUS_BLOCKS-2:
        income: 40.0
        points: 40.0
        experience: 200.0
      LOOT_BONUS_BLOCKS-3:
        income: 80.0
        points: 80.0
        experience: 300.0
      #Looting
      LOOT_BONUS_MOBS-1:
        income: 10.0
        points: 10.0
        experience: 20.0
      LOOT_BONUS_MOBS-2:
        income: 20.0
        points: 20.0
        experience: 40.0
      LOOT_BONUS_MOBS-3:
        income: 30.0
        points: 30.0
        experience: 60.0
      #Luck of the Sea
      LUCK-1:
        income: 15.0
        points: 15.0
        experience: 10.0
      LUCK-2:
        income: 25.0
        points: 25.0
        experience: 20.0
      LUCK-3:
        income: 35.0
        points: 35.0
        experience: 30.0
      #Lure
      LURE-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      LURE-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      LURE-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      #Respiration
      OXYGEN-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      OXYGEN-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      OXYGEN-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      #Protection
      PROTECTION_ENVIRONMENTAL-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      PROTECTION_ENVIRONMENTAL-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      PROTECTION_ENVIRONMENTAL-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      PROTECTION_ENVIRONMENTAL-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      #Blast Protection
      PROTECTION_EXPLOSIONS-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      PROTECTION_EXPLOSIONS-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      PROTECTION_EXPLOSIONS-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      PROTECTION_EXPLOSIONS-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      #Feather Falling
      PROTECTION_FALL-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      PROTECTION_FALL-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      PROTECTION_FALL-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      PROTECTION_FALL-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      #Fire Protection
      PROTECTION_FIRE-1:
        income: 5.0
        points: 5.0
        experience: 10.0
      PROTECTION_FIRE-2:
        income: 10.0
        points: 10.0
        experience: 20.0
      PROTECTION_FIRE-3:
        income: 20.0
        points: 20.0
        experience: 30.0
      PROTECTION_FIRE-4:
        income: 30.0
        points: 30.0
        experience: 40.0
      #Projectile Protection
      PROTECTION_PROJECTILE-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      PROTECTION_PROJECTILE-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      PROTECTION_PROJECTILE-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      PROTECTION_PROJECTILE-4:
        income: 40.0
        points: 40.0
        experience: 40.0
      #Silk Touch
      SILK_TOUCH:
        income: 100.0
        points: 100.0
        experience: 300.0
      #Thorns
      THORNS-1:
        income: 10.0
        points: 10.0
        experience: 10.0
      THORNS-2:
        income: 20.0
        points: 20.0
        experience: 20.0
      THORNS-3:
        income: 30.0
        points: 30.0
        experience: 30.0
      #Aqua Affinity
      WATER_WORKER:
        income: 30.0
        points: 30.0
        experience: 100.0
      #1.13 enchantments
      #Channeling
      channeling:
        income: 10
        points: 10
        experience: 10
      #Curse of Binding
      binding_curse:
        income: 5
        points: 5
        experience: 5
      #Curse of Vanishing
      vanishing_curse:
        income: 5
        points: 5
        experience: 5
      #Frost Walker 2
      frost_walker-1:
        income: 10
        points: 10
        experience: 10
      frost_walker-2:
        income: 20
        points: 20
        experience: 20
      #Impaling 5
      impaling-1:
        income: 10
        points: 10
        experience: 10
      impaling-2:
        income: 20
        points: 20
        experience: 20
      impaling-3:
        income: 30
        points: 30
        experience: 30
      impaling-4:
        income: 40
        points: 40
        experience: 40
      impaling-5:
        income: 50
        points: 50
        experience: 50
      #Loyalty 3
      loyalty-1:
        income: 10
        points: 10
        experience: 10
      loyalty-2:
        income: 20
        points: 20
        experience: 20
      loyalty-3:
        income: 30
        points: 30
        experience: 30
      #Mending
      mending:
        income: 10
        points: 10
        experience: 10
      #Riptide
      riptide:
        income: 20
        points: 20
        experience: 20
      #Sweeping Edge
      sweeping_edge:
        income: 15
        points: 15
        experience: 15
      #1.14 enchantments (coming soon-ish, hopefully)
      #Multishot
      #Piercing
      #Quick Charge
```

**Comment by montlikadani** [comment]
I've reviewed the video more thoroughly, but it's not an error, because we use the custom enchant names if the **UseCustomNames** option is enabled. I don't know what's the problem with this?

**Comment by LogGits** [comment]
UseCustomNames is enabled, and it doesn't use the translatable words:
```yaml
EnchantList:
  PROTECTION_FIRE: Fire Protection
  DAMAGE_ALL: Sharpness
  ARROW_FIRE: Flame
  WATER_WORKER: Water worker
  ARROW_KNOCKBACK: Punch
  LOYALTY: Loyalty
  DEPTH_STRIDER: Depth Strider
  VANISHING_CURSE: Vanishing curse
  DURABILITY: Unbreaking
  KNOCKBACK: Knockback
  LUCK: Luck of the Sea
  BINDING_CURSE: Binding curse
  LOOT_BONUS_BLOCKS: Fortune
  PROTECTION_ENVIRONMENTAL: Protection
  DIG_SPEED: Aqua Affinity
  MENDING: Mending
  FROST_WALKER: Frost Walker
  LURE: Lure
  LOOT_BONUS_MOBS: Looting
  PROTECTION_EXPLOSIONS: Blast Protection
  DAMAGE_UNDEAD: Smite
  FIRE_ASPECT: Fire Aspect
  CHANNELING: Channeling
  SWEEPING_EDGE: Sweeping Edge
  THORNS: Thorns
  DAMAGE_ARTHROPODS: Bane of Arthropods
  OXYGEN: Respiration
  RIPTIDE: Riptide
  SILK_TOUCH: Silk Touch
  PROTECTION_PROJECTILE: Protection projectile
  IMPALING: Impaling
  PROTECTION_FALL: Feather Falling
  ARROW_DAMAGE: Power
  ARROW_INFINITE: Infinity
```
