### ISSUE TITLE
McMMO Overhaul abilities are paying 100%

### ISSUE THREAD

**Issue by NyannyWu** [Zrips/Jobs#401]
TreeFeller, SuprBreaker, GigaDrill, any ability of McMMO are paying 100% its price no matter the config with the new McMMO, it destroying my economy.

Spigot 1.13.2
McMMO 2.1.44

**Comment by montlikadani** [comment]
Try with installing the dev. version from [Releases](https://github.com/Zrips/Jobs/releases) tab.

**Comment by NyannyWu** [comment]
I'm still getting paid 100%

```
  McMMO:
    # Players will get part of money from cutting trees with treefeller ability enabled.
    # 0.2 means 20% of original price
    TreeFellerMultiplier: 0.1
    # Players will get part of money from braking blocks with gigaDrill ability enabled.
    # 0.2 means 20% of original price
    gigaDrillMultiplier: 0.1
    # Players will get part of money from braking blocks with super breaker ability enabled.
    # 0.2 means 20% of original price
    superBreakerMultiplier: 0.1
  # MythicMobs plugin support
  # Disable if you having issues with it or using old version
```
