### ISSUE TITLE
Quests with multiple targets only count last target in list

### ISSUE THREAD

**Issue by Lunna123** [Zrips/Jobs#408]
Server version: Paper-620 (MC: 1.13.2)
Plugin version: 4.10.3

As explained in the title, quests with multiple targets only count the last target in the list. I tested it using the quest provided in jobConfig.yml:

```      
      4:
        Name: "Strip logs"
        Action: StripLogs
        Target:
        - stripped_birch_log
        - stripped_acacia_log
        Amount: 50
        RewardCommands:
        - "msg [playerName] Completed quest!"
        RewardDesc:
        - "Strip 50 birch and acacia logs!"
```

In the above example, it only counts (i.e. progress counter only increases) when stripping acacia logs, not when stripping birch logs. I also tested it by switching the order of the logs in the list like so:

```      
      5:
        Name: "Strip logs"
        Action: StripLogs
        Target:
        - stripped_acacia_log
        - stripped_birch_log
        Amount: 50
        RewardCommands:
        - "msg [playerName] Completed quest!"
        RewardDesc:
        - "Strip 50 birch and acacia logs!"
```

And in the above scenario, it only counted stripping birch logs and not acacia logs.

I also tested it using my own multiple target quests and the same behaviour occurs regardless of the number of items in the list. 

Edit: Progress also doesn't seem to go past 1, and if you strip the log on the list that doesn't count, progress is reset back to 0.
