### ISSUE TITLE
Restricted Areas don't work

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#411]
The restricted regions do not work. You can create them, but the job earnings are neither reduced nor increased. So nothing is happening. I have tested both the manual entry and the worldguard integration.

Paper 1.13.2 - 622
Jobs 4.11.1

```
Guardianfarm:
  world: Abbau
  multiplier: 4
  point1:
    x: -8433
    y: 0
    z: 505
  point2:
    x: -8360
    y: 150
    z: 583
```
```
  prisma:
    multiplier: -1.0
    WG: true
```
`   PlaceAndBreakProtection: true`
