### ISSUE TITLE
No rewards for the Zombie Pigman

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#420]
Since the update to 4.11.1 you are no longer paid for killing a zombie pigman. It worked fine on previous versions. If you add the value and reloaded the plugin the value will not be added. If you restart the server you will be paid for pigs instead of zombie pigman. There are no errors in the log. Every other reward in the same section works and has worked fine, so there is no problem with the general setup!

config:
```
    Kill:
      PIG_ZOMBIE:
        income: 25.52
        experience: 25.52
```

Paper 1.13.2 - 622
Jobs 4.11.1
