### ISSUE TITLE
McMMO and Hunter not getting paid

### ISSUE THREAD

**Issue by StpNex** [Zrips/Jobs#429]
Players complain that they dont get paid from mobs.

If  mobs die 1 hit it works sometimes but, if they get any effects from the /swords /axes abilities, they wont get paid at all, and it's very annoying as they get punished for levling mcmmo.

I didnt test all mcmmo abilities, but i guess all abilities that affect mobs will conflict.

I use Jobs Reborn 4.11.1, paper 1.13.2,
McMMO 2.1.62

**Comment by Zrips** [comment]
generalConfig 
```
    MonsterDamage:
      # This section controls how much damage player should do to monster for player to get paid
      # This prevents from killing monsters in one hit when they suffer in example fall damage
      Use: false
      Percentage: 60
```
Keep this at false or lower percentage. This is protection from players creating mob farms where they can one hit them after they suffer enough damage from other sources, like suffocation or fall damage. This is why some of the monsters doesn't pay out if they suffered more damage from effects then from players hands.
