### ISSUE TITLE
[Support] Invalid block type 

### ISSUE THREAD

**Issue by mrfloris** [Zrips/Jobs#446]
```
[13:14:33 WARN]: [Jobs] Job Miner has an invalid Break type property: NETHER_BRICK (nether_brick)! Material must be a block!
[13:14:33 WARN]: [Jobs] Job Builder has an invalid Place type property: NETHER_BRICK (nether_brick)! Material must be a block!
```
```
>ver Jobs
[14:10:57 INFO]: Jobs version 4.12.0
[14:10:57 INFO]: Jobs Plugin for the BukkitAPI
[14:10:57 INFO]: Website: https://www.spigotmc.org/resources/4216/
[14:10:57 INFO]: Author: phrstbrn
>ver
[14:10:57 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[14:10:57 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
>
```
```
  Miner:
    fullname: Miner
    shortname: M
    description: Earns money mining minerals and ores.
    ChatColour: DARK_GRAY
    chat-display: full
    max-level: 200
    #slots: 10
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    Gui:
      Id: 270
      Data: 0
    TNTBreak:
      stone:
        income: 0.25
        points: 0.25
        experience: 0.5
      granite:
        income: 0.25
        points: 0.25
        experience: 0.5
      diorite:
        income: 0.25
        points: 0.25
        experience: 0.5
      andesite:
        income: 0.25
        points: 0.25
        experience: 0.5
    Break:
      #new 1.13 blocks (some changed blocks are below
      tube_coral_block:
        income: 2
        points: 2
        experience: 3
      brain_coral_block:
        income: 2
        points: 2
        experience: 3
      bubble_coral_block:
        income: 2
        points: 2
        experience: 3
      fire_coral_block:
        income: 2
        points: 2
        experience: 3
      horn_coral_block:
        income: 2
        points: 2
        experience: 3     
      #origial blocks 
      andesite:
        income: 1
        points: 1
        experience: 1
      stone:
        income: 1
        points: 1
        experience: 1
      granite:
        income: 1
        points: 1
        experience: 1
      diorite:
        income: 1
        points: 1
        experience: 1
      sandstone:
        income: 0.15
        points: 0.15
        experience: 0.2
      chiseled_sandstone:
        income: 0.15
        points: 0.15
        experience: 0.2
      cut_sandstone:
        income: 0.15
        points: 0.15
        experience: 0.2
      coal_ore:
        income: 3
        points: 2
        experience: 2
      redstone_ore:
        income: 2.5
        points: 2
        experience: 2
      iron_ore:
        income: 3.5
        points: 3
        experience: 2
      gold_ore:
        income: 5
        points: 4
        experience: 2
      lapis_ore:
        income: 7.5
        points: 6
        experience: 2
      diamond_ore:
        income: 10
        points: 10
        experience: 10
      emerald_ore:
        income: 15
        points: 15
        experience: 30
      nether_quartz_ore:
        income: 2.5
        points: 2.5
        experience: 2.5
      obsidian:
        income: 5
        points: 5
        experience: 5
      cobblestone_wall:
        income: 2.5
        points: 2.5
        experience: 2.5
      mossy_cobblestone_wall:
        income: 2.5
        points: 2.5
        experience: 2.5
      nether_brick:
        income: 1.0
        points: 1
        experience: 1.0
      nether_brick_stairs:
        income: 3
        points: 3
        experience: 3
      nether_brick_fence:
        income: 1
        points: 1
        experience: 1
      netherrack:
        income: 0.1
        points: 0.1
        experience: 0.1
      prismarine:
        income: 2.5
        points: 2.5
        experience: 2.5
      prismarine_bricks:
        income: 2.5
        points: 2.5
        experience: 2.5
      dark_prismarine:
        income: 2.5
        points: 2.5
        experience: 2.5
    Place:
      rail:
        income: 2.0
        points: 2.0
        experience: 2.0
      iron_ore:
        income: -5.0
        points: -5
        experience: -5.0
      gold_ore:
        income: -6.0
        points: -6
        experience: -6.0
      diamond_ore:
        income: -10.0
        points: -10
        experience: -10.0
      emerald_ore:
        income: -15
        points: -15
        experience: -30
    Kill:
      Player:
        income: 7.5
        points: 7.5
        experience: 7.5
```

What do I change to WHAT exactly ?

Because no matter what I provide, it always complaints.
