### ISSUE TITLE
[Question] Paying Custom CMI Recipes

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#458]
Hejo,
it is possible to reward custom block, furnance or brewing recipes from CMI in jobs? I have tried it this way:
```
    Craft:
      '!Test':
        income: 1
        points: 2
        experience: 4
```
But the item is not recognized. Am I doing something wrong or is this a bug or is it more of a feature request? And if it is a feature request, should I create a ticket under Jobs or under CMI?

Jobs: 4.12.0
CMI: 8.6.5.0
Paper 1.13.2 - 632
