### ISSUE TITLE
Cod & nautilus shell isn't recognized by the plugin

### ISSUE THREAD

**Issue by Daxxas** [Zrips/Jobs#459]
***Description of issue:**
Cod & Nautilus shell are considered as "AIR" in the /jobs info
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Fish:
      PufferFish:
        income: 5
        experience: 34
      Salmon:
        income: 5
        experience: 34
      Cod:
        income: 5
        experience: 34
      TropicalFish:
        income: 5
        experience: 34
      NAUTILUS_SHELL:
        income: 6
        experience: 40
      ENCHANTED_BOOK:
        income: 6
        experience: 40
      NAME_TAG:
        income: 6
        experience: 40
```

---

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** 
[17:50:06 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[17:50:06 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
