### ISSUE TITLE
Villager Emerald Trading Bug

### ISSUE THREAD

**Issue by FeroxDrood** [Zrips/Jobs#474]
***Description of issue:**
When you give a villager an emerald for e.g. lapis you do not get paid even though it is specified in the config.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  VillagerT:
    fullname: VILLAGERTRADER
    shortname: VT
    description: '&b» &6The Art Of Marketing...'
    ChatColour: GREEN
    chat-display: full
    max-level: 500
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    Gui:
      Item: EMERALD
    VTrade:
      emerald:
        income: 15.0
        points: 15.0
        experience: 15.0
```

---

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.13.2 build #637
