### ISSUE TITLE
Entity Cat appears as Vindicator

### ISSUE THREAD

**Issue by Seeroh** [Zrips/Jobs#480]
When using entity `Cat` as a payment method, it shows up as `Vindicator`. For instance, I have Breed and Tame payments for `Cat`, and both show `Vindicator` instead.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    Breed:
      Cat:
        income: 1.00
        experience: 1.00
    Tame:
      Cat:
        income: 1.00
        experience: 1.00
```

In TranslatableWords, Cat should be entity 75, but it doesn't appear at all.

(Also, CMI doesn't work with Cat, either. If you try and use spawnmob to summon a cat, it summons a Vindicator instead)

---

**Server Type (Spigot/Paperspigot/etc):** 

`Paper`

**Server Version (using `/ver`):** 

`Paper version git-Paper-126 (MC: 1.14.3)`
