### ISSUE TITLE
Break Melon doesn't work

### ISSUE THREAD

**Issue by PackCraft** [Zrips/Jobs#481]
***Description of issue: In farmer jobs the melon doesn't work in break**

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## 
      MELON_BLOCK:
        income: 2
        points: 2
        experience: 2 ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): 1.14.3**
