### ISSUE TITLE
Enchanted Items in Jobs Shop Not Enchanted

### ISSUE THREAD

**Issue by mmagoo13** [Zrips/Jobs#482]
***Description of issue:**
If buying an enchanted book from the points shop you are given a book with no enchantment

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## Items:
  UnberakEnchantBook:
    Price: 5000.0
    Icon:
      Id: enchanted_book
      Name: "&eEnchant book"
      Lore:
      - "&eContains Unbreaking 5 enchant"
      HideWithoutPermission: false
    RequiredPermission:
    PerformCommands:
    - "msg &eThanks [player] for buying this book!"
    GiveItems:
      Book:
        Id: enchanted_book
        Enchants:
        - UNBREAKING=5##
#####################################
```

---

**Server Type (Paperspigot):** 

**Server Version (git-Paper-123):** 
**MC Server Version (1.14.3):** 
![Screenshot_1](https://user-images.githubusercontent.com/23560791/61345310-87ab0f80-a822-11e9-8a98-cb69d0ec9f09.png)
![Screenshot_2](https://user-images.githubusercontent.com/23560791/61345317-8aa60000-a822-11e9-931f-eb78c3574012.png)
