### ISSUE TITLE
Brewing does not get paid when removing potions with hoppers

### ISSUE THREAD

**Issue by kaniesha** [Zrips/Jobs#497]
***Description of issue:**

When the following settings are set to true, players using furnaces still get paid when using hoppers to remove smelted/cooked items into chests. For brewing stands, players using hoppers to remove completed potions into chests do not get paid.

I would prefer if both instances got paid when items are **moved out** with furnaces

  Smelt:
    # Prevent payments when hoppers moving items into furnace
    # Player will not get paid, but items will be smelted
    PreventHopperFillUps: true
  Brew:
    PreventBrewingStandFillUps: true

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Smelt:
    # Prevent payments when hoppers moving items into furnace
    # Player will not get paid, but items will be smelted
    PreventHopperFillUps: true
  Brew:
    PreventBrewingStandFillUps: true
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper spigot

**Server Version (using `/ver`):** 
paper 158. Minecraft 1.14.4
