### ISSUE TITLE
Dark Oak Log showing as Acacia in the job info gui

### ISSUE THREAD

**Issue by Frogperson** [Zrips/Jobs#516]
***Description of issue:**

The title pretty much says it all. Dark oak logs (162:1) are incorrectly showing up as acacia logs on Spigot 1.12.2. Here's an example of what I mean: https://i.imgur.com/7BvlUT1.png

---

**CONFIG SECTION:**
```
    Break:
      17-0:
        income: 1.0
        points: 1.0
        experience: 1.0
      17-1:
        income: 1.0
        points: 1.0
        experience: 1.0
      17-2:
        income: 1.0
        points: 1.0
        experience: 1.0
      17-3:
        income: 1.0
        points: 1.0
        experience: 1.0
      162-0:
        income: 1.0
        points: 1.0
        experience: 1.0
      162-1:
        income: 1.0
        points: 1.0
        experience: 1.0
```

---

**Server Type:** 
Spigot

**Server Version:** 
1.12.2
