### ISSUE TITLE
Jobs quests completion & refresh issue/bug

### ISSUE THREAD

**Issue by MrTrinax** [Zrips/Jobs#522]
***Description of issue:**
Job quests get marked as completed for some players when the player begins it.
Example: A quest where the player needs to break 200 stones will get marked as completed and reward the player when 1 stone is broken.

For some players the quests doesn't refresh. This seems to mostly only affect the players who have the above issue as well.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
    Quests:
      1:
        Name: "Stone Miner"
        Objectives:
        - Break;stone;200
        - Break;iron_ore;20
        - Break;coal_ore;50
        RewardCommands:
        - "eco give [playerName] 75"
        - "msg [playerName] daily quest completed!"
        - "msg [playerName] Mine 200 Stone ✓"
        - "msg [playerName] Mine 20 Iron ores ✓"
        - "msg [playerName] Mine 50 Coal ores ✓"
        - "msg [playerName] Reward: $75"
        RewardDesc:
        - "&a&lReward: &a$75"
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot (MC: 1.14.4)

**Server Version (using `/ver`):** 
Paper version git-Paper-186 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
