### ISSUE TITLE
Place action isn't working with quests.

### ISSUE THREAD

**Issue by UnioDex** [Zrips/Jobs#549]
***Description of issue:**
```
      1:
        Name: "Daily Quest"
        Objectives:
          - Place;35-0;20
          - Place;35-1;20
          - Place;35-2;20
          - Place;35-3;20
          - Place;35-4;20
          - Place;35-5;20
          - Place;35-6;20
          - Place;35-7;20
          - Place;35-8;20
          - Place;35-9;20
          - Place;35-10;20
          - Place;35-11;20
          - Place;35-12;20
          - Place;35-13;20
          - Place;35-14;20
          - Place;35-15;20
        RewardCommands:
          - "give [playerName] diamond 1"
        RewardDesc:
          - "Test"
```

I want to reward players who placed 20 wool of each colors. But the config snippet I provided is not working.

I also tried:
- Place;WOOL;20
- Place;WOOL-1;20
- Place;WHITE_WOOL;20
- Place;WHITE_WOOL-1;20
- Place;GRAY_WOOL;20 (and other colored wools)

But none of these worked. At first I thought it's a problem with wools. I tried to change it with STONE but it also didn't work. So I don't think place action is working with quests. It's working with job rewards. I mean I can earn money with placing wools but quests didn't count it.

Version: Paper 1.12
Jobs Version: I just built it with latest commit: 9a73f1eb0d40126bea1b49f57dd4673ee6d1e6be
