### ISSUE TITLE
Hunter: Missing mobs

### ISSUE THREAD

**Issue by slankford** [Zrips/Jobs#553]
***Description of issue:**

The three following mobs are missing from the Hunter job:
```
  slime
  magma_cube
  wither_skeleton
```

Maybe slime and magma slime were left out intentionally, but it's definitely a bug to not be paid for wither_skeleton. I would make a pull request to add these mobs, but I was wondering if there needed to be a discussion on reward balancing. Slimes give you the reward for each slime and slime child killed, so $0.50 seemed fair to me. My suggestion for wither skeleton is $15.

Suggested additions to the jobs config file under hunter kills:
```
      wither_skeleton:
        income: 15.0
        points: 15
        experience: 15.0
      slime:
        income: 0.5
        points: 0.5
        experience: 0.5
      magma_cube:
        income: 0.5
        points: 0.5
        experience: 0.5
```
