### ISSUE TITLE
Cave spider bug

### ISSUE THREAD

**Issue by Elric02** [Zrips/Jobs#561]
***Description of issue:**

I can't make the cave spiders worth some money and xp, when I kill them I gain nothing. Every other mob is fine.
I tried to put CAVESPIDER, CAVE_SPIDER, Cave_spider, Cavespider, cavespider, CaveSpider and Cave_Spider, nothing works.
There's no error on the console, neither when I reload the plugin nor when I kill a cave spider.

**CONFIG SECTION:**
```
    Kill:
      CAVE_SPIDER:
        income: 12
        points: 20
        experience: 30
```

---

**Server Type (Spigot/Paperspigot/etc):** 

Spigot

**Server Version (using `/ver`):** 

1.12.2
