### ISSUE TITLE
Drink Job Action Doesn't Work On Version 4.13.1

### ISSUE THREAD

**Issue by DC-FLASH** [Zrips/Jobs#568]
***Description of issue:**

The action "Drink", which is meant to payout to the worker for drinking potions, does not work, there is no errors, but upon clicking the job to view the actions in the GUI it is blank. I will send a copy of the config concerning the issue to show what IDs I used if that is what the issue is, also I have milk and water listed in them I'm not sure if there even is support for them but if there isn't I would love to see it implemented if that is not a problem.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Alcoholic:
    fullname: Alcoholic
    shortname: Ac
    description: Earns money from drinking potions.
    ChatColour: LIGHT_PURPLE
    BossBarColour: LIGHT_PURPLE
    chat-display: full
    max-level: 200
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    maxDailyQuests: 1
    Quests:
      Alcoholic1:
        Name: "Put it on my tab."
        Objectives:
        - Drink;swiftness_1;1
        RewardCommands:
        - "eco give [playerName] 100"
        - "msg [playerName] Quest Completed!"
        RewardDesc:
        - "Drink a swiftness 1 potion and get money"
        - "Get 100 for this!"
    Gui:
      Item: dragon_breath
    Drink:
      absorption_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      absorption_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      blindness_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      blindness_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      fire_resistance_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      fire_resistance_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      harming_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      harming_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      haste_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      haste_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      healing_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      healing_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      health_boost_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      health_boost_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      hunger_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      hunger_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      invisibility_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      invisibility_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      jump_boost_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      jump_boost_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      milk:
        income: 1.0
        points: 1.0
        experience: 1.0
      mining_fatigue_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      mining_fatigue_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      nausea_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      nausea_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      night_vision_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      poison_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      poison_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      regeneration_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      regeneration_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      resistance_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      resistance_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      saturation_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      slowness_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      slowness_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      strength_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      strength_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      swiftness_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      swiftness_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      water:
        income: 1.0
        points: 1.0
        experience: 1.0
      water_breathing_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      weakness_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      weakness_2:
        income: 1.0
        points: 1.0
        experience: 1.0
      wither_1:
        income: 1.0
        points: 1.0
        experience: 1.0
      wither_2:
        income: 1.0
        points: 1.0
        experience: 1.0
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot
**Server Version (using `/ver`):** 
1.14.4
