### ISSUE TITLE
Shearing Light Blue Dyed Sheep Doesn't Work In Version 4.13.1

### ISSUE THREAD

**Issue by DC-FLASH** [Zrips/Jobs#569]
***Description of issue:**

You don't get paid out for shearing light blue dyed sheep, it displays as "Navy" in the GUI as well. I tried using Light_Blue and Navy and neither work, all other variants of sheep payout.

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    Shear:
      Light_Blue:
        income: 0.5
        points: 0.5
        experience: 0.5
      Navy:
        income: 0.5
        points: 0.5
        experience: 0.5
```

---

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
1.14.4
