### ISSUE TITLE
/jobs top showing 50 results, instead of the 15 in config

### ISSUE THREAD

**Issue by Seeroh** [Zrips/Jobs#576]
***Description of issue:***

When using /jobs top {job}, it should give out 15 results to the chat, as specified in my config. But instead, it gives out 50. If I hit the next tab, I get results 15-65. And so on.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
PageRow:
  JobsTop:
    # Defines amount of players to be shown in one page for /jobs top & /jobs gtop
    AmountToShow: 15
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper version git-Paper-210 (MC: 1.14.4)
