### ISSUE TITLE
CreateServerAccount option

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#63]
Hey Zrips, can you add a setting in the generalConfig.yml that allows for the creation of the server economy account? What I'm hoping can be added with the "UseServerAcount: true/false" is also a "CreateServerAccount: true/false". Note also that the option for UseServerAcount is missing a C (two c's in Account).
If both are true, then the AccountName (again two c's in account) would be created. Since I'm moving from Fe to SaneEconomy I lose the option to create the server account.

**Comment by smmmadden** [comment]
so was this added or not added?

**Comment by montlikadani** [comment]
It has been added for a long time, this is found in the generalConfig file. If you change the **AcountName** string to Server (as default), you will use the server account.

```
  # Server economy account
  # With this enabled, players will get money from defined user (server account)
  # If this account don't have enough money to pay for players for, player will get message
  UseServerAcount: false
  # Username should be with Correct capitalization
  AcountName: Server
  Taxes:
    # Do you want to use taxes feature for jobs payment
    use: false
    # Username should be with Correct capitalization, it can be same as setup in server account before
    AccountName: Server
    # Amount in percentage
    Amount: 15.0
    # Do you want to transfer taxes to server account
    TransferToServerAccount: true
    # With this true, taxes will be taken from players payment and he will get less money than its shown in jobs info
    # When its false player will get full payment and server account will get taxes amount to hes account
    TakeFromPlayersPayment: false
```
