### ISSUE TITLE
Taming is not working

### ISSUE THREAD

**Issue by sKye27** [Zrips/Jobs#633]
***Description of issue:**
When I try to tame any animal it does not give the reward for the taming. But the animal gets tamed.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Farmer:
    fullname: FARMER
    shortname: Fa
    description: '&b» &6Earns money by cultivating/n  &6crops, breeding animals and/n  &6taking care of the farm.'
    ChatColour: GREEN
    chat-display: full
    max-level: 500
    leveling-progression-equation: 20*(joblevel+joblevel)+(joblevel*joblevel)
    income-progression-equation: baseincome*0.4+(joblevel*0.007)
    points-progression-equation: (basepoints*0.2+(joblevel*0.01))*(joblevel*0.0005)
    experience-progression-equation: (baseexperience*0.2)-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    Gui:
      Item: WHEAT
    maxDailyQuests: 3
    Quests: []
    Tame:
      Wolf:
        income: 3.5
        points: 3.5
        experience: 8
      Horse:
        income: 3.5
        points: 3.5
        experience: 8
      Parrot:
        income: 3.5
        points: 3.5
        experience: 10
      Ocelot:
        income: 3.5
        points: 3.5
        experience: 8
      Llama:
        income: 3.5
        points: 3.5
        experience: 10
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
paper spigot
**Server Version (using `/ver`):** 
1.14.4-R0.1-SNAPSHOT
