### ISSUE TITLE
Custom permission nodes are not working

### ISSUE THREAD

**Issue by Feldmarschall** [Zrips/Jobs#639]
Custom permission nodes are not working since last patch. (jobs reborn 4.15.2)

**Server Type (Spigot/Paperspigot/etc):** 

Paper version git-Paper-45 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
Previous version: git-Paper-32 (MC: 1.15.1)

**Relevant plugins (Delete if this isn't needed):**

LuckPerms

**Comment by montlikadani** [comment]
Which permission nodes are not working?

**Comment by BoozleDoof** [comment]
I'm guessing, but probably related to this from Zrips Discord:
---
```
    # permissions granted for joining class
    permissions:
      # example node
      aaaaaatest.node:
        # true to give, false to revoke
        value: true
        # minimum level needed to grant permission. Use 0 for all levels
        level: 0
      aaaaaatest.node2:
        value: true
        # Permission granted when reaching level 10
        level: 10
    # Permissions granted when particular conditions are meet
```
---
The above was posted by in the 💬-help~2 channel within JobsReborn.
They mentioned using their own custom permission nodes in their configuration but ever since JobsReborn 4.15.2 they have stopped working.

**Comment by montlikadani** [comment]
https://github.com/Zrips/Jobs/issues/150 See my comment

**Comment by Feldmarschall** [comment]
Then why does it have the settings? You should take it out if it doesn't work.

**Comment by montlikadani** [comment]
Well, if something doesn't work, it doesn't have to be deleted; So far, I can tell you that if anyone has an idea to fix this, we are waiting for the PR to open it or maybe @Zrips will try to fix it.

**Comment by Feldmarschall** [comment]
I hope for the best. I think the function is really important. :)

**Comment by Blackyvk** [comment]
Is this the issue ? when I updated jobs it changed my permission nodes

from
```
      mcmmo.perks.xp.10percentboost.alchemy:
        value: true
        level: 25
```
to
```
      mcmmo:
        perks:
          xp:
            10percentboost:
              alchemy:
                value: true
                level: 25
```

**Comment by montlikadani** [comment]
@Blackyvk Temporary fix: https://github.com/Zrips/Jobs/commit/118b6d84594bf7f4b70b26acf4f023712ef1e23f

**Comment by Blackyvk** [comment]
it did not work, I compiled and tried but perms still changed

I tested version  4.15.1 and perms dont change, so something after that version broke it.

**Comment by montlikadani** [comment]
> it did not work, I compiled and tried but perms still changed
> 
> I tested version 4.15.1 and perms dont change, so something after that version broke it.

You should use "_" mark for permission name section instead of "." dots.
Eg
```
permissions:
    some_perm:
```

**Comment by EgidioBezerra** [comment]
Someone found a fix for this?

**Comment by montlikadani** [comment]
Seems to be this works correctly.
Correct usage:
```
permissions:
  fly:
    value: true
    permission: essentials.fly
    level: 2
```
