### ISSUE TITLE
Furnace and hopper money

### ISSUE THREAD

**Issue by PoulpinSky** [Zrips/Jobs#661]
If i turn reassign furnaces in exploitprotection in generalconfig to false,  furnace do not give any money for smelting items.
And if i turn it to true, hopper does not spill into furnaces.

**CONFIG SECTION**
```
ExploitProtections:
  Furnaces:
    # When enabled, players interacted furnaces will be saved into a file and will be reassigned after restart to keep giving out money
    # Players will no longer need to click on furnace to get paid from it after server restart
    Reassign: false
    # Defines max available furnaces each player can have to get paid from
    # This can be overridden with jobs.maxfurnaces.[amount] permission node
    MaxDefaultAvailable: 20
```

---

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 1.12.2**
