### ISSUE TITLE
Jobs with MySql

### ISSUE THREAD

**Issue by banit** [Zrips/Jobs#678]
When switching from sqlite to mysql jobs will create database entrys if you try to access the database for example with /jobs gtop it will throw this error in the console:

(Database is working fine for at least 10 other Plugins)

`11:31:39
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1,100' at line 1
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
at com.mysql.jdbc.Util.getInstance(Util.java:408)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
at com.gamingmesh.jobs.dao.JobsDAO.getGlobalTopList(JobsDAO.java:1638)
at com.gamingmesh.jobs.commands.list.gtop.perform(gtop.java:51)
at com.gamingmesh.jobs.commands.JobsCommands.onCommand(JobsCommands.java:97)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742)
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1821)
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1629)
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
at java.lang.Thread.run(Thread.java:748)`

```
 storage:
  # storage method, can be MySQL or sqlite
  method: mysql
# Requires Mysql.
mysql:
  username: root
  password: -----
  hostname: localhost
  database: Jobs
  table-prefix: jobs_
  verify-server-certificate: false
  use-ssl: false
  auto-reconnect: true
# How often in minutes you want it to save. This must be a non-zero number
save-period: 10
# Should player data be saved on disconnect?
# Player data is always periodically auto-saved and autosaved during a clean shutdown.
# Only enable this if you have a multi-server setup, or have a really good reason for enabling this.
# Turning this on will decrease database performance.
save-on-disconnect: true
# Tool used when selecting bounds for restricted area.
selectionTool: golden_hoe
# Enable if you are using one data base for multiple servers across bungee network
# This will force to load players data every time he is logging in to have most up to date data instead of having preloaded data
# This will enable automatically save-on-disconnect feature
MultiServerCompatability: true

```
---

Paper 112 1.15.2

Jobs 4.15.5
