### ISSUE TITLE
Player getting paid without doing anything

### ISSUE THREAD

**Issue by NikolaiCinotti** [Zrips/Jobs#697]
So, I have this custom job for "woodcutter" and the players are getting money with doing anything, they are breaking stones and dirt, or something  else or even afk and gain money/xp for the job

The job is exclusive to gain for breaking wood/log etc. I dont know what is happening and why they are gaining money/xp even if they are afk/stopped
This is the job:
```
Lenhador:
    fullname: Lenhador
    shortname: LN
    description: Ganhe quebrando madeiras.
    ChatColour: GOLD
    chat-display: full
    max-level: 1000
    vip-max-level: 2000
    slots: 10
    leveling-progression-equation: 550*(joblevel)+(joblevel*joblevel*32)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
      * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
      * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 259200
    maxDailyQuests: 2
    Quests:
      '1':
        Name: Its a nice day to cut all trees!
        Objectives:
        - Smelt;acacia_log;300
        - Smelt;birch_log;300
        - Smelt;oak_log;300
        RewardCommands:
        - money give [playerName] 25
        - msg [playerName] Completed quest!
        RewardDesc:
        - Clean this server
        - Get 25 for this!
    Gui:
      Id: 6
      Data: 0
    cmd-on-join:
      - msg [name] Now start working and get money from [jobname] job!
    cmd-on-leave:
      - msg [name] See you soon!
    Break:
      acacia_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      birch_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      dark_oak_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      jungle_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      oak_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      spruce_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      acacia_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      birch_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      dark_oak_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      jungle_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      spruce_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_acacia_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_acacia_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_birch_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_birch_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_dark_oak_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_dark_oak_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_jungle_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_jungle_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_oak_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_oak_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_spruce_log:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      stripped_spruce_wood:
        income: 0.001
        points: 0.00015
        experience: 0.00015
      acacia_leaves:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      birch_leaves:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      dark_oak_leaves:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      jungle_leaves:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      oak_leaves:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      spruce_leaves:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
```
