### ISSUE TITLE
Smelting blocks doesnt work.

### ISSUE THREAD

**Issue by NikolaiCinotti** [Zrips/Jobs#707]
The only block that works when I put in the furnace to smelt is cobblestone.

All nameblocks was check with /jobs blockinfo to get the correct name.

Theres no error in chat or console, it doesnt work (none bossbar and text etc)

Heres the job:

```
  Smelter:
    fullname: Smelter
    shortname: SL
    description: Ganhe derretendo coisas.
    ChatColour: GOLD
    chat-display: full
    max-level: 1000
    vip-max-level: 2000
    slots: 30
    leveling-progression-equation: 550*(joblevel)+(joblevel*joblevel*32)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
      * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
      * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 259200
    maxDailyQuests: 1
    Quests:
      '1':
        Name: Comer here Iron Man!
        Objectives:
        - Smelt;sand;320
        - Smelt;cobblestone;800
        - Smelt;smooth_stone;600
        RewardCommands:
        - money give [playerName] 20
        - msg [playerName] Completed quest!
        RewardDesc:
        - Clean this server
        - Get 20 for this!
    Gui:
      Id: 62
      Data: 0
    cmd-on-join:
      - msg [name] Now start working and get money from [jobname] job!
    cmd-on-leave:
      - msg [name] See you soon!
    Smelt:
      sand:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      cobblestone:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      sandstone:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      stone:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      quartz:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      clay:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      netherrack:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      clay_ball:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      stone_bricks:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      black_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      blue_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      brown_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      cyan_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      gray_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      green_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      light_blue_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      light_gray_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      lime_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      magenta_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      orange_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      pink_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      purple_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      red_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      white_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      yellow_terracotta:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      cactus:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      chorus_fruit:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      wet_sponge:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      sea_pickle:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
```

**Comment by montlikadani** [comment]
You should add the **result** of the material not the melted material.
Eg:
`sand` replace to `glass`

**Comment by NikolaiCinotti** [comment]
you should put this on the wiki in spigot page or the #comment codes then.

**Comment by montlikadani** [comment]
Ask Zrips, I don't have permission to edit the spigot page.

**Comment by NikolaiCinotti** [comment]
ty

**Comment by NikolaiCinotti** [comment]
So...
I did a test with a wood,
insted of wood I put a charcoal like you said.

still doesnt work.

**Comment by NikolaiCinotti** [comment]
@montlikadani 
I did another test, with glass and cobblestone. none work

```
Smelt:
      glass:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
      cobblestone:
        income: 0.0005
        points: 0.00010
        experience: 0.00010
```
