### ISSUE TITLE
disable-move-event: true on paper breaks PreventHopperFillUps

### ISSUE THREAD

**Issue by Nextopi** [Zrips/Jobs#714]
***Description of issue:**

If you set` Disable-move-event `to `true `on paper, this feature doesnt work, hoppers jobs will pay even if this anti exploit is on

---

**CONFIG SECTION**
```
  Smelt:
    # Prevent payments when hoppers moving items into furnace
    # Player will not get paid, but items will be smelted
    PreventHopperFillUps: true
  Brew:
    PreventBrewingStandFillUps: true
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.15.2-145
