### ISSUE TITLE
Memory leak on 1.16.1 with 4.16.0

### ISSUE THREAD

**Issue by KarlPro123** [Zrips/Jobs#715]
***Description of issue:**

Our server starts lagging, so I made a heap dump. In the dump, Jobs BlockProtection was one of the biggest problems. Please fix this!
---

**Picture of the leak in VisualVM (taking lots of memory)**
https://cdn.discordapp.com/attachments/669984865982218264/735824931505569832/Screenshot_8.png

**Config section**
```
General:
    # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
    # Modify restrictedBlocks.yml for blocks you want to protect
    PlaceAndBreakProtection: true
    # For how long in days to keep block protection data in data base
    # This will clean block data which ones have -1 as cooldown value
    # Data base cleanup will be performed on each server startup
    # This cant be more then 14 days
    KeepDataFor: 1
```

---

**Server Type (Spigot/Paperspigot/etc):** 

Paper, 1.16.1

**Server Version (using `/ver`):** 

Paper 110

OPENING THIS AS IT'S STILL NOT FIXED!

https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/container/BlockProtection.java
