### ISSUE TITLE
Wrong bossbar bracket payment calculation

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#737]
A player sometimes receive negative amounts in the bossbar for cooking chicken, porkshop, beef and mutton. However, money and XP are paid out normally and the bossbar XP display also increases. Only the number in brackets is wrong. The job itself does not involve any subtractions, so there should never be any negative figures.
The problem first appeared in version 4.15.7. A reload of the plugin does not cause any changes.

Screenshot: https://imgur.com/a/huj0bXM
```
    Smelt:
      COOKED_BEEF:
        income: 3.26
        experience: 3.26
      COOKED_PORKCHOP:
        income: 2.5
        experience: 2.5
      COOKED_CHICKEN:
        income: 4.3
        experience: 4.3
      COOKED_MUTTON:
        income: 3.1
        experience: 3.1
      COOKED_RABBIT:
        income: 3.3
        experience: 3.3
```
Jobs 4.15.7 
Paper 1.13.2 - 655
