### ISSUE TITLE
Milking mooshrooms

### ISSUE THREAD

**Issue by Elric02** [Zrips/Jobs#740]
***Description of issue:**

Milking mooshrooms (with a bowl) doesn't give money. Milking normal cows does.
EDIT : also tried with Mooshroom, Mushroom Cow and MushroomCow

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Milk:
      Mushroom_Cow:
        income: 0.65
        experience: 1.5
```

---

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
Paper 1.15.2 version 155
