### ISSUE TITLE
v4.15.8 No bonus work

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#745]
***Description of issue:**
With the new version, the enchantments work but the bonuses no longer work at all :(
---
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PiocheMineur:
  id: DIAMOND_PICKAXE
  name: '&2La Pioche du super mineur'
  lore:
  - '&5Cette pioche a appartenu'
  - '&5A un grand mineur'
  - '&5Mais nous avons oublié sont nom'
  - '&7Points/Exp : x3%'
  - '&7Argent : x2%'
  enchants:
  - DIG_SPEED=6
  - unbreaking=3
  - FORTUNE=3
  moneyBoost: 3.0
  expBoost: 4.0
  pointsBoost: 4.0
  jobs:
  - Mineur
  levelFrom: 1
  levelUntil: 100
TorcheMineur:
  id: torch
  name: '&2Vision nocturne'
  lore:
  - '&5Cette torche vous'
  - '&5Guidera dans les ténèbres'
  - '&7Points/Exp : x3%'
  - '&7Argent : x2%'
  enchants:
  - DURABILITY=3
  - fire_aspect=2
  moneyBoost: 2.0
  expBoost: 3.0
  pointsBoost: 3.0
  jobs:
  - Mineur
  levelFrom: 1
  levelUntil: 100 ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.12.2
![bug](https://user-images.githubusercontent.com/12047619/79113107-70348f00-7d80-11ea-9601-43eff64e5137.PNG)
