### ISSUE TITLE
Reward for killing squids

### ISSUE THREAD

**Issue by dusekdan** [Zrips/Jobs#760]
**Description of issue:**
Hello, I am using the latest version of the plugin on 1.15.2 server. 

I tried to define job that will reward players for killing squids (and tested this issue affects only squids by adding a reward for killing a pig too).

When player on the job kills pig, they receive experience and money. They receive nothing when killing squids. I am attaching relevant part of the job config below. It reports no issues, it just does not work.

---

**CONFIG SECTION:**
```
    Kill:
      SQUID:
        income: 2.0
        points: 2
        experience: 2.0
      PIG:
        income: 2.0
        points: 2
        experience: 2.0
```

---

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** CraftBukkit version git-Spigot-ae72bf4-183139d (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
