### ISSUE TITLE
Multiple reward

### ISSUE THREAD

**Issue by AxelJoue** [Zrips/Jobs#767]
**Description of issue:**
Be able to obtain the same trade reward several times from a certain level.
(You should be able to block multiple reward abstention, if it goes down in level, and then goes up.)
(Excuse me for my English)

---

**CONFIG SECTION :**
```
    commands:
      MsgMoneyGiveLvl50:
        command: msg [player] &cFélicitations ! &9Tu es niveau 50 en [jobname] !
        levelFrom: 50
        levelUntil: 50
```

---

**Server Type :** Spigot

**Server Version :** 1.15.2

**Plugin Version :** 4.15.7
