### ISSUE TITLE
Restricted blocks (Place and break protection) feature bug

### ISSUE THREAD

**Issue by Gumpah** [Zrips/Jobs#797]
Hi, I have an issue with the restricted blocks feature, for a time I had wood blocks in the restricted blocks list, but I took them off it, and somehow I still get the message some times : on the first oak log I place and break just after, and breaking logs pushed by pistons using a wood farm (I remind that it's while the broken blocks are not on the restricted blocks list
I have the latest version of the plugin (4.15.11)

---

```
# Block protected by timer in sec
# Category name can be any you like to be easily recognized
# id can be actual block id (use /jobs blockinfo to get correct id) or use block name
# By setting time to -1 will keep block protected until global cleanup, mainly used for structure blocks like diamond
# If you want to have default value for all blocks, enable GlobalBlockTimer in generalConfig file
blocksTimer:
  COAL_ORE: 2008000
  NETHER_QUARTZ_ORE: 2008000
  OBSIDIAN: 2008000
  REDSTONE_ORE: 2008000
  IRON_ORE: 2008000
  GOLD_ORE: 2008000
  LAPIS_ORE: 2008000
  DIAMOND_ORE: 2008000
  EMERALD_ORE: 2008000
```
---
```
  General:
    # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
    # Modify restrictedBlocks.yml for blocks you want to protect
    PlaceAndBreakProtection: true
    # For how long in days to keep block protection data in data base
    # This will clean block data which ones have -1 as cooldown value
    # Data base cleanup will be performed on each server startup
    # This cant be more then 14 days
    KeepDataFor: 14
    # All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: false
      timer: -1
```
---

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper # 185
