### ISSUE TITLE
The payment for crafting / dyeing of shulkerboxes doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#799]
The dyeing of coloured shulker boxes is not rewarded.
Here's what I've been trying to do:
```
    DYE:        
      WHITE_SHULKER_BOX:
        income: 0.44
        experience: 0.44
      ORANGE_SHULKER_BOX:
        income: 0.78
        experience: 0.78
      MAGENTA_SHULKER_BOX:
        income: 0.56
        experience: 0.56
      LIGHT_BLUE_SHULKER_BOX:
        income: 1.65
        experience: 1.65
      YELLOW_SHULKER_BOX:
        income: 0.56
        experience: 0.56
```
All other job values, for example the crafting of a normal shulkerbox are paid correctly, so it is not a setup problem.

Jobs 4.15.11
Paper 1.15.2 - 300
