### ISSUE TITLE
Placeholder don't give good decimals

### ISSUE THREAD

**Issue by Crusfire63** [Zrips/Jobs#801]
I don't have good decimals in scoreboard of sunlight plugins.
![image](https://user-images.githubusercontent.com/52324277/82801065-f9111100-9e7c-11ea-88f6-653b644140d9.png)
I use :
 - %jobsr_plimit_money% / %jobsr_limit_money%
 - %jobsr_plimit_exp% / %jobsr_limit_exp%

Config:
```
DecimalPlaces:
    Money: 2
    Exp: 2
    Points: 2
```
---

**Server Type : Spigot** 

**Server Version : Jobs 4.15.11 / 1.14.4**
