### ISSUE TITLE
Quest not reset correctly

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#805]
Description of issue :
For some mysterious reason it happens that certain quests once do not reset correctly ...
The person skip 2 quests and she finds herself with the quest impossible to do but validated ...

**CONFIG SECTION :**
```
#####################################
    Quests:
      '1':
        Name: blé !
        Objectives:
        - Break;wheat;512
        RewardCommands:
        - eco give [playerName] 500
        - jobs grantxp [playerName] paysan 100
        - tell [playerName] Quête terminée!
        RewardDesc:
        - Va casser du blé et tu gagneras un peu d'argent.
#####################################
```
---

**Server Type : Spigot:** 

**Server Version : This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)** 

![image](https://user-images.githubusercontent.com/12047619/83139937-7a6eda80-a0ed-11ea-8657-32f25e95679d.png)
