### ISSUE TITLE
Loading jobs scoreboard wipes all user scoreboard groups.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#82]
Compiled source as of https://github.com/Zrips/Jobs/commit/3f71080b028ac26e85fab586f37b319961e08ee3
Paper dev 1104 (Spigot 1.11.2)

```
Scoreboard:
  # This will enables to show top list in scoreboard instead of chat
  ShowToplist: true
  # For how long to show scoreboard
  interval: 10
```

When you load a jobs scoreboard, i.e. ```/jobs gtop```, it wipes all scoreboard groups a person is already a part of. It doesn't load / revert to their former groups when the jobs scoreboard disappears. 

This breaks things such as if a player had a scoreboard to disable player collision on login or if they had a custom scoreboard to colorize the nametag above their head based on their group.

McMMO's scoreboard properly hides user groups and then reverts back after its top players display is hidden. So might want to perhaps look into how McMMO saves and reverts the grouping to use a similar system for Jobs.
