### ISSUE TITLE
Permissions don't work

### ISSUE THREAD

**Issue by Volgeop** [Zrips/Jobs#826]
***Description of issue:**
Hi, I have issues with permission which don't work... I wanna give players kit on level 10 and then I wanna give VIP players on level 15 special kit VIP and remove clasic.... But they even don't get clasic kit on level 10....

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    conditions:
      first:
        requires:
        - j:hornik-15
        - p:group.vip
        perform:
        - p:cmi.kit.hornik-false
        - p:cmi.kit.hornikvip-true
    commands:
      kit:
        command:
        - lp user [player] permission set cmi.kit.hornik true server=Survival
        - msg [player] Byl ti odemčen kit horníka!
        levelFrom: 10
    cmd-on-leave:
    - lp user [player] permission unset cmi.kit.hornik server=Survival
    - lp user [player] permission unset cmi.kit.hornikvip server=Survival
```

---

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  354

**Relevant plugins (Delete if this isn't needed):**
