### ISSUE TITLE
level based permissions broken on jobs version 4.15.2+

### ISSUE THREAD

**Issue by Wolfhound1Z** [Zrips/Jobs#828]
Description of issue:
Level based permissions break on versions 4.15.2+ seemingly (Tested on jobs version 4.15.2 and 4.15.11 on a 1.15.1 server). After server restarts, the jobConfig.yml breaks single permissions into seperate lines, rendering them useless. On 4.15.11, correcting the config and reloading doesn't fix the issue and players are still unable to use their level permissions. Reverting to version 4.15.1 is the only thing that fixed this for us. I'll add an example of one of our level permissions that were broken.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

Before, when the permission worked and applied correctly:
```
    permissions:
      essentials.top:
        value: true
        level: 30
```

After updating the jobs plugin jar & restarting server, the config changes and breaks the permission:
```
    permissions:
      essentials:
        top:
          value: true
          level: 30
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper (a custom fork of it)
**Server Version (using `/ver`):** 
Custom fork of paper (MC version 1.15.1). Can go into more detail privately. (Discord is Wolfhound1#9085)
**Relevant plugins (Delete if this isn't needed):**
Luckperms version 5.1.26
