### ISSUE TITLE
Experience is not shown in global top leaderboards.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#83]
Compiled source as of https://github.com/Zrips/Jobs/commit/3f71080b028ac26e85fab586f37b319961e08ee3
Paper dev 1104 (Spigot 1.11.2)

```
Scoreboard:
  # This will enables to show top list in scoreboard instead of chat
  ShowToplist: false
  # For how long to show scoreboard
  interval: 10
```
