### ISSUE TITLE
Schedules bug

### ISSUE THREAD

**Issue by BleuBleue** [Zrips/Jobs#834]
***Description of issue: Hello. The schedule don't work. reload not fix that issue. Config has no problem and no error on console.**

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Enabled - with this false this schedule will be ignored
# From and Until is in 24 hours format with : signs to separate minutes and seconds
# Exp and Money determines how big is boost, to reset it. keep it at 1.0. so if you use 2.0 that means all money/exp is doubled
# Days variables: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, All
# Jobs can be any of your settup job or use All to give for all jobs at once
# BroadcastOnStart or BroadcastOnStop - set it false to disable message when boost starts/stops
# MessageOnStart or MessageOnStop - optional messages, if not given, then message from locale file will be shown
# BroadcastInterval - how often in minutes to broadcast message about money/exp boost for jobs
# BroadcastMessage - message to show every x minutes

Boost:
  BoostLundi:
    Enabled: true
    From: '19:30:00'
    Until: '20:30:00'
    Exp: 1.75
    Money: 1.75
    Days:
    - Monday
    Jobs:
    - Bucheron
    - Chasseur
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Boost d''xp et d''argent de +&c75% &esur &bBucheron &eet &bChasseur'
    - '&e* Valable pendant une heure à partir de &c19h30 &e!'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le boost d''xp et d''argent est désormais &cterminé&e !'
    - '&e* Tous les taux sont revenus à la normale'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Le boost d''xp et d''argent est disponible jusqu''à &c20h30&e !'
    - '&e******************************************************'
  BoostMardi:
    Enabled: true
    From: '19:30:00'
    Until: '20:30:00'
    Exp: 1.75
    Money: 1.75
    Days:
    - Tuesday 
    Jobs:
    - Fermier
    - Mineur 
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Boost d''xp et d''argent de +&c75% &esur &bFermier &eet &bMineur'
    - '&e* Valable pendant une heure à partir de &c19h30 &e!'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le boost d''xp et d''argent est désormais &cterminé&e !'
    - '&e* Tous les taux sont revenus à la normale'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Le boost d''xp et d''argent est disponible jusqu''à &c20h30&e !'
    - '&e******************************************************'
  BoostMercredi:
    Enabled: true
    From: '19:30:00'
    Until: '20:30:00'
    Exp: 1.5
    Money: 1.5
    Days:
    - Wednesday
    Jobs:
    - All
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Boost d''xp et d''argent de +&c50% &esur tous les metiers'
    - '&e* Valable pendant une heure à partir de &c19h30 &e!'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le boost d''xp et d''argent est désormais &cterminé&e !'
    - '&e* Tous les taux sont revenus à la normale'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Le boost d''xp et d''argent est disponible jusqu''à &c20h30&e !'
    - '&e******************************************************'
  BoostJeudi:
    Enabled: true
    From: '19:30:00'
    Until: '20:30:00'
    Exp: 1.75
    Money: 1.75
    Days:
    - Thursday
    Jobs:
    - Pecheur
    - Terraformeur
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Boost d''xp et d''argent de +&c75% &esur &bPecheur &eet &bTerraformeur'
    - '&e* Valable pendant une heure à partir de &c19h30 &e!'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le boost d''xp et d''argent est désormais &cterminé&e !'
    - '&e* Tous les taux sont revenus à la normale'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Le boost d''xp et d''argent est disponible jusqu''à &c20h30&e !'
    - '&e******************************************************'
  BoostVendredi:
    Enabled: true
    From: '19:30:00'
    Until: '20:30:00'
    Exp: 1.75
    Money: 1.75
    Days:
    - Friday
    Jobs:
    - Bucheron
    - Mineur
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Boost d''xp et d''argent de +&c75% &esur &bBucheron &eet &bMineur'
    - '&e* Valable pendant une heure à partir de &c19h30 &e!'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le boost d''xp et d''argent est désormais &cterminé&e !'
    - '&e* Tous les taux sont revenus à la normale'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Le boost d''xp et d''argent est disponible jusqu''à &c20h30&e !'
    - '&e******************************************************'
  BoostSamedi:
    Enabled: true
    From: '19:30:00'
    Until: '20:30:00'
    Exp: 1.75
    Money: 1.75
    Days:
    - Saturday
    Jobs:
    - Chasseur
    - Pecheur
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Boost d''xp et d''argent de +&c75% &esur &bChasseur &eet &bPecheur'
    - '&e* Valable pendant une heure à partir de &c19h30 &e!'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le boost d''xp et d''argent est désormais &cterminé&e !'
    - '&e* Tous les taux sont revenus à la normale'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Le boost d''xp et d''argent est disponible jusqu''à &c20h30&e !'
    - '&e******************************************************'
  BoostDimanche:
    Enabled: true
    From: '19:30:00'
    Until: '20:30:00'
    Exp: 1.75
    Money: 1.75
    Days:
    - Sunday
    Jobs:
    - Fermier
    - Terraformeur
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Boost d''xp et d''argent de +&c75% &esur &bFermier &eet &bTerraformeur'
    - '&e* Valable pendant une heure à partir de &c19h30 &e!'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le boost d''xp et d''argent est désormais &cterminé&e !'
    - '&e* Tous les taux sont revenus à la normale'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Le boost d''xp et d''argent est disponible jusqu''à &c20h30&e !'
    - '&e******************************************************'
```

---

**Server Type (Spigot/Paperspigot/etc): Spigot latest (1.16.1 build stable)** 

**Server Version (using `/ver`): 1.16.1**
