### ISSUE TITLE
Schedulers issue (not starting and cloning when jobs reload)

### ISSUE THREAD

**Issue by Flo-Nz** [Zrips/Jobs#835]
***Description of issue:**

--- Hello, my 11 schedulers are not starting when they should. And when I /jobs reload ; console says "22 schedulers loaded" as if they were cloned ! 

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## Boost:
  NightBoost:
    Enabled: true
    From: '23:00:00'
    Until: '07:00:00'
    Exp: 1.2
    Money: 1.2
    Days:
    - All
    Jobs:
    - All
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Nightboost activé ! Tous les jobs rapportent 1.5x XP & Money !'
    - '&e* Seulement pour la nuit !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le Nightboost est fini.'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 20
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* NIGTBOOST ! 1.5x money & xp boost jusque [until]  *'
    - '&e******************************************************'
  MondayMiner:
    Enabled: true
    From: '00:00:01'
    Until: '23:59:59'
    Exp: 1.5
    Money: 1.5
    Days:
    - Monday
    Jobs:
    - Miner
    - Digger
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Le Miner Monday est en marche !'
    - '&e* Les mineurs et diggers gagnent 1.5x plus d argent et XP !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le Miner Monday est terminé'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 60
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Salaire et exp x1.5 pour les miners et diggers'
    - '&e* Actif jusque demain !'
    - '&e******************************************************'
  TuesdayFarmerCrafterWeapon:
    Enabled: true
    From: '00:00:01'
    Until: '23:59:59'
    Exp: 1.5
    Money: 1.5
    Days:
    - Tuesday
    Jobs:
    - Farmer
    - Crafter
    - Weaponsmith
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Farmers et crafters boost !'
    - '&e* Farmers, Crafters, Weaponsmiths gagnent 1.5x plus d argent et XP !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le Boost est terminé'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 60
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Salaire et exp x1.5 pour Farmers, crafters, weapmonsmiths'
    - '&e* Actif jusque demain !'
    - '&e******************************************************'
  WesdnesdayMagic:
    Enabled: true
    From: '00:00:01'
    Until: '23:59:59'
    Exp: 1.5
    Money: 1.5
    Days:
    - Wednesday
    Jobs:
    - Brewer
    - Enchanter
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Le Magic Day démarre !'
    - '&e* Les enchanters et brewers gagnent 1.5x plus d argent et XP !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le Magic Day est terminé'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 60
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Salaire et exp x1.5 pour les enchanters et brewers'
    - '&e* Actif jusque demain !'
    - '&e******************************************************'
  ThursdayAdventure:
    Enabled: true
    From: '00:00:01'
    Until: '23:59:59'
    Exp: 1.5
    Money: 1.5
    Days:
    - Thursday
    Jobs:
    - Hunter
    - Explorer
    - Fisherman
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* C est le jour de l aventure !'
    - '&e* Les hunters, explorers et fishermen gagnent 1.5x plus d argent et XP !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le jour de l aventure est terminé'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 60
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Salaire et exp x1.5 pour les hunters, explorers et fishermen'
    - '&e* Actif jusque demain !'
    - '&e******************************************************'
  FridayBuild:
    Enabled: true
    From: '00:00:01'
    Until: '23:59:59'
    Exp: 1.5
    Money: 1.5
    Days:
    - Friday
    Jobs:
    - Builder
    - Woodcutter
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* C est le moment de Build des Chalets !'
    - '&e* Les builders et woodcutters gagnent 1.5x plus d argent et XP !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le Builder day est terminé'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 60
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* A vos builds ! Salaire et exp x1.5 pour les Builders et Woodcutters'
    - '&e* Actif jusque demain'
    - '&e******************************************************'
  SaturdayBoost1:
    Enabled: true
    From: '10:00:01'
    Until: '13:00:00'
    Exp: 1.0
    Money: 2.0
    Days:
    - Saturday
    Jobs:
    - All
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* BOOST !'
    - '&e* Tous les jobs rapportent x2 argent $$$ jusque [until] !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le BOOST est terminé'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* BOOST salaire x2 pour TOUS LES JOBS'
    - '&e* Actif jusque [until] !'
    - '&e******************************************************'
  SaturdayBoost2:
    Enabled: true
    From: '14:00:01'
    Until: '15:00:01'
    Exp: 2.0
    Money: 2.0
    Days:
    - Saturday
    Jobs:
    - All
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* GOLDEN HOUR !!!!!'
    - '&e* Tous les jobs rapportent x2 EXP ET $$$ jusque [until] !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* La GOLDEN HOUR est terminée'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 6
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* GOLDEN HOUR - x2 EXP et $$$ !'
    - '&e* Actif jusque [until] !'
    - '&e******************************************************'
  SaturdayBoost3:
    Enabled: true
    From: '17:00:01'
    Until: '20:00:00'
    Exp: 2.0
    Money: 1.0
    Days:
    - Saturday
    Jobs:
    - All
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* BOOST !'
    - '&e* Tous les jobs rapportent x2 EXP jusque [until] !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le BOOST est terminé'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* BOOST EXP x2 pour TOUS LES JOBS'
    - '&e* Actif jusque [until] !'
    - '&e******************************************************'
  SundayBoost1:
    Enabled: true
    From: '08:00:01'
    Until: '12:00:00'
    Exp: 1.5
    Money: 1.5
    Days:
    - Sunday
    Jobs:
    - All
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Déjà reveillé ? Profite du boost !'
    - '&e* 1.5x EXP et $$$ [until] !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le Sunday Morning Boost est terminé.'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* Réveil difficile ? 1.5x EXP et $$ ce matin !'
    - '&e* Actif jusque [until] !'
    - '&e******************************************************'
  SundayBoost2:
    Enabled: true
    From: '17:00:01'
    Until: '20:00:00'
    Exp: 2.0
    Money: 1.5
    Days:
    - Sunday
    Jobs:
    - All
    BroadcastOnStart: true
    MessageOnStart:
    - '&e***********************************************'
    - '&e* Fin du week-end... C est boost sur le serveur !'
    - '&e* Tous les jobs x2 EXP et x1.5 $$$ jusque [until] !'    
    - '&e***********************************************'
    BroadcastOnStop: true
    MessageOnStop:
    - '&e***********************************************'
    - '&e* Le BOOST fin du weekend est terminé'
    - '&e* Tout revient à la normale.'
    - '&e***********************************************'
    BroadcastInterval: 15
    BroadcastMessage:
    - '&e******************************************************'
    - '&e* BOOST fin du weekend actif !'
    - '&e* x2 EXP et x1.5 $$$ jusque [until] !'
    - '&e******************************************************' ##
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.15.2

**Relevant plugins (Delete if this isn't needed):**
EssentialsX
LuckPerms
Vault
