### ISSUE TITLE
Falling blocks treated as player placed

### ISSUE THREAD

**Issue by JamGallant** [Zrips/Jobs#836]
***Description of issue:**

Falling blocks such as gravel or sand are treated as though placed by player who made it fall and being picked up by the exploit protection.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  General:
    # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
    # Modify restrictedBlocks.yml for blocks you want to protect
    PlaceAndBreakProtection: true
    # For how long in days to keep block protection data in data base
    # This will clean block data which ones have -1 as cooldown value
    # Data base cleanup will be performed on each server startup
    # This cant be more then 14 days
    KeepDataFor: 14
    # All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: true
      timer: 180
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
git-Spigot-ad703da-d77f4d9 (MC: 1.16.1)
