### ISSUE TITLE
Global top outputs that it is displaying the top 15 but actually shows top 20.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#84]
Compiled source as of https://github.com/Zrips/Jobs/commit/3f71080b028ac26e85fab586f37b319961e08ee3
Paper dev 1104 (Spigot 1.11.2)

```
Scoreboard:
  # This will enables to show top list in scoreboard instead of chat
  ShowToplist: false
  # For how long to show scoreboard
  interval: 10
```

```/job gtop``` outputs that it is showing ```Top 15 players by global job level``` but actually displays 20 users.

When you type ```/jobs gtop 2```, the output ranges from 3 to 22 rather than a second page as well.
