### ISSUE TITLE
Payementmethod displaying when disabled

### ISSUE THREAD

**Issue by kristouffe** [Zrips/Jobs#844]
**DESCRIPTION OF ISSUE:**
PayementMethods are still displaying in jobs info/ jobs browse even if the payment method is disabled. I tried each combination, but it will display in any case, wether i have points, exp or income disabled.

Image of the issue:

![image](https://user-images.githubusercontent.com/39053190/86528420-e4765e80-bea7-11ea-96d8-ba10bd628ea5.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Economy:
  # By disabling one of these, players no longer will get particular payment.
  # Useful for removing particular payment method without editing whole jobConfig file
  PaymentMethods:
    Money: true
    Points: false
    Exp: true

```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-67 (MC: 1.16.1)
