### ISSUE TITLE
Points not saved

### ISSUE THREAD

**Issue by n54b** [Zrips/Jobs#848]
The points bug is still current, the database (SQLITE) does not save the players' data when disconnected or when scheduled ...

If I do a / editpoints set n54b 100 jobs, that I disconnect that I reconnect to look at my points I end up with the points before the set, its the same if I do ADD or TAKE ...

Would it be possible to add a command to execute which forces the backup of the database?
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
storage:
  # storage method, can be MySQL or sqlite
  method: sqlite
# Requires Mysql.
mysql:
  username: root
  password: ''
  hostname: localhost:3306
  database: minecraft
  table-prefix: jobs_
  verify-server-certificate: false
  use-ssl: false
  auto-reconnect: true
# How often in minutes you want it to save. This must be a non-zero number
save-period: 1
# Should player data be saved on disconnect?
# Player data is always periodically auto-saved and autosaved during a clean shutdown.
# Only enable this if you have a multi-server setup, or have a really good reason for enabling this.
# Turning this on will decrease database performance.
save-on-disconnect: true
```

---

**Server Type (Spigot/Paperspigot/etc):  SPIGOT  ** 

**Server Version (using `/ver`): 1.12.2**
