### ISSUE TITLE
Global top leaderboards displays your total level as 0 if you join a job and then leave it.

### ISSUE THREAD

**Issue by mibby** [Zrips/Jobs#86]
Compiled source as of https://github.com/Zrips/Jobs/commit/3f71080b028ac26e85fab586f37b319961e08ee3
Paper dev 1104 (Spigot 1.11.2)

```
Scoreboard:
  # This will enables to show top list in scoreboard instead of chat
  ShowToplist: false
  # For how long to show scoreboard
  interval: 10
```

* Players can only have 1 job at any given time per my config and there is no penalty set for leaving and rejoining a job.
* A player is level 11 in mining and level 8 in building.
* His global top rank should display him with a total level of 19.
* When he leaves his current active job and rejoins another, his global top rank updates to show his total level count being 0 and is no longer in the top list.
