### ISSUE TITLE
Items Disappearing in Furnaces 

### ISSUE THREAD

**Issue by JulianBooleanLau** [Zrips/Jobs#880]
***Description of issue:**

Numerous reports on my server that items in furnaces disappear after extended use. The bug is inconsistent and occurs even if the chunk where the furnace is loaded the whole time.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
ExploitProtections:
  Furnaces:
    # When enabled, players interacted furnaces will be saved into a file and will be reassigned after restart to keep giving out money
    # Players will no longer need to click on furnace to get paid from it after server restart
    Reassign: true
    # Defines max available furnaces each player can have to get paid from
    # This can be overridden with jobs.maxfurnaces.[amount] permission node
    MaxDefaultAvailable: 30
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
git-Paper-110 (MC: 1.16.1)

**Relevant plugins (Delete if this isn't needed):**
McMMO
