### ISSUE TITLE
Cobblestone generator problem

### ISSUE THREAD

**Issue by WarnDangerous** [Zrips/Jobs#885]
***Description of issue:**
When using AdvancedOreGen, if you create a generator and mine with the PlaceAndBreakProtection: true, on the first block you will earn exp/money, but on next blocks ( on the same place ), it will tell you that you can't earn money/exp from placed blocks.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
```  General:
    # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
    # Modify restrictedBlocks.yml for blocks you want to protect
    PlaceAndBreakProtection: true
    # For how long in days to keep block protection data in data base
    # This will clean block data which ones have -1 as cooldown value
    # Data base cleanup will be performed on each server startup
    # This cant be more then 14 days
    KeepDataFor: 1
    # All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: true
      timer: 30
    # Enable silk touch protection.
    # With this enabled players wont get paid for broken blocks from restrictedblocks list with silk touch tool.
    SilkTouchProtection: true```
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.12.2 Build 1618
**Jobs version :**
4.16.0
