### ISSUE TITLE
Armor, weapon, tool crafting exploit

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/Jobs#887]
When you combine armor pieces, tools or weapons in the crafting table, you get full reward for crafting an armor piece, tool or weapon. This is of course a disaster! You should only be rewarded by crafting armor pieces, tools or wepaons with materials like diamonds.If one also get money by combining all products, this is a fatal exploit!

Example config excerpt:
```
  Craft:
      DIAMOND_AXE:
        income: 278.24
        experience: 278.24
      DIAMOND_SWORD:
        income: 185.65
        experience: 185.65
      DIAMOND_SHOVEL:
        income: 93.05
        experience: 93.05
      DIAMOND_PICKAXE:
        income: 278.24
        experience: 278.24
      DIAMOND_HOE:
        income: 185.65
        experience: 185.65
      DIAMOND_BOOTS:
        income: 370.59
        experience: 370.59
      DIAMOND_LEGGINGS:
        income: 648.37
        experience: 648.37
      DIAMOND_CHESTPLATE:
        income: 740.96
        experience: 740.96
      DIAMOND_HELMET:
        income: 463.19
        experience: 463.19
```

Jobs 4.16.0 
Paper 1.16.1 - 134
