### ISSUE TITLE
MythicMob names not appearing on jobs info

### ISSUE THREAD

**Issue by Classicalad** [Zrips/Jobs#899]
***Description of issue:**
Names of mythic mobs not appearing next to their relevant payment/EXP info when doing both `/jobs info` or `/jobs browse` and then clicking/hovering.

[Jobs Browse](https://gyazo.com/c417e597b5ba753577568914e338c083)
[Jobs Info](https://gyazo.com/0f802c332562334fcf450f3a4cc1d4cb)
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Jobs:
  Cosmonaut:
    fullname: Cosmonaut
    shortname: O
    ChatColour: AQUA
    BossBarColour: WHITE
    chat-display: full
    max-level: 1000
    softIncomeLimit: 75
    leveling-progression-equation: 100*((1.13+(0.02*(1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.04)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.04)^(joblevel-1))
    MMKill:
      AncientGolem:
        income: 9.45
        experience: 7.40
```

```
AncientGolem:
  Display: '&eAncient Golem'
  Type: vindicator
  Health: 2500
  Damage: 80
  Equipment:
  - air:HEAD
  - air:HAND
  Options:
    FollowRange: 20
    PreventOtherDrops: true
    AlwaysShowName: true
    MovementSpeed: 0.3
  Disguise:
    Type: iron_golem
  Skills:
    - command{c="cmi saveditems get ancientgolemkey -t:<target.name> -a:1"} @trigger ~onDeath
    - skill{s=Shockwave} ~onCombat <80% 0.5
    - skill{s=Shockwave} ~onCombat <50% 0.8
    - skill{s=Suplex} ~onCombat 0.7
    - skill{s=SummonOldStatue} @self ~onSpawn
    - skill{s=antiknockbackskill} ~onDamaged
    - effect:itemspray{i=iron_ingot;a=3;d=10;v=1;yo=1.5} @origin ~onDamaged
    - effect:itemspray{i=iron_block;a=2;d=10;v=1;yo=1.5} @origin ~onDamaged
```
---

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):** paper 343

**Relevant plugins (Delete if this isn't needed):** MythicMobs, Jobs
