### ISSUE TITLE
Global block timer not working properly.

### ISSUE THREAD

**Issue by mrcoffee1026** [Zrips/Jobs#908]
***Description of issue:**
This is the portion of generalConfig.yml which this pertains to:
```
    # All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: true
      timer: 10
```
From the language used above, this timer should be in effect for 10 seconds AFTER THE PLAYER PLACES IT.  Instead, this timer appears to pre-exist in every block, for eternity.  With this set to true people are only getting paid about once in a glitch so often, but ALWAYS receive the message "you need to wait 10 seconds before getting paid for  this!"  The point is: they can wait 10 seconds or 10 months, but the next block they interact with will present the same exact message.  The "fix" for now is just shutting this off, but I had it on intentionally to avoid exploitive behavior like placing and breaking sugarcane repeatedly... without having to figure out what items like those are and placing them individually into the restrictedBlocks.yml list.  In any case if you figure out what is wrong with this setting I may use it again in the future.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  General:
    # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
    # Modify restrictedBlocks.yml for blocks you want to protect
    PlaceAndBreakProtection: true
    # For how long in days to keep block protection data in data base
    # This will clean block data which ones have -1 as cooldown value
    # Data base cleanup will be performed on each server startup
    # This cant be more then 14 days
    KeepDataFor: 1
    # All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: false
      timer: 10
    # Enable silk touch protection.
    # With this enabled players wont get paid for broken blocks from restrictedblocks list with silk touch tool.
    SilkTouchProtection: true
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
 This server is running Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
You can always recheck protected blocks before and after breaking them with /jobs bp command where black blocks will have infinite timer and white ones will be timed. But in general this is not reproducible currently. Keep in mind that block timer can be applied for placed blocks too, not only for broken.

**Comment by mrcoffee1026** [comment]
You seem to have misread the issue I posted since I already told you the timer is being applied to ALL blocks, not just placed blocks.  using the /jobs bp command does nothing while the option is set to false, it doesn't appear that there are any protected blocks anywhere, but then, I have the block timer set to false right now.  I can't set it to true since the result of doing so is this issue where people only get paid unintentionally by the plugin when lag allows it to happen.  Otherwise every block they touch will state they have to wait 10 seconds to get paid for this.  The problem is they could wait a year and the next block they touch would still say that.  The timer doesn't work, if you can't duplicate it, then you didn't try to use it.

**Comment by mrcoffee1026** [comment]
/jobs bp command says "No protected blocks found around you".  There are also no indicators of protected blocks.  The tree I was standing against when running that command I chop and it immediately says "You need to wait 9 more seconds to get paid for this!" as does every additional chopped tree which had grown up to adulthood long before I entered the area. That is with these following settings which clearly do not work as documented:
```
  General:
    # Enable blocks protection, like ore, from exploiting by placing and destroying same block again and again.
    # Modify restrictedBlocks.yml for blocks you want to protect
    PlaceAndBreakProtection: true
    # For how long in days to keep block protection data in data base
    # This will clean block data which ones have -1 as cooldown value
    # Data base cleanup will be performed on each server startup
    # This cant be more then 14 days
    KeepDataFor: 1
    # All blocks will be protected X sec after player places it on ground.
    GlobalBlockTimer:
      use: true
      timer: 10

```
Even if I had personally planted every tree I intended to chop, is was well over a day ago when I had so the protected data should be long since cleared.  The timer is 10 seconds, not 10 decades, so I can safely assume I do not need to wait any additional time frame to chop these trees to get paid, and yet every single tree I chop says this.  Random tp to uninhabited area I have never been in before yielded an identical result for every single tree.  /jobs bp command again shows no protected blocks around me before I attempted to chop, yet every chop I did would give me the same message on my screen and only about 1/10 chops received any - even partial - payment.
