### ISSUE TITLE
Doesn't create tables to database

### ISSUE THREAD

**Issue by ken-kentan** [Zrips/Jobs#921]
***Description of issue:**

Jobs Reborn doesn't create jobs tables to MySQL database when installing plugin in MySQL mode.

It doesn't log any errors...
So, Jobs seems working well but any jobs data (like player joined jobs) doesn't saved.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
storage.method: MySQL
mysql:
  username: minecraft
  password: ****************
  hostname: localhost:3306
  database: minecraft
MultiServerCompatability: true
```

---

**Server Type (Spigot/Paperspigot/etc):** 

Paperspigot

**Server Version (using `/ver`):** 

git-Paper-195 (MC: 1.16.3)

**Plugin Version**

4.16.1
