### ISSUE TITLE
Farmers not being paid for pumpkins

### ISSUE THREAD

**Issue by SavagePanda116** [Zrips/Jobs#925]
***Description of issue:**
Players with the Farmer job are not being paid for breaking pumpkins. We've tried it with axes and fists and neither work. 

---

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** 1.16.3

**Comment by SavagePanda116** [comment]
Not getting paid for Beetroots either.

**Comment by mattirizarry** [comment]
Please verify yours looks like mine. I am on the same setup as you with no issues.


```
      beetroots-3:
        income: 3
        experience: 3.0
      wheat-7:
        income: 3
        experience: 3.0
      carrots-7:
        income: 3
        experience: 3.0
      potatoes-7:
        income: 3
        experience: 3.0
      pumpkin:
        income: 5
        experience: 5
```
