### ISSUE TITLE
UseAsWhiteList option is not working properly!

### ISSUE THREAD

**Issue by Braynblocks** [Zrips/Jobs#929]
Description of issue:
---
---
I only want Jobs to work in the following worlds: world, resource_nether, resource_world, world_nether, & world_the_end. The config below was working just fine in Jobs 4.16.0, I updated to 4.16.2. With UseAsWhiteList set to true, every time I type a Jobs command this shows: "You can't use command in this world!". But if I set UseAsWhiteList to false and then removed the list of worlds, I can use it again just fine. This was working just fine last update and I believe this is a bug. I can also confirm that my config is working fine with the 4.16.0 version as I have switched versions twice.

**CONFIG SECTION:**
```
  DisabledWorlds:
    # By setting this to true, Jobs plugin will be disabled in given worlds
    # Only commands can be performed from disabled worlds with jobs.disabledworld.commands permission node
    Use: true
    # If true, will changes the list behavior, so if a world is added to list
    # the payments will only works in the given worlds.
    UseAsWhiteList: true
    List:
    - world
    - resource_nether
    - resource_world
    - world_nether
    - world_the_end
```

---

**Server Type (Spigot/Paperspigot/etc): Tuinity-1e695f4** 

**Server Version (using `/ver`): 1.16.3**
