### ISSUE TITLE
Job Limits Broken

### ISSUE THREAD

**Issue by BetaBurnt** [Zrips/Jobs#938]
***Description of issue:**
Job limits appear broken on 4.16.2 - Current setup on 4.16.1, no changes, set to limit earnings to $1million per hour and without changing anything on 4.16.2 the timer starts a new hour and sometimes it fails to give any income just giving XP.

Running "/jobs resetlimit all" when this happens gives it a kick, but it keeps happening again seemingly at random.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
No errors given.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```

  Limit:
    # Money gain limit
    # With this enabled, players will be limited how much they can make in defined time
    # Time in seconds: 60 = 1 min, 3600 = 1 hour, 86400 = 24 hours
    Money:
      Use: true
      # Do you want to stop money gain when exp limit reached?
      StopWithExp: false
      # Do you want to stop money gain when point limit reached?
      StopWithPoint: false
      # Equation to calculate max limit. Option to use total level to include players total amount levels of current jobs
      # You can always use simple number to set money limit
      # Default equation is: 500+500*(totallevel/100), this will add 1% from 500 for each level player have
      # So player with 2 jobs with level 15 and 22 will have 685 limit
      MoneyLimit: 1000000
      # Time in seconds: 60 = 1 min, 3600 = 1 hour, 86400 = 24 hours
      TimeLimit: 3600
      # Delay between announcements about reached money limit
      # Keep this from 30 to 5 min (300), as players can get annoyed of constant message displaying
      AnnouncementDelay: 30
```

---

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
03.10 21:17:28 [Server] INFO This server is running Paper version git-Paper-209 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
03.10 21:17:28 [Server] INFO Checking version, please wait...
03.10 21:17:28 [Server] INFO Previous version: git-Paper-208 (MC: 1.16.3)

**Relevant plugins (Delete if this isn't needed):**
Jobs 4.16.2.
