### ISSUE TITLE
stripping logs are respected as stripped_*_log block place

### ISSUE THREAD

**Issue by kikelkik** [Zrips/Jobs#940]
***Description of issue:***
---
When stripping logs by right clicking on it with an axe, Jobs respects it as if it has been placed which results in unwanted payments.

**CONFIG SECTION:**
```
*Extracted from jobConfig.yml*
Jobs:
  Gaertner:
    Place:
      STRIPPED_ACACIA_LOG:
        income: -2.49
        experience: -2.49
```
-2.49 will be charged if a player right clicks with an axe on acacia log to strip it. (should only happen when *placing* acacia log)

---

**Server Type (Spigot/Paperspigot/etc):** 
paperspigot

**Server Version (using `/ver`):** 
git-Paper-204 (MC: 1.16.3)

**Relevant plugins (Delete if this isn't needed):**
Jobs version 4.16.2
