### ISSUE TITLE
DisabledWorlds UseAsWhiteList seems broken in recent update

### ISSUE THREAD

**Issue by incredimike** [Zrips/Jobs#944]
***Description of issue:**

I think this broke with the last update:
```
  DisabledWorlds:
    # By setting this to true, Jobs plugin will be disabled in given worlds
    # Only commands can be performed from disabled worlds with jobs.disabledworld.commands permission node
    Use: true
    # If true, will changes the list behavior, so if a world is added to list
    # the payments will only works in the given worlds.
    UseAsWhiteList: true
    List:
    - survivalworld
```
I had to set `Use: false` to get Jobs working in `survivalworld`

Prior to disabling, the error I would receive is "You cannot use this command in this world"

---

**Server Type (Spigot/Paperspigot/etc):** Paper 

**Server Version (using `/ver`):** Paper 214 / 1.16.3
