### ISSUE TITLE
Quartz block unsupported?

### ISSUE THREAD

**Issue by EvilOlaf** [Zrips/Jobs#96]
Hey there,

players noticed that they do not get reward for placing quartz blocks as builder.
I tried to add these blocks to the `jobConfig.yml` and reload Jobs but they still do not get payment. All other defined blocks working as expected.
No error messages at reload, so I guess the file is configured correctly.
```
[...]
 Builder:
    fullname: Builder
    shortname: B
    description: Get cash for building.
    ChatColour: WHITE
    chat-display: full
    #max-level: 10
    #slots: 10
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    Gui:
      Id: 108
      Data: 0
    Place:
      STONE-2:
        income: 0.1
        points: 0.1
        experience: 0.2
      STONE-4:
        income: 0.1
        points: 0.1
        experience: 0.2
      STONE-6:
        income: 0.1
        points: 0.1
        experience: 0.2
[...]
      '155':
        income: 0.15
        points: 0.15
        experience: 0.2
      '155-1':
        income: 0.15
        points: 0.15
        experience: 0.2
      '155-2':
        income: 0.15
        points: 0.15
        experience: 0.2
[...]
```

Spigot 1.8.8
Jobs 3.9.1 (Yes, 3.9.3 is out, but as for the changelog the only difference is 1.12 support)
