### ISSUE TITLE
Bug with traduction

### ISSUE THREAD

**Issue by DjeyMute** [Zrips/Jobs#960]
Hello,

I have a problem with the last version of Jobs dev-release.
It's the translation for "newFurnaceRegistration" and "newBrewingRegistration" which are in my "messages_fr.yml" file since I am French.
![3](https://user-images.githubusercontent.com/47302852/95957497-1466c380-0e00-11eb-9f77-c1c1f64fb81d.png)

But for these 2 sentences the translations are replaced by the English file "newRegistration" (which I have now translated into French below) and the name of the item (brewing stand, furnace and blast furnace) is also in english.
![2](https://user-images.githubusercontent.com/47302852/95957367-ea150600-0dff-11eb-9e1b-673db9a6a1bc.png)
![4](https://user-images.githubusercontent.com/47302852/95957675-48da7f80-0e00-11eb-92d1-f9ba5924de8b.png)

Is it normal that the translation now uses only one variable or not?
Is it possible to have the name of the item translated?

---

Server Type : PaperSpigot

Server Version : 1.16.3

Version Jobs : Last version dev-release on Discord

**Comment by montlikadani** [comment]
Did you added these into `general.info` section?
```yml
    blocks:
      furnace: Furnace
      smoker: Smoker
      blastfurnace: Blast furnace
      brewingstand: Brewing stand
```
