### ISSUE TITLE
Missing Actions for Mooshrooms

### ISSUE THREAD

**Issue by B4m1237** [Zrips/Jobs#969]
***Description of issue:**

I'm attempting to pay players for the following actions;
- shearing a mooshroom with shears to receive mushrooms
- milking a mooshroom with a bucket (receives milk)
- "milking" a mooshroom with a bowl (receives soup)

The only action I was able to get working was milking mooshrooms with a bowl.
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
    Shear:
      mushroom_cow:
        income: 1
        points: 0
        experience: 5
    Milk:
      mushroom_cow:
        income: 0.35
        points: 0
        experience: 3
    Collect:
      mushroom_cow:
        income: 0.20
        points: 0
        experience: 2
```

---

**Server Type (Spigot/Paperspigot/etc):** 
Paper Spigot

**Server Version (using `/ver`):** 
Paper 1.16.3
