### ISSUE TITLE
/jobs gtop lists incorrect amount of entries.

### ISSUE THREAD

**Issue by SirKillian** [Zrips/Jobs#974]
**Plugin version:** 4.16.2
**Description of issue:**
When using the command /jobs gtop it shows an incorrect amount of entries.

_note: /jobs top displays the right amount._ 

According to my config it should list 10 entries. However, as shown below, it is listing 11 entries.
It appears no matter what the config value is, it always adds 1 extra.

**generalConfig.yml:**
```
Commands:
  PageRow:
    JobsTop:
      # Defines amount of players to be shown in one page for /jobs top & /jobs gtop
      AmountToShow: 10
```

![jobs-report](https://user-images.githubusercontent.com/19877696/97048424-b150fb80-157a-11eb-9077-04dae250beaf.png)
