### ISSUE TITLE
Paying for smelting doesn't work for terracotta and glazed terracottas

### ISSUE THREAD

**Issue by EkonC** [Zrips/Jobs#990]
**Job Smelter has an invalid Smelt type property - paying for smelting doesn't work for terracotta and glazed terracottas**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: white_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: orange_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: magenta_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: light_blue_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: yellow_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: lime_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: pink_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: gray_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: light_gray_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: cyan_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: purple_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: blue_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: brown_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: green_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: red_glazed_terracota!
>.... [21:49:38 WARN]: [Jobs] Job Smelter has an invalid Smelt type property: black_glazed_terracota!
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
...

    Smelt:
      terracota:
        income: 3.5
        experience: 3.5
      white_glazed_terracota:
        income: 1
        experience: 1
      orange_glazed_terracota:
        income: 1
        experience: 1
      magenta_glazed_terracota:
        income: 1
        experience: 1
      light_blue_glazed_terracota:
        income: 1
        experience: 1
      yellow_glazed_terracota:
        income: 1
        experience: 1
      lime_glazed_terracota:
        income: 1
        experience: 1
      pink_glazed_terracota:
        income: 1
        experience: 1
      gray_glazed_terracota:
        income: 1
        experience: 1
      light_gray_glazed_terracota:
        income: 1
        experience: 1
      cyan_glazed_terracota:
        income: 1
        experience: 1
      purple_glazed_terracota:
        income: 1
        experience: 1
      blue_glazed_terracota:
        income: 1
        experience: 1
      brown_glazed_terracota:
        income: 1
        experience: 1
      green_glazed_terracota:
        income: 1
        experience: 1
      red_glazed_terracota:
        income: 1
        experience: 1
      black_glazed_terracota:
        income: 1
        experience: 1

...
```

---

**Server Type:** 
Paper 253
**Server Version:** 
1.16.3
