### ISSUE TITLE
Item boosts dont work with netherite armour

### ISSUE THREAD

**Issue by TheCrunchy** [Zrips/Jobs#994]
Itemboost on netherite armour doesnt apply the boost when the armour is equipped, possibly because this class doesnt include it?
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/container/ArmorTypes.java
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
davesBoots:
  id: netherite_boots
  name: '&2Farmer Daves Boots'
  lore:
  - '&e5% Farmer Bonus Money'
  moneyBoost: 1.05
  expBoost: 1.0
  pointsBoost: 1.0
  jobs:
  - Farmer 
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):Paper** 

**Server Version (using `/ver`):git-paper-186**
