### ISSUE TITLE
Quest objective shear <color> nor color-all generate a reward

### ISSUE THREAD

**Issue by silentnyte** [Zrips/Jobs#999]
***Quest objective shear <color> nor color-all generate a reward:**

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
        Name: Shear sheep
        Chance: 6
        Objectives:
        - Shear;White;1
        RewardCommands:
        - eco give [playerName] 300
        - msg [playerName] completed a job quest!
        RewardDesc:
        - Earn 300 reward for
        - Shearing sheep
```

---

**Server Type Paperspigot:** 

**Server Version Paper version git-Paper-247 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT):**
